### PR TITLE
Add spider for Ernst & Young

### PR DESCRIPTION
**Pull request by thismakessand**
Scrapes 816 EY office locations worldwide

### CODE REVIEW

**Comment by thismakessand** [comment]
Is this the first place in Greenland? :greenland:

**Comment by iandees** [comment]
I'm feeling like we might want to spell out "EY". I don't think I've ever heard them referred to with that acronym before.

**Comment by thismakessand** [comment]
Yeah, I wasn't sure what to call it, but their website is all branded "EY" and it states at the bottom "EY refers to the global organization, and may refer to one or more, of the member firms of Ernst & Young Global Limited, each of which is a separate legal entity."

If you just mean the spider name/file name, then yeah I can for sure update that - the name that is being scraped is the name provided in the data.

**Comment by iandees** [comment]
Yea can you update the spider name and file name to `ernst_young`?

**Pull request merged**
