### PR TITLE
[vkusno_i_tochka_ru] fix broken spider.

### PR DESCRIPTION
**Pull request by panasonic-mafia**
Now the website is accessible only from Russian IP.

I'll comeback to opening hours later.

### CODE REVIEW

**Comment by panasonic-mafia** [comment]
The spider works from my locals from RU IP. Opening hours started to work again :)

<details><summary>Stats:</summary>

```json
{
 "atp/brand/Vkusno i tochka": 872,
 "atp/brand_wikidata/Q112406961": 872,
 "atp/category/amenity/fast_food": 872,
 "atp/field/country/from_spider_name": 872,
 "atp/field/email/missing": 872,
 "atp/field/image/missing": 872,
 "atp/field/phone/missing": 8,
 "atp/field/postcode/missing": 872,
 "atp/field/street_address/missing": 872,
 "atp/field/twitter/missing": 872,
 "atp/nsi/perfect_match": 872,
 "downloader/request_bytes": 319670,
 "downloader/request_count": 874,
 "downloader/request_method_count/GET": 874,
 "downloader/response_bytes": 1071541,
 "downloader/response_count": 874,
 "downloader/response_status_count/200": 874,
 "elapsed_time_seconds": 1080.883736,
 "feedexport/success_count/FileFeedStorage": 1,
 "finish_reason": "finished",
 "finish_time": "2023-11-20T04:36:28.772133+00:00",
 "httpcompression/response_bytes": 2374027,
 "httpcompression/response_count": 874,
 "item_scraped_count": 872,
 "log_count/INFO": 28,
 "memusage/max": 629817344,
 "memusage/startup": 142966784,
 "request_depth_max": 1,
 "response_received_count": 874,
 "robotstxt/request_count": 1,
 "robotstxt/response_count": 1,
 "robotstxt/response_status_count/200": 1,
 "scheduler/dequeued": 873,
 "scheduler/dequeued/memory": 873,
 "scheduler/enqueued": 873,
 "scheduler/enqueued/memory": 873,
 "start_time": "2023-11-20T04:18:27.888397+00:00"
}
```
</details>

@iandees would it be possible to merge the spider? 
Not sure why CI cannot run it successfully, but I noticed that `ScrapyZyteAPIDownloadHandler` is not mentioned in [log](https://data.alltheplaces.xyz/ci/6925604522/vkusno_i_tochka_ru/log.txt) at all.

**Comment by panasonic-mafia** [comment]
Thanks!

**Comment by Cj-Malone** [comment]
> Not sure why CI cannot run it successfully, but I noticed that ScrapyZyteAPIDownloadHandler is not mentioned in [log](https://data.alltheplaces.xyz/ci/6925604522/vkusno_i_tochka_ru/log.txt) at all.

I suspect GitHub secrets (`ZYTE_API_KEY`) are only loaded for collaborators, so CI was running without the proxy.

**Comment by iandees** [comment]
> GitHub secrets (ZYTE_API_KEY) are only loaded for collaborators

Yep, this is the case. I wish there was a way around it...

**Pull request merged**
