### PR TITLE
Add VicFreeWiFi (AU) (516 hotspots)

### PR DESCRIPTION
**Pull request by davidhicks**
Reference/source data: https://www.vic.gov.au/victorias-free-public-wifi

### CODE REVIEW

**Comment by davidhicks** [comment]
@Cj-Malone your thoughts on how to tag free Wi-Fi access points would be appreciated before I commit this project to any particular method. The Wi-Fi access points in this PR are located in parks on dedicated poles, on street lamp poles, on the side of buildings, on roofs of concourses at train stations, etc.

**Comment by Cj-Malone** [comment]
Since there are physical things, not just attributes of another POI, I think it's https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dantenna

**Comment by davidhicks** [comment]
Thanks, good suggestion for man_made=antenna, I've added it :)

**Comment by davidhicks** [comment]
Sorry I haven't properly figured out GitHub's stacked PRs. Got it working once and never again :(

**Comment by iandees** [comment]
No problem.

**Pull request merged**
