### PR TITLE
[ShellRecharge] Add category 

### PR DESCRIPTION
**Pull request by DivyaB1**
Hi,

This is my first commit to alltheplaces, I'm adding category to shellrecharge.
Any feedback will be much appreciated!

Thanks,

### CODE REVIEW

**Comment by iandees** [comment]
This is a great start, thank you!

**Comment by davidhicks** [comment]
I have an old open PR I haven't got around to completing at https://github.com/alltheplaces/alltheplaces/pull/5833 which was able to extract at least some Shell electric recharging locations.

Do you know if there is a 100% overlap, or whether the `shell` spider is only returning some of the full set of Shell electric recharge locations? Could both spiders be merged per https://github.com/alltheplaces/alltheplaces/pull/5833?

@Cj-Malone  @DivyaB1

**Comment by iandees** [comment]
(I merged this just for the category. Please continue discussion about merging the other Shell PR)

**Comment by Cj-Malone** [comment]
They don't seem to overlap. Black dots Shell Recharge, red dots Shell, data from the last weekly, but I don't think your PR gets more locations? Just more attributes.

image

(I loaded both files into JOSM and selected all on the layers, you can do conflation with a plugin, but it wasn't necessary in this case)

**Pull request merged**
