### PR TITLE
Rename GeojsonPointItem to Feature, part 2 of 5

### PR DESCRIPTION
**Pull request by brawer**

### CODE REVIEW

**Comment by brawer** [comment]
@iandees Looking at the logs of some failures, I believe they’re unrelated to this change. For example, spider [fairway_market_us](https://data.alltheplaces.xyz/ci/3854126099/fairway_market_us/log.txt) crashes with this change. But that spider hasn’t been yielding any features for a while, so the failure doesn’t appear to be new.

**Comment by iandees** [comment]
Yes, rerunning all the spiders through Github CI was probably not a great idea. In the future, when you change more than one or two spiders at a time please cancel the test-spider build if you can.

I haven't merged these yet because I would prefer to have it all in one change.

**Comment by brawer** [comment]
@iandees See https://github.com/alltheplaces/alltheplaces/pull/4597 for a pull request that renames any use of `GeojsonPointItem` in all spiders at once. Apparently, I don’t have permission to cancel the GitHub workflow.

**Comment by brawer** [comment]
Closing in favor of https://github.com/alltheplaces/alltheplaces/pull/4597.

**Pull request closed without merging**
