### PR TITLE
Add Dis-Chem (237 locations)

### PR DESCRIPTION
**Pull request by arrival-spring**
```
 'atp/brand/Dis-Chem': 237,
 'atp/brand_wikidata/Q97274558': 237,
 'atp/category/amenity/pharmacy': 237,
 'atp/category/multiple': 237,
 'atp/cdn/cloudflare/response_count': 245,
 'atp/cdn/cloudflare/response_status_count/200': 245,
 'atp/field/city/missing': 237,
 'atp/field/country/from_reverse_geocoding': 235,
 'atp/field/country/missing': 2,
 'atp/field/email/missing': 237,
 'atp/field/image/missing': 237,
 'atp/field/lat/missing': 2,
 'atp/field/lon/missing': 2,
 'atp/field/operator/missing': 237,
 'atp/field/operator_wikidata/missing': 237,
 'atp/field/phone/invalid': 6,
 'atp/field/phone/missing': 1,
 'atp/field/postcode/missing': 237,
 'atp/field/state/missing': 2,
 'atp/field/street_address/missing': 237,
 'atp/field/twitter/missing': 237,
 'atp/item_scraped_host_count/www.dischem.co.za': 237,
 'atp/nsi/perfect_match': 237,
```

### CODE REVIEW

**Comment by arrival-spring** [comment]
Strange, because ones causing the exception are meant to be blocked by robots.txt (so it works fine locally), but maybe somehow different robots files are being served?

Anyway, I'll work around it

**Comment by arrival-spring** [comment]
I don't understand why this is failing, it's worked fine locally the whole time

**Comment by CloCkWeRX** [comment]
Failure is jq: error: Could not open file /tmp/output/dis_chem/stats.json: No such file or directory

**Comment by iandees** [comment]
This happens when `scrapy` is waiting around for a network response and never exits, so the `timeout` shell wrapper does it for us. This results in an empty stats JSON. This is usually a sign that something is doing SSL fingerprinting or otherwise blocking connections from the IP we're making requests from.

**Comment by arrival-spring** [comment]
We got all 237 results in the latest run

**Pull request merged**
