### PR TITLE
Add Shoprite (ZA)

### LINKED ISSUE #8069: Shoprite (ZA)
----
### Brand name

Shoprite

Africa's largest food retailer.

### Wikidata ID

Q1857639
https://www.wikidata.org/wiki/Q1857639
https://www.wikidata.org/wiki/Special:EntityData/Q1857639.json

### Store finder url(s)

Official Url(s): http://www.shoprite.co.za
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q1857639 http://www.shoprite.co.za`
```
```
https://www.shoprite.co.za/store-finder

### PR DESCRIPTION
**Pull request by davidhicks**
Fixes #8069

### CODE REVIEW

**Comment by davidhicks** [comment]
@iandees Looks like the new CodeBuild CI system needs to have Playwright installed correctly?

**Comment by iandees** [comment]
Yea, the install steps for Playwright might not work in this system. 🤔 I'll take a look.

**Comment by davidhicks** [comment]
@iandees To help with merging prior to Playwright being fixed with AWS CodeBuild, I've provided output from this new spider below:

```
{'atp/brand/Shoprite': 492,
 'atp/brand_wikidata/Q1857639': 492,
 'atp/category/shop/supermarket': 492,
 'atp/field/city/missing': 1,
 'atp/field/country/from_spider_name': 492,
 'atp/field/email/missing': 492,
 'atp/field/image/missing': 492,
 'atp/field/operator/missing': 492,
 'atp/field/operator_wikidata/missing': 492,
 'atp/field/phone/invalid': 11,
 'atp/field/twitter/missing': 492,
 'atp/nsi/category_match': 492,
 'downloader/request_bytes': 281364,
 'downloader/request_count': 518,
 'downloader/request_method_count/GET': 518,
 'downloader/response_bytes': 314249383,
 'downloader/response_count': 518,
 'downloader/response_status_count/200': 493,
 'downloader/response_status_count/404': 25,
 'elapsed_time_seconds': 1899.247244,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 5, 15, 16, 53, 50, 495959, tzinfo=datetime.timezone.utc),
 'httperror/response_ignored_count': 25,
 'httperror/response_ignored_status_count/404': 25,
 'item_scraped_count': 492,
 'log_count/DEBUG': 177706,
 'log_count/INFO': 69,
 'memusage/max': 306593792,
 'memusage/startup': 163491840,
 'playwright/context_count': 1,
 'playwright/context_count/max_concurrent': 1,
 'playwright/context_count/persistent/False': 1,
 'playwright/context_count/remote/False': 1,
 'playwright/page_count': 518,
 'playwright/page_count/closed': 517,
 'playwright/page_count/max_concurrent': 1,
 'playwright/request_count': 88082,
 'playwright/request_count/aborted': 86554,
 'playwright/request_count/method/GET': 88082,
 'playwright/request_count/navigation': 1528,
 'playwright/request_count/resource_type/document': 1528,
 'playwright/request_count/resource_type/font': 2068,
 'playwright/request_count/resource_type/image': 9888,
 'playwright/request_count/resource_type/images': 1034,
 'playwright/request_count/resource_type/script': 68394,
 'playwright/request_count/resource_type/stylesheet': 5170,
 'playwright/response_count': 1528,
 'playwright/response_count/method/GET': 1528,
 'playwright/response_count/resource_type/document': 1528,
 'request_depth_max': 1,
 'response_received_count': 518,
 'scheduler/dequeued': 518,
 'scheduler/dequeued/memory': 518,
 'scheduler/enqueued': 518,
 'scheduler/enqueued/memory': 518,
 'start_time': datetime.datetime(2024, 5, 15, 16, 22, 11, 248715, tzinfo=datetime.timezone.utc)}
```

**Comment by iandees** [comment]
I switched to x86 Lambda platform today. Let's see if it helps.

**Comment by iandees** [comment]
Well that was obnoxiously difficult, but it seems to work now.

**Comment by iandees** [comment]
In the end, I switched CodeBuild to use an EC2 image (so that it would run as a consistent user) and allowed `playwright install-deps` to work.

**Comment by Firefishy** [comment]
Shoprite has many more than just 10 stores. Example of missing store is Shoprite Hyper Greenacres

**Comment by iandees** [comment]
The CI system only gives each spider 60 seconds to do its thing before getting stopped. This one still had more work to do (thus the `timeout`) and so it likely will get more in the weekly run.

**Pull request merged**
