### PR TITLE
Create charles_tyrwhitt.py

### PR DESCRIPTION
**Pull request by TheUKHighStreet**

### CODE REVIEW

**Comment by arrival-spring** [comment]
You're missing the .py file extension, which I think is why scraperbot hasn't commented

**Comment by TheUKHighStreet** [comment]
Thank you - that would have taken me a while to spot!

**Comment by TheUKHighStreet** [comment]
I'm stuck. It runs locally and finds 47 stores.

**Comment by TheUKHighStreet** [comment]
Thank you! Sorry - I knew it would be something stupid.

**Pull request merged**
