### PR TITLE
Add Vivacom spider

### LINKED ISSUE #3713: Vivacom
https://www.vivacom.bg/bg/residential/magazini

Brand tags:
```
brand=Vivacom
brand:wikidata=Q7937522
```

### PR DESCRIPTION
**Pull request by Cj-Malone**
Ideally @Dimitar5555 will check the output on this one.
Fixes #3713

### CODE REVIEW

**Comment by Dimitar5555** [comment]
The image tag is not needed since it points to the partner's logo (partner being a different company which offers some of Vivacom's services). I'm not entirely sure if these partners should appear at all since they are entirely different amenities (payment centres, posts, banks etc.). A good filter for them would be to exclude all POIs that don't have `image=https://www.vivacom.bg/web/images/stores/*.jpg` where `*` can be any number from 1 to 8

It would be nice to include the openning hours if possible.
Пон. - Monday
Пет. - Friday
Съб. - Saturday
Нед. - Sunday

**Comment by Cj-Malone** [comment]
OK, I've dropped the partners, and all the images as they were bad quality. I've also added the opening hours, they are inconsistent and a pain to parse. If someone wants to do a follow up PR to better format them, I'd be grateful.

**Comment by Dimitar5555** [comment]
You need to add ```.replace(":", "").replace(".", ":").replace(",", ";").replace(" -", "-").replace("- ", "-")``` for the opening hours to work correctly. Everything else looks good.

**Comment by Cj-Malone** [comment]
That still doesn't work for all of them.

It leaves us with `opening_hours=Mo-Fr 09:00-19:00; Sa 1000-1700; Su off` where there times do use "10:00", even though most of them are "10.00".

Some others include:

`opening_hours=Mo- Su08:00-21:00`
`opening_hours=Mo-Fr 08:00-19:00; Sa10:00-18:00-Su off`
`opening_hours=Mo-Fr 09:00-19:30; Sa 1000-1700;-Su off`

I don't want to get stuck in the weeds with the opening hours, if Vivacom improves there data I'll happily parse it. Or if someone else manages to parse the current mess, I'm sure @iandees would accept it.

**Comment by Cj-Malone** [comment]
After saying that, I think I've done it.

**Pull request merged**
