### PR TITLE
Add brand:wikidata documentation

### PR DESCRIPTION
**Pull request by iandees**
Adding details about `brand:wikidata` column for #1343.

### CODE REVIEW

**Comment by thomas536** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/tgarner/projects/third_party/github.com/thomas536/alltheplaces/locations/pipelines.py", line 42, in process_item
    item[key] = value
  File "/usr/lib/python3/dist-packages/scrapy/item.py", line 73, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'GeojsonPointItem does not support field: brand:wikidata'
```

**Comment by iandees** [comment]
Can you try using `brand_wikidata` in the spider output now?

**Comment by thomas536** [comment]
I pulled in your changed and tested it out, and it seems ok to me. I still see the underscore in my json test output, but I'm not familiar enough with how everything gets transformed to know if that's working as intended or not.

**Comment by iandees** [comment]
If you run using the GeoJSON outputter it should transform the `brand_wikidata` to `brand:wikidata`. I'll merge and we can fix any bugs that come up.

**Pull request merged**
