### PR TITLE
[American Golf GB] Create american_golf_gb.py

### PR DESCRIPTION
**Pull request by TheUKHighStreet**

### CODE REVIEW

**Comment by TheUKHighStreet** [comment]
Sorry about the messy pull request - still learning.
I've tested this American Golf scraper locally and it works if you ignore robots.txt.

**Comment by TheUKHighStreet** [comment]
Found the setting to ignore robots.txt.

**Comment by mjoe999** [comment]
Looks fine but `item = DictParser.parse(location)` would save you a few lines of "boiler plate" settings e.g.

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/versace.py#L27

**Comment by TheUKHighStreet** [comment]
> Looks fine but `item = DictParser.parse(location)` would save you a few lines of "boiler plate" settings e.g.
> 
> https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/versace.py#L27

Thanks - grateful for any pointers.

**Pull request merged**
