### PR TITLE
Harris Teeter

### LINKED ISSUE #148: Harris Teeter
Mostly southeastern https://www.harristeeter.com/store/#/app/store-locator

### PR DESCRIPTION
**Pull request by vlad555**
Fixes #148

### CODE REVIEW

**Comment by vlad555** [comment]
It's sad to admit,
But it was necessary to integrate cookies into spider :-(
They are dynamically generated and site don't give answer without them.
So they could expire in future

**Comment by iandees** [comment]
I think the session cookies time out after a while. It might be a good idea to start at a normal page, [let it set cookies](https://blog.scrapinghub.com/2016/03/23/scrapy-tips-from-the-pros-march-2016-edition/) and then spider into the other pages?

**Comment by vlad555** [comment]
Sad to  admit, but it's necessary javascript to generate cookies.
I don't understand how to move further without javascript rendering here

**Comment by evanmosseri** [comment]
I'm on it

**Comment by vlad555** [comment]
cool!!
do we have permission to use javascript rendering libs?
it's not first one I need these libs.

**Comment by evanmosseri** [comment]
You don't need javascript for this, you just need to get the cookies from a response object and pass it down to further requests

**Comment by vlad555** [comment]
:-) I'll be glad if it will be enough
Let's wait your solution .

**Comment by vlad555** [comment]
I don't know if you need it, but cookies you need to send request:
_gag
HTAPIADMSESID
_ga
_gid
First pair you really got from first request
Look where to take second.
Good luck

**Pull request closed without merging**
