### PR TITLE
[rituals] Add spider (1165 stores)

### PR DESCRIPTION
**Pull request by hfs**
Add [Rituals](https://www.rituals.com/) cosmetics stores worldwide.

### CODE REVIEW

**Comment by hfs** [comment]
The CI pipeline is run with `CLOSESPIDER_TIMEOUT=60`, but that’s not enough for this spider. The spider makes on the order of 5000 requests. The sitemap lists also non-Rituals shops which sell their products, which we are not interested in. Only the pages for their Rituals branded shops have the Structured Data, so the StructuredDataSpider is extracting exactly the right subset of shops.

Maybe you can run the spider locally to review it?

**Comment by iandees** [comment]
Can you tighten up the sitemap filter so that it only makes requests for pages that we want?

**Comment by hfs** [comment]
Unfortunately the wanted shops cannot be detected from the URL. I *can* exclude the most common non-wanted shops based on their brand name, though. Would this be an acceptable solution?

**Comment by iandees** [comment]
Sure, that sounds good.

**Pull request merged**
