### PR TITLE
Regis Salons

### PR DESCRIPTION
**Pull request by DerekMcDaniel**
For #655 

Added spider for Regis Salons

### CODE REVIEW

**Comment by DerekMcDaniel** [comment]
ah somethings wrong, I think ill have to search by full state rather than abbreviation. Will fix !

**Comment by DerekMcDaniel** [comment]
Actually turns out that even though it includes the search state in the url it defaults back to lat/lon search. I think I can use the form to populate the lat/lon however

**Comment by DerekMcDaniel** [comment]
Still need to check smaller radius for more stores. Results are capped at 100 per. Also, Regis owns a lot of brands such as supercuts, its unclear at the moment whether all of those locations will be served

**Comment by DerekMcDaniel** [comment]
@iandees Searching by 200 mile radius returned ~30 less results. Also I checked store locator on supercuts vs Regis salons and they do not match up. So while Regis Salons is reported to have more than 9,000 locations it looks like they will be have to done individually.  With the large radius I can include Canada and the UK without too many requests.

**Comment by DerekMcDaniel** [comment]
Picking up Canada but not UK. Looks like UK has its own website

**Comment by iandees** [comment]
Please make another spider for the UK.

**Pull request merged**
