### PR TITLE
Red Lobster

### LINKED ISSUE #105: Red Lobster
https://www.redlobster.com/

### PR DESCRIPTION
**Pull request by whoissteven**
Fixes #105.

### CODE REVIEW

**Comment by whoissteven** [comment]
Do you prefer to have the Full Address on one line or can it be separated as address1 and address2? Two lines.

Thanks

**Comment by iandees** [comment]
Let's just keep address1 by itself.

**Comment by whoissteven** [comment]
@iandees, so have address1 and address2 or its good as is w/o address2? thanks

**Comment by iandees** [comment]
Skip address2.

**Comment by whoissteven** [comment]
Cool. This is all done here to merge pending your approval.

**Pull request merged**
