### PR TITLE
[Big Table Group GB] Add and fix spiders

### PR DESCRIPTION
**Pull request by TheUKHighStreet**
Updating spiders for https://www.bigtablegroup.com
Please let me know if I'm doing something wrong as I've only just started using github.

### CODE REVIEW

**Comment by Cj-Malone** [comment]
I'll fix the website

**Comment by TheUKHighStreet** [comment]
Thanks - fast learning curve as I'm used to programming in perl rather than python.
I think I need that fix for the website for Cafe Rouge as well.

**Comment by Cj-Malone** [comment]
I think this is better

**Comment by TheUKHighStreet** [comment]
Theres also Banana Tree - can you see that or do I need to do another pull request?

**Comment by TheUKHighStreet** [comment]
Oh - and chiquito - which is an update of an existing spider.

**Comment by Cj-Malone** [comment]
I don't usually do ones that small (Banana Tree and Café Rouge), but I will since it's almost no code, and to welcome you.

I'll sort out Chiquito too.

**Comment by TheUKHighStreet** [comment]
Thanks :)

**Pull request closed without merging**
