### PR TITLE
adding spider superonefoods

### PR DESCRIPTION
**Pull request by ADWSr**
init commit for superonefoods

### CODE REVIEW

**Comment by ADWSr** [comment]
I'm running Python 2.7 and the CI tested my spider using 3.6, could that be why it failed?

**Comment by iandees** [comment]
It's failing because it can't run the build from a fork for security reasons. Can you re-open this pull request from the `alltheplaces` repo instead of your fork?

**Comment by ADWSr** [comment]
I sure can, my brain freeze on that!

**Comment by ADWSr** [comment]
closing pr

**Pull request closed without merging**
