### PR TITLE
Village Inn

### LINKED ISSUE #137: Village Inn
http://www.villageinn.com/locations/

### PR DESCRIPTION
**Pull request by Eagle19243**
Fixes #137.

### CODE REVIEW

**Comment by Eagle19243** [comment]
@iandees, Could you please review the last commit?

**Comment by Eagle19243** [comment]
@iandees, What is preferred  format for `opening_hours`? Could you please describe an example here?

**Comment by iandees** [comment]
@Eagle19243 The opening_hours property should follow the OpenStreetMap opening_hours format. There are examples [in their wiki page](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Examples). All of the other spiders have some code to handle this that could be useful to follow. Let me know if you need some more guidance.

**Comment by Eagle19243** [comment]
Nothing for now. Thanks for your guide.

**Pull request merged**
