### PR TITLE
Allow spiders to tag output with machine-readable metadata

### PR DESCRIPTION
**Pull request by brawer**
For the motivation of this change, see
https://github.com/alltheplaces/alltheplaces/issues/4338.

### CODE REVIEW

**Comment by iandees** [comment]
Can you think of a way to move the FeatureCollection properties to the top of the file?

**Comment by brawer** [comment]
I tried, but didn’t manage. The problem is that Scrapy doesn’t pass the spider to exporters — if I understand correctly, the framework is built for multiple spiders running in parallel within in the same process, so theoretically (but not with ATP) a single exporter instance may combine data from many different spiders into one single file. On the other hand, surely there must be _some_ way to find the name of the currently running spider? Maybe you’ll see have an idea how to do this?

**Comment by brawer** [comment]
> Can you think of a way to move the FeatureCollection properties to the top of the file?

Buffering the data into a temp file? If we do that, we could also compute a `bbox` for the FeatureCollection, and sort the features by `id`; this would stabilize the file contents across weekly runs. Not sure if anyone cares, but why not.

**Comment by brawer** [comment]
Ah, perhaps the exporter could overwrite `export_item()` and delay writing the header when it receives the first item to export. I’ll give that a try, but it’ll have to wait a couple days.

**Comment by iandees** [comment]
Unrelated to this change, but the exporter needs to be looked at again because when a spider emits an exception and crashes, the exporter doesn't get the `export_finished()` call and the resulting GeoJSON file is broken as a result. Maybe we could write to CSV and then some external process could convert to GeoJSON + add the feature collection properties?

**Comment by brawer** [comment]
> Unrelated to this change, but the exporter needs to be looked at again because when a spider emits an exception and crashes, the exporter doesn't get the `export_finished()` call and the resulting GeoJSON file is broken as a result. Maybe we could write to CSV and then some external process could convert to GeoJSON + add the feature collection properties?

Here’s a proposal to handle this particular problem in a slightly different way, which would also help with other sources of flakiness: https://github.com/alltheplaces/alltheplaces/issues/4351

**Comment by brawer** [comment]
> Can you think of a way to move the FeatureCollection properties to the top of the file?

Yes, after some back and forth I figured out a way. Please take another look.

**Pull request merged**
