### PR TITLE
Aunt Anne

### LINKED ISSUE #382: Auntie Anne's
http://hosted.where2getit.com/auntieannes/2014/ajax?&xml_request=%3Crequest%3E%3Cappkey%3E6B95F8A2-0C8A-11DF-A056-A52C2C77206B%3C%2Fappkey%3E%3Cformdata+id%3D%22locatorsearch%22%3E%3Cdataview%3Estore_default%3C%2Fdataview%3E%3Climit%3E2500%3C%2Flimit%3E%3Cgeolocs%3E%3Cgeoloc%3E%3Caddressline%3EMinneapolis+MN+55412%3C%2Faddressline%3E%3Clongitude%3E%3C%2Flongitude%3E%3Clatitude%3E%3C%2Flatitude%3E%3C%2Fgeoloc%3E%3C%2Fgeolocs%3E%3Csearchradius%3E5000%3C%2Fsearchradius%3E%3C%2Fformdata%3E%3C%2Frequest%3E

### PR DESCRIPTION
**Pull request by kristinepetrosyan**
Closes #382

### CODE REVIEW

**Comment by iandees** [comment]
It'd be great to get more than 1000 locations. There's also locations outside of the US.

**Comment by kristinepetrosyan** [comment]
@iandees can I write a separate spider for the other locations? That was USA will be separate.

**Comment by kristinepetrosyan** [comment]
@iandees this was the link i used..Should I be changing this link?

http://hosted.where2getit.com/auntieannes/2014/ajax?&xml_request=%3Crequest%3E%3Cappkey%3E6B95F8A2-0C8A-11DF-A056-A52C2C77206B%3C%2Fappkey%3E%3Cformdata+id%3D%22locatorsearch%22%3E%3Cdataview%3Estore_default%3C%2Fdataview%3E%3Climit%3E2500%3C%2Flimit%3E%3Cgeolocs%3E%3Cgeoloc%3E%3Caddressline%3EMinneapolis+MN+55412%3C%2Faddressline%3E%3Clongitude%3E%3C%2Flongitude%3E%3Clatitude%3E%3C%2Flatitude%3E%3C%2Fgeoloc%3E%3C%2Fgeolocs%3E%3Csearchradius%3E5000%3C%2Fsearchradius%3E%3C%2Fformdata%3E%3C%2Frequest%3E

**Comment by iandees** [comment]
They limit queries to 1000 results and there are more than 1000 stores. You could add multiple queries with different lat/lons to cover the US and see if that gets you everything.

**Comment by kristinepetrosyan** [comment]
The build timed out but on my local I got 1702

**Comment by kristinepetrosyan** [comment]
[output.txt](https://github.com/alltheplaces/alltheplaces/files/1570070/output.txt)

**Comment by iandees** [comment]
Looks good. We could probably slim down the number of requests but this'll work for now.

**Comment by kristinepetrosyan** [comment]
@iandees i will try to run something separately to see places that are close by to each other.

**Pull request merged**
