### PR TITLE
Add spider for AutoNation

### PR DESCRIPTION
**Pull request by nbeecher**

### CODE REVIEW

**Comment by iandees** [comment]
@nbeecher, can you merge the upstream 'master' branch into your fork so that it brings in the latest CI changes? The one in your fork seems to be causing a ton of unneeded builds. https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

**Comment by nbeecher** [comment]
@iandees ah yes sorry about that.  My fork is now up to date and the latest CI changes are now there.  Do I need to re-commit autonation?

**Comment by iandees** [comment]
Nope, that's ok. Just want to make it easier in the future.

**Comment by iandees** [comment]
(Thanks!)

**Pull request merged**
