### PR TITLE
added steaknshake spider

### PR DESCRIPTION
**Pull request by DerekMcDaniel**
please check

### CODE REVIEW

**Comment by DerekMcDaniel** [comment]
Sorry, I'm new to this, can someone clue me into why it failed?

**Comment by SelfnessAid** [comment]
You forked repository to your account.
Please work on this repository, not fork.

**Comment by DerekMcDaniel** [comment]
Oh ok. Thanks! It looks like I don't have permissions to create a branch directly.

**Comment by iandees** [comment]
@DerekMcDaniel I invited you to the team with access.

**Pull request closed without merging**
