### PR TITLE
Add spider for Motel 6.

### PR DESCRIPTION
**Pull request by LadyLatitude**
Closes issue #1326.

### CODE REVIEW

**Comment by iandees** [comment]
Looks like this isn't parsing JSON correctly: https://transfer.sh/skZx4/log.txt

**Comment by LadyLatitude** [comment]
I believe the issue is a bad property id returning an error page: 
`2019-12-17 18:29:51 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.motel6.com/content/g6/motel6/motel6-com/en/error.html> (referer: https://www.motel6.com/var/g6/hotel-summary/ms.infinity.1.json)`

Funny, this is a different error than I received the first time I committed this spider, and this particular property id was not returning an error Friday. 

I'm currently working on building in some handling for this. Additionally, I discovered the "brand_id" tag and and adding that into the "extras" property. Hopefully this one is it.

**Comment by iandees** [comment]
In the last few hours we made `brand` a full fledged property you can output. You don't have to use `extras` for it anymore. I moved the brand lookup to use that property.

**Comment by LadyLatitude** [comment]
When I attempted
`'brand': brand_lookup[mdata["brand_id"]],` 
I received a
`TypeError: 'str' object does not support item assignment`
error message. Could it be those changes were not yet active?

**Comment by iandees** [comment]
You probably need to merge the `master` branch into this branch.

**Pull request merged**
