### PR TITLE
rossmann_pl puts country in city for some reason

### LINKED ISSUE #8696: country put into addr:city (rossmann_pl)
`{"type": "Feature", "id": "2iNrouX-pdEKo6pzuRei1HC-mCU=", "properties": {"ref": "https://www.rossmann.pl/drogerie/Drogeria-Rossmann-zwycieska-25-35,wroclaw,2,1437", "@spider": "rossmann_pl", "shop": "chemist", "addr:street_address": "ul. Zwyci\u0119ska 25/35", "addr:city": "Polska", "addr:state": "PL", "addr:postcode": "53-033", "addr:country": "PL", "name": "Wroc\u0142aw ul. Zwyci\u0119ska 25/35", "website": "https://www.rossmann.pl/drogerie/Drogeria-Rossmann-zwycieska-25-35,wroclaw,2,1437", "opening_hours": "Mo-Sa 09:00-21:00", "brand": "Rossmann", "brand:wikidata": "Q316004", "nsi_id": "rossmann-06ae64"}, "geometry": {"type": "Point", "coordinates": [17.004694, 51.060128]}},`

` "addr:city": "Polska"` is wrong (Polska == Poland)

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/rossmann_pl.py  1643 entries have this (`cat rossmann_pl.geojson | grep "city\": \"Polska" | wc -l`)

### PR DESCRIPTION
**Pull request by iandees**
Fixes #8696

### CODE REVIEW

**Comment by iandees** [comment]
It'd be nice to find the actual city in the page data rather than just clearing it out...

**Comment by ireun** [comment]
@iandees use this `item['city'] = re.match(regex, ld_data['description']).group(1)` since description shows full addr ''Biała Podlaska ul. Jana III Sobieskiego 14'` than this regex should return everything until ` ul.` or ` pl.` or ` al.`.

**Comment by matkoniecz** [comment]
opening say https://www.rossmann.pl/drogerie/Drogeria-Rossmann-targowa-1,zuromin,14,728 in browser and looking at source code gives me 
`"address":{"city":"Żuromin","street":"ul. Targowa 1","postCode":"09-300","cityEncodeUrl":"zuromin","location":""},"clickCollectEnabled":true,"openHours":{"mondayOpenFrom":"08:00","mondayOpenTo":"19:30","tuesdayOpenFrom":"08:00","tuesdayOpenTo":"19:30","wednesdayOpenFrom":"08:00","wednesdayOpenTo":"19:30","thursdayOpenFrom":"08:00","thursdayOpenTo":"19:30","fridayOpenFrom":"08:00","fridayOpenTo":"19:30","saturdayOpenFrom":"08:00","saturdayOpenTo":"19:30","sundayOpenFrom":"10:00","sundayOpenTo":"16:00"}`
among others.

note `"address":{"city":"Żuromin"`

not checked is it given to browser as-is or rewritten by JS and therefore harder to access by spider.

**Comment by ireun** [comment]
I also think that the spider should use `https://www.rossmann.pl/shops/api/Shops` instead, there are way more rossmann shops than 56 currently found.

**Comment by ireun** [comment]
I think this PR can be closed without a merge

**Pull request closed without merging**
