### PR TITLE
[Pizza Hut Amrest][La Tagliatella ES][KFC Amrest] Collect branch

### PR DESCRIPTION
**Pull request by vfosnar**
previously:
`name` = `KFC Pardubice Palac`

now:
`name` = `KFC`
`branch` = `KFC Pardubice Palac`

### CODE REVIEW

**Comment by Cj-Malone** [comment]
> now:
> `name` = `KFC`
> `branch` = `KFC Pardubice Palac`

`branch` shouldn't include KFC.

**Comment by vfosnar** [comment]
fixed

**Review by Cj-Malone — CHANGES_REQUESTED** [review]
This is shared code, not just KFC. I'll take a look tomorrow

**Comment by vfosnar** [comment]
No need to hurry, I'm fetching all data locally anyway. thx <3

**Review by Cj-Malone — APPROVED** [review]
Typically, the spider code has all the power. Sometimes that means more work, but it also means more control.

**Comment by Cj-Malone** [comment]
Rel: #5899

**Pull request merged**
