### PR TITLE
Add contact details

### PR DESCRIPTION
**Pull request by Cj-Malone**
Could someone validate the Slack link please.

@brawer @Romeo-PHILLIPS @jancallewaert @abbensid2 the Slack isn't that active, but it'd be nice to see you there.

### CODE REVIEW

**Comment by Cj-Malone** [comment]
@rjw62 too

**Comment by Romeo-PHILLIPS** [comment]
Not letting me join, says that my email isn't linked to an account of "OpenStreetMap". Doesn't give me an option to create one

**Comment by Cj-Malone** [comment]
Does [this](https://slack.openstreetmap.us/) help? I doubt it literally means osm.org account.

**Comment by Romeo-PHILLIPS** [comment]
> Does [this](https://slack.openstreetmap.us/) help? I doubt it literally means osm.org account.

Was able to join this yes

**Pull request merged**
