### PR TITLE
Refactoring: Backport changes to storemapper and other storefinders to add types from autospidergen branch

### PR DESCRIPTION
**Pull request by CloCkWeRX**
https://github.com/alltheplaces/alltheplaces/commit/412633379b6e9865c86dbb6726e3722552154144 is a useful and small standalone part of the autospidergen branch (https://github.com/alltheplaces/alltheplaces/pull/6526).

This is an attempt to backport this, without adding the detection rules behaviours / to reduce the delta between master and the current branch.

Changes:

- Type hints
- Updates the storemapper key to "company_id"

FYI @davidhicks

### CODE REVIEW

**Review by davidhicks — APPROVED** [review]

**Comment by CloCkWeRX** [comment]
@iandees does this PR seem granular enough? I know it's fairly broad, if needed can break it up further to "doc fixes"; "type hints"; and "rename key to company id"

**Comment by CloCkWeRX** [comment]
Todo: Check if there are other recent storemapper commits that also need an update

**Comment by CloCkWeRX** [comment]
Okay, that's ready.

**Comment by CloCkWeRX** [comment]
I might need to tweak some of the docs added recently vs key names

**Review by davidhicks — APPROVED** [review]
OK to merge now? Then we can pull in the rest of the automatic spider generator branch

**Pull request merged**
