### PR TITLE
LA Breweries

### LINKED ISSUE #262: LA Breweries
http://labeerhop.com/breweries/

### PR DESCRIPTION
**Pull request by whoissteven**
Fixes #262

There is no geo data on these pages. How should that be handled?

### CODE REVIEW

**Comment by whoissteven** [comment]
Still need to clean up hours. Just wondering how to handle geo data missing.

**Comment by iandees** [comment]
Pull the address out and we can geocode it later.

**Comment by whoissteven** [comment]
For clarification, is the only needed data: lat, lon, and full address(addr, city, state, and post)?

**Comment by iandees** [comment]
@whoissteven please pull in as much data as you can find on the site. If you can't find a lat/lon we can do without it as long as there's an address we can pull out.

**Comment by whoissteven** [comment]
The error is on this page:
http://labeerhop.com/breweries/1056/

Which is a list of ALL breweries in LA Area. I am already pulling all the breweries from the sitemap XML, I'll need to disallow this URL. Will look into this. Otherwise data pulled looks good. Open to critique otherwise.

**Pull request merged**
