### PR TITLE
Attempt to glue together "Find missing NSI stores" and "Detect spiders" (WIP / not ready)

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Related: https://github.com/alltheplaces/alltheplaces/pull/6916

@davidhicks - would you be able to maybe take a look here?
I grabbed your autogen spider branch (https://github.com/alltheplaces/alltheplaces/pull/6526) but ran into problems.

- I found it difficult to start a group of related crawlers for a website, ie it has 3x urls to look at; so I wanted to crawl all of those potentially in threads; finish; move onto the next one. Ran into plenty of issues with "can't restart reactors" and global state that I didn't expect.
- For some reason, I'd get the first generated spider all of the time; rather than the current one. If I had to guess; I'd say somehow the responses are *all* http responses and first_response accidentally is the wrong thing. But the code *shouldn't* do that

After giving up on that I ran into problems with using a submodule to basically run the sf command again in bash; which I don't 100% understand - there's going to be some obvious way to tell pipenv where it is running or similar I'm just not seeing.

Still a little bit manual, but closer!

Example output:

https://github.com/alltheplaces/alltheplaces/discussions/7101

### CODE REVIEW

**Comment by davidhicks** [comment]
> I found it difficult to start a group of related crawlers for a website, ie it has 3x urls to look at; so I wanted to crawl all of those potentially in threads; finish; move onto the next one. Ran into plenty of issues with "can't restart reactors" and global state that I didn't expect.

Have a look at `SfCommand` in `sf.py`, specifically the `run` method. Currently only one URL is crawled, but it would be possible to change this so that more than one URL is added to the list to crawl. Is this the method you used to crawl multiple URLs?

**Comment by CloCkWeRX** [comment]
> Is this the method you used to crawl multiple URLs?
Effectively, yes.

Roughly in https://github.com/alltheplaces/alltheplaces/pull/7100/commits/949b90e3177a69993ae47d57974f867d6b6a1c85#diff-5192c6150e6f4dc72751035fc1624d67fa1dc7a32ad539d6213a43b0a10361adR141

I tried:
```
        # for store in stores
        process = CrawlerProcess(settings)
....

        # for url in urls, make a crawler
            crawler = process.create_crawler(StorefinderDetectorSpider)
            crawler.signals.connect(self.print_spider_code, signal=signals.item_scraped)
            process.crawl(
                crawler,
                url=url,
                brand_wikidata=opts.brand_wikidata,
                operator_wikidata=opts.operator_wikidata,
                spider_key=opts.spider_key,
                spider_class_name=opts.spider_class_name,
            )
        
        # Then once each assembled, hit the start button
        process.start()
```

I turned one of the detector methods to always be true, for ease of testing

Calls to print_spider_code receive:
 - Initially pass url[0] and a `Store0Spider` class that was generated on the first major loop
 - Then url[1] and a `Store0Spider`  
 
 I might just fork + make something reproducable/executable to more clearly show it.

**Comment by CloCkWeRX** [comment]
Part 1: https://github.com/alltheplaces/alltheplaces/commit/0131960e448fd7773a8452d674c3e45ae6140938 - running into trouble starting multiple crawls.
Part 2: Of course, I can't reproduce it properly now :/

**Comment by CloCkWeRX** [comment]
Far out: e0b341ed was the cause of my woes, as the auto correction removed all of the loading - so the reflection would not find anything.

Any suggestions on opting out specifically from that automatic refactoring/stating it is intended?

**Comment by CloCkWeRX** [comment]
Okay, far from ideal, but at least this branch won't get automatically refactored to death all of the time.

@iandees / @Cj-Malone / @davidhicks - thoughts on the better way to do this? 
2180a32 didn't appear to work, --exclude according to the manual lets you pass in a glob; but apparently it had no effect.

**Comment by CloCkWeRX** [comment]
Okay. @davidhicks to show what I mean:

Grab this branch: https://github.com/CloCkWeRX/alltheplaces/tree/odd-behaviour
Note; I've made it return true for a lot of storefinders.
Check nothing has been broken by the auto refactoring bot
Then run:
```
ubuntu@codespaces-7f0edb:/workspaces/alltheplaces$ pipenv run scrapy nsi --detect-missing brands/shop/baby_goods
Fetched 22 brands/shop/baby_goods from NSI
Missing by wikidata: 20
### Brand name

Aubert

French baby goods retail chain

### Wikidata ID

Q62964657
https://www.wikidata.org/wiki/Q62964657
https://www.wikidata.org/wiki/Special:EntityData/Q62964657.json

### Store finder url(s)

{'https://www.aubert.com/'}
Crawling!
<scrapy.crawler.CrawlerProcess object at 0x7f7d3b3f55d0>
Parsing response
[<class 'locations.storefinders.agile_store_locator.AgileStoreLocatorSpider'>, <class 'locations.storefinders.closeby.ClosebySpider'>, <class 'locations.storefinders.freshop.FreshopSpider'>, <class 'locations.storefinders.kibo.KiboSpider'>, <class 'locations.storefinders.limesharp_store_locator.LimesharpStoreLocatorSpider'>, <class 'locations.storefinders.localisr.LocalisrSpider'>, <class 'locations.storefinders.metalocator.MetaLocatorSpider'>, <class 'locations.storefinders.metizsoft.MetizsoftSpider'>, <class 'locations.storefinders.momentfeed.MomentFeedSpider'>, <class 'locations.storefinders.storepoint.StorepointSpider'>, <class 'locations.storefinders.wp_store_locator.WPStoreLocatorSpider'>]
[<class 'locations.storefinders.agile_store_locator.AgileStoreLocatorSpider'>, <class 'locations.storefinders.storepoint.StorepointSpider'>]
We found a store finder (2)
<200 https://www.aubert.com/>
<200 https://www.aubert.com/>
Building a new spider
URL: https://www.aubert.com/ gives us <class 'locations.spiders.AubertFRSpider'>   *So far, so good*
Spider detected, woo  
from locations.storefinders.agile_store_locator import AgileStoreLocatorSpider


class AubertFRSpider(AgileStoreLocatorSpider):
        name = "aubert_fr"
        item_attributes = {
                "brand_wikidata": "Q62964657",
                "brand": "Aubert",
        }
        allowed_domains = [
                "www.aubert.com",
        ]
We found a store finder (2)
<200 https://www.aubert.com/>
<200 https://www.aubert.com/>
Building a new spider
URL: https://www.aubert.com/ gives us <class 'locations.spiders.AubertFRSpider'>
Spider detected, woo
from locations.storefinders.storepoint import StorepointSpider


class AubertFRSpider(StorepointSpider):
        name = "aubert_fr"
        item_attributes = {
                "brand_wikidata": "Q62964657",
                "brand": "Aubert",
        }

----
### Brand name

Autour de Bébé

### Wikidata ID

Q117842411
https://www.wikidata.org/wiki/Q117842411
https://www.wikidata.org/wiki/Special:EntityData/Q117842411.json

### Store finder url(s)

{'https://magasins.autourdebebe.com/', 'https://www.autourdebebe.com/'}
Crawling!
<scrapy.crawler.CrawlerProcess object at 0x7f7d3e1b9e90>
Parsing response
[<class 'locations.storefinders.agile_store_locator.AgileStoreLocatorSpider'>, <class 'locations.storefinders.closeby.ClosebySpider'>, <class 'locations.storefinders.freshop.FreshopSpider'>, <class 'locations.storefinders.kibo.KiboSpider'>, <class 'locations.storefinders.limesharp_store_locator.LimesharpStoreLocatorSpider'>, <class 'locations.storefinders.localisr.LocalisrSpider'>, <class 'locations.storefinders.metalocator.MetaLocatorSpider'>, <class 'locations.storefinders.metizsoft.MetizsoftSpider'>, <class 'locations.storefinders.momentfeed.MomentFeedSpider'>, <class 'locations.storefinders.storepoint.StorepointSpider'>, <class 'locations.storefinders.wp_store_locator.WPStoreLocatorSpider'>]
[<class 'locations.storefinders.agile_store_locator.AgileStoreLocatorSpider'>, <class 'locations.storefinders.storepoint.StorepointSpider'>]
We found a store finder (2)
<200 https://www.aubert.com/>
<200 https://www.aubert.com/>
Building a new spider
URL: https://www.aubert.com/ gives us <class 'locations.spiders.AubertFRSpider'>
We found a store finder (2)
<200 https://www.aubert.com/>
<200 https://www.aubert.com/>
Building a new spider
URL: https://www.aubert.com/ gives us <class 'locations.spiders.AubertFRSpider'>
Parsing response
[<class 'locations.storefinders.agile_store_locator.AgileStoreLocatorSpider'>, <class 'locations.storefinders.closeby.ClosebySpider'>, <class 'locations.storefinders.freshop.FreshopSpider'>, <class 'locations.storefinders.kibo.KiboSpider'>, <class 'locations.storefinders.limesharp_store_locator.LimesharpStoreLocatorSpider'>, <class 'locations.storefinders.localisr.LocalisrSpider'>, <class 'locations.storefinders.metalocator.MetaLocatorSpider'>, <class 'locations.storefinders.metizsoft.MetizsoftSpider'>, <class 'locations.storefinders.momentfeed.MomentFeedSpider'>, <class 'locations.storefinders.storepoint.StorepointSpider'>, <class 'locations.storefinders.wp_store_locator.WPStoreLocatorSpider'>]
[<class 'locations.storefinders.agile_store_locator.AgileStoreLocatorSpider'>, <class 'locations.storefinders.storepoint.StorepointSpider'>]
We found a store finder (2)
<200 https://magasins.autourdebebe.com/fr>
<200 https://magasins.autourdebebe.com/fr>
Building a new spider
URL: https://magasins.autourdebebe.com/fr gives us <class 'locations.spiders.AubertFRSpider'>      *Incorrect spider generated! Completely unclear why*
Spider detected, woo
from locations.storefinders.agile_store_locator import AgileStoreLocatorSpider


class AubertFRSpider(AgileStoreLocatorSpider):
        name = "aubert_fr"
        item_attributes = {
                "brand_wikidata": "Q62964657",
                "brand": "Aubert",
        }
        allowed_domains = [
                "magasins.autourdebebe.com",
        ]
We found a store finder (2)
<200 https://magasins.autourdebebe.com/fr>
<200 https://magasins.autourdebebe.com/fr>
Building a new spider
URL: https://magasins.autourdebebe.com/fr gives us <class 'locations.spiders.AubertFRSpider'>
Spider detected, woo
from locations.storefinders.storepoint import StorepointSpider
```

**Comment by davidhicks** [comment]
> ```
>         # for store in stores
>         process = CrawlerProcess(settings)
> ....
> 
>         # for url in urls, make a crawler
>             crawler = process.create_crawler(StorefinderDetectorSpider)
>             crawler.signals.connect(self.print_spider_code, signal=signals.item_scraped)
>             process.crawl(
>                 crawler,
>                 url=url,
>                 brand_wikidata=opts.brand_wikidata,
>                 operator_wikidata=opts.operator_wikidata,
>                 spider_key=opts.spider_key,
>                 spider_class_name=opts.spider_class_name,
>             )
>         
>         # Then once each assembled, hit the start button
>         process.start()
> ```

Did you also try multiple `process.crawl` calls within the same `CrawlerProcess` as defined at https://docs.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process  I haven't read/tested if you can call the same spider twice within the same `CrawlerProcess`. Or changing `StorefinderDetectorSpider` to accept multiple `start_url`'s would possibly work too?

When I get time I'll have a proper look over this code and see if we can glue things together better :)

**Comment by CloCkWeRX** [comment]
Usability:
With the wordpress detected spiders, this is kind of great. But I've given myself/the project ~40+ spiders to implement.

Literally the slowest/most tedious bits are now:
```
git checkout upstream/master
git checkout -b add_(name)
touch locations/spiders/(name).py
git add locations/spiders/(name).py
echo 'spider code gets cut and paste' > locations/spiders/(name).py
black locations/spiders/(name).py
pipenv run scrapy crawl (name).py
```
And really then - 30-60 seconds later, it's when the practical work happens (tweak timeformat, check hours, find ticket)

Should really go back to the templates and look at generating these command OR making a new spider template generator command line tool that does 90% of this for you, a bit like rails does.

**Comment by davidhicks** [comment]
Just to check--is the difference from the `autospidergen` branch just the changes to `nsi.py` and `WIKIDATA.md`?

**Comment by CloCkWeRX** [comment]
It's https://github.com/alltheplaces/alltheplaces/pull/6526 + https://github.com/alltheplaces/alltheplaces/pull/6916

But there's also a lot of the individual autodetection branches at varying levels (ie this has where2getit merged in, while we decided not to on your upstream branch.

https://github.com/alltheplaces/alltheplaces/discussions is the output/results where the detections have failed / manual checking needed

**Comment by davidhicks** [comment]
Thanks you. I'm overdue to update the `autospidergen` branch and implement some missing bits and pieces such as use of Playwright for intercepting API requests, or use of Playwright to read out JavaScript objects from `Window`. I want to try and avoid breaking your additional work to automatically generate issue templates for missing spiders :)

**Comment by CloCkWeRX** [comment]
Ah, go nuts; I'll figure it out if there's conflicts.

I will warn you though current master has the CI bots doing this kind of business:
https://github.com/alltheplaces/alltheplaces/pull/7100/commits/230fcde3bdd4203d136e0a6bf172293acbf59639

... and I can't seem to find the off switch. That's more likely to break your branch/this branch than anything else.

**Comment by CloCkWeRX** [comment]
Closing for the moment; as some parts of this were merged upstream.

**Pull request closed without merging**
