### PR TITLE
feat: add media markt be

### PR DESCRIPTION
**Pull request by mickaelabdealy**

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Hey, thank you and this is looking good.

Have you seen out StructuredDataSpider, it should be able to the bulk of the in this case, you'd just deal with some of the unexpected stuff, name + opening hours in this case. [Docs](https://github.com/alltheplaces/alltheplaces/blob/master/docs/STRUCTURED_DATA.md)

`$ pipenv run scrapy sd https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Anvers,58852,-29.html`
```python
{'city': 'Anvers',
 'email': 'mm.antwerpen.info@mediamarkt.be',
 'extras': {},
 'facebook': '//www.facebook.com/MediaMarktBE',
 'lat': 51.21741,
 'lon': 4.41919,
 'name': None,
 'opening_hours': 'Sa 10:00-19:00',
 'phone': '+32 3 224 10 40',
 'postcode': '2018',
 'ref': 'https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Anvers,58852,-29.html',
 'state': None,
 'street_address': 'De Keyserlei 7',
 'website': 'https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Anvers,58852,-29.html'}
```

**Comment by mickaelabdealy** [comment]
> 

I just found that this link that seems nice : [mediamarkt sitemap](https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)

Is it something like [here](https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/webuyanycar_gb.py)

**Comment by mickaelabdealy** [comment]
> `rules` is from a `CrawlSpider`, `sitemap_rules` is the similar concept in `SitemapSpider`. In this case you code is working because by default everything in the sitemap is parsed, and that's fine here as every url in the sitemap is location, we often need to filter out "list" pages or product pages. So just remove `rules`.
> 
> For the opening hours, this works, and it's fine for now. But going forward you probably want to checkout `ld_data`, it's the Microdata after parsing so it's usually easier to work with. Also you could probably get away with just translating the days in `pre_process_data` and then letting the system parse them, but I've not tested that.

Ok for the `rules`.

I have a problem with the run of this crawler. They are several subsites the spider is not able to crawl but I don't know why. Do you have an idea ? 

Here are the scrapy stats :

`{'atp/brand/MediaMarkt': 32,
 'atp/brand_wikidata/Q2381223': 32,
 'atp/category/shop/electronics': 32,
 'atp/field/country/from_spider_name': 32,
 'atp/field/image/missing': 32,
 'atp/field/state/missing': 32,
 'atp/field/twitter/missing': 32,
 'atp/nsi/perfect_match': 32,
 'downloader/request_bytes': 78536,
 'downloader/request_count': 46,
 'downloader/request_method_count/GET': 46,
 'downloader/response_bytes': 8104414,
 'downloader/response_count': 46,
 'downloader/response_status_count/200': 46,
 'elapsed_time_seconds': 56.322374,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 3, 29, 12, 8, 0, 381559),
 'httpcompression/response_bytes': 8391725,
 'httpcompression/response_count': 34,
 'item_scraped_count': 32,
 'log_count/DEBUG': 83,
 'log_count/INFO': 9,
 'memusage/max': 121159680,
 'memusage/startup': 121159680,
 'request_depth_max': 1,
 'response_received_count': 46,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 45,
 'scheduler/dequeued/memory': 45,
 'scheduler/enqueued': 45,
 'scheduler/enqueued/memory': 45,
 'start_time': datetime.datetime(2023, 3, 29, 12, 7, 4, 59185)}`

**Comment by Cj-Malone** [comment]
hmm, so they are giving us all the pages, ` 'response_received_count': 46,` 44 stores + robots.txt + sitemap.xml. No errors in our code, no bad response codes. But I'd guess they are blocking us after so long but not giving us a 403, maybe try `download_delay = 5` and see if that works, or faking a browser user agent. Did you get all of them before switching to a sitemap spider?

**Comment by mickaelabdealy** [comment]
> hmm, so they are giving us all the pages, ` 'response_received_count': 46,` 44 stores + robots.txt + sitemap.xml. No errors in our code, no bad response codes. But I'd guess they are blocking us after so long but not giving us a 403, maybe try `download_delay = 5` and see if that works, or faking a browser user agent. Did you get all of them before switching to a sitemap spider?

I tried with `download_delay` without success. Here is the log for website not working when i'm trying a `scrapy crawl`.

> 2023-03-29 16:35:25 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Schoten,58362,-29.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:35:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Oostakker,58358,-29.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:35:40 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Li%C3%A8ge-Saint-Lambert,58357,-29.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:35:46 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Jemappes,58356,-17.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:35:50 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Herstal,58355,-17.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:35:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Gosselies,58354,-29.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:36:00 [scrapy.extensions.logstats] INFO: Crawled 40 pages (at 10 pages/min), scraped 32 items (at 4 items/min)
2023-03-29 16:36:04 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Brussel-Basilix,58353,-17.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:36:10 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Bruxelles-Basilix,58353,-29.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:36:17 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Brussel-Docks,175052,-17.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:36:24 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Courtrai,141454,-29.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:36:31 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Zwijnaarde,112952,-17.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml)
2023-03-29 16:36:37 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mediamarkt.be/mcs/marketinfo/_MediaMarkt-Zwijnaarde,112952,-29.html> (referer: https://www.mediamarkt.be/sitemap/sitemap-marketinfo.xml

I'm going to try with faking a browser user agent.

**Comment by mickaelabdealy** [comment]
No success with using a fake user agent...

**Comment by Cj-Malone** [comment]
I've turned back into a into [StructuredDataSpider](https://github.com/alltheplaces/alltheplaces/pull/5066/commits/d67c33769a80cf85361efcc578d2defd75ce838d). A [CrawlSpider](https://github.com/alltheplaces/alltheplaces/pull/5066/commits/f36cc1c6b3a4e25135901a7abd0f212fd6b99a0d). And parsing the [ld_data opening hours](https://github.com/alltheplaces/alltheplaces/pull/5066/commits/5f58508f0e2212360aa40febf2743c56046e387f). All in small commits so hopefully you can see what I did.

**Review by Cj-Malone — APPROVED** [review]
Thank you.

```python
{'atp/brand/MediaMarkt': 22,
 'atp/brand_wikidata/Q2381223': 22,
 'atp/category/shop/electronics': 22,
 'atp/field/country/from_spider_name': 22,
 'atp/field/image/missing': 22,
 'atp/field/state/missing': 22,
 'atp/field/twitter/missing': 22,
 'atp/nsi/perfect_match': 22,
 'downloader/request_bytes': 61677,
 'downloader/request_count': 24,
 'downloader/request_method_count/GET': 24,
 'downloader/response_bytes': 5830388,
 'downloader/response_count': 24,
 'downloader/response_status_count/200': 24,
 'elapsed_time_seconds': 0.968625,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 3, 30, 14, 37, 5, 573584),
 'httpcache/hit': 24,
 'httpcompression/response_bytes': 6072059,
 'httpcompression/response_count': 24,
 'item_scraped_count': 22,
 'log_count/DEBUG': 58,
 'log_count/INFO': 8,
 'memusage/max': 126930944,
 'memusage/startup': 126930944,
 'request_depth_max': 1,
 'response_received_count': 24,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 23,
 'scheduler/dequeued/memory': 23,
 'scheduler/enqueued': 23,
 'scheduler/enqueued/memory': 23,
 'start_time': datetime.datetime(2023, 3, 30, 14, 37, 4, 604959)}
```

**Pull request merged**
