### PR TITLE
[Dino PL] Improve name

### PR DESCRIPTION
**Pull request by matkoniecz**
and I have not confirmed is it fitting `branch` - and these are unusual in Poland

see also #8739

(I expect that many like this will be needed before I will be able to trust ATP data)

### CODE REVIEW

**Comment by matkoniecz** [comment]
note that it is almost certainly not actually a `branch` code, at least not in https://taginfo.openstreetmap.org/keys/branch#overview meaning

**Comment by Cj-Malone** [comment]
https://github.com/alltheplaces/alltheplaces/pull/7883#issuecomment-2000272067

**Comment by matkoniecz** [comment]
So should `branch` be used for any identifier in web listing, no matter whether it is actually used within shops?

**Comment by matkoniecz** [comment]
(the same should be done with https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/empik_pl.py - I will try doing it after this PR is merged, personally I would prefer to emit `branch` where this distinction is seriously used, but moving such web listing code to `branch` field from `name` field already significantly helps)

**Review by Cj-Malone — APPROVED** [review]

**Comment by matkoniecz** [comment]
BTW, with name being popped I am a bit confused from where name comes now. NSI?

**Comment by iandees** [comment]
The name comes from NSI, yes. The [`ApplyNSICategoriesPipeline`](https://github.com/alltheplaces/alltheplaces/blob/master/locations/pipelines/apply_nsi_categories.py) code uses the wikidata ID to find an entry in Name Suggestion Index and then applies the tags from NSI to the outputted item.

**Pull request merged**
