### PR TITLE
[medstar] Added Categories for features (500 items)

### PR DESCRIPTION
**Pull request by ckpiper**
I started to add some categories for based on the name of the POIs. As there is only 500 from this spider I began looking at the names and using them to decide on the category. Now something that I noticed is that many of the scraped POIs are actually just different services of the same hospital. 

For example [MedStar Harbor Hospital](https://www.medstarhealth.org/locations/medstar-harbor-hospital) has 13 services. And it got scraped 14 times in the code. (13 services + 1 hospital). 

My question is, should each service be its own POI? The example for Harbor Hospital puts the same Latitude and Longitude for different services. The names are like
MedStar Health: Pharmacy at MedStar Harbor Hospital
MedStar Health: Pediatrics at MedStar Harbor Hospital
etc.

<details><summary>New Stats with changes below</summary>

```python
{'atp/brand/Medstar Health': 500,
 'atp/brand_wikidata/Q6804943': 500,
 'atp/category/amenity/clinic': 46,
 'atp/category/amenity/hospital': 130,
 'atp/category/amenity/pharmacy': 2,
 'atp/category/healthcare/centre': 58,
 'atp/category/missing': 264,
 'atp/category/multiple': 178,
 'atp/field/city/missing': 500,
 'atp/field/email/missing': 500,
 'atp/field/image/missing': 500,
 'atp/field/opening_hours/missing': 500,
 'atp/field/phone/missing': 36,
 'atp/field/postcode/missing': 500,
 'atp/field/state/from_reverse_geocoding': 500,
 'atp/field/street_address/missing': 500,
 'atp/field/twitter/missing': 500,
 'atp/field/website/missing': 500,
 'atp/nsi/brand_missing': 500,
 'downloader/request_bytes': 333796,
 'downloader/request_count': 502,
 'downloader/request_method_count/GET': 502,
 'downloader/response_bytes': 9293035,
 'downloader/response_count': 502,
 'downloader/response_status_count/200': 502,
 'elapsed_time_seconds': 625.719717,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 11, 28, 20, 38, 25, 843556, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 31450332,
 'httpcompression/response_count': 502,
 'item_scraped_count': 500,
 'log_count/INFO': 19,
 'memusage/max': 413863936,
 'memusage/startup': 136658944,
 'request_depth_max': 1,
 'response_received_count': 502,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 501,
 'scheduler/dequeued/memory': 501,
 'scheduler/enqueued': 501,
 'scheduler/enqueued/memory': 501,
 'start_time': datetime.datetime(2023, 11, 28, 20, 28, 0, 123839, tzinfo=datetime.timezone.utc)}
```
</details>
If we decide to continue with multiple POIs per hospital (one for each specialty) then healthcare:specialty tags should be applied.

### CODE REVIEW

**Comment by iandees** [comment]
I think my opinion is that we should have one point for the hospital and not allow the specialties to exist as different points.

There's probably a case to be made for modeling all the different offices and departments/specialties in the hospital and where they are relative to one another on the hospital campus, but it doesn't sound like we can get that data out of the page.

**Comment by ckpiper** [comment]
I agree with having one point for the hospital then several healthcare:specialty tags for the services the have. Although I am not sure how to achieve that without collecting all items. Not really a memory issue as there are only 500. But that would require getting the response of a request in the same function. Is that possible in scrapy? If so would the only way to do this is collect, sort by location, then add specialty tag to main hospital point.

**Comment by iandees** [comment]
I haven't had to do that before with Scrapy. A quick scan through documentation doesn't seem that it's obviously supported, but I'm sure there's a way to pull it off.

**Comment by iandees** [comment]
Closing as stale. Please feel free to reopen if we want to tackle what was suggested here.

**Pull request closed without merging**
