### PR TITLE
Clean up name and branch

### PR DESCRIPTION
**Pull request by Cj-Malone**
I've mentioned this before. But I'd like to get closer to the OSM `name` and `branch`. Instead of our current thing.

This takes the NSI names and `strip_names` supplied by a spider and removes them from a `name` and sets the remainder to `branch`.

I still want to run through a weekly and get a reasonable set of `strip_names` before this is merged. I'm opening this now because I've been ignoring it for too long.

### CODE REVIEW

**Comment by iandees** [comment]
Yea, this makes sense 👍🏻

**Comment by Cj-Malone** [comment]
Rel: #4772

**Comment by Cj-Malone** [comment]
So, I don't think doing this automatically from all the tags (`name`, `brand`, `operator`) is viable. It will work most of the time, but we'll end up with edge cases. My latest idea is just `name` from NSI, or `strip_names` is spider.

**Comment by iandees** [comment]
I'm going to close this as stale. Please feel free to reopen if we want to continue this line of inquiry.

**Pull request closed without merging**
