### PR TITLE
Add Harvey Norman (AU/NZ) (239 stores)

### PR DESCRIPTION
**Pull request by davidhicks**

### CODE REVIEW

**Comment by davidhicks** [comment]
Hmmm geo blocked it would appear--HTTP 406 error being returned by the CI check.

**Comment by davidhicks** [comment]
requires_proxy = True added. Thanks for confirming it it a geoblock

**Comment by Cj-Malone** [comment]
Wouldn't we want it to be `requires_proxy = "AU"`?
True would be we'll get the country from the spider name, but in this case it isn't in the name, so it'd fall back to US.

**Comment by Cj-Malone** [comment]
We may as well document it while we think about it, otherwise when the proxies are finally set up we'd still have to go through every spider to check it.

**Pull request merged**
