### PR TITLE
Create telenor_dk.py

### LINKED ISSUE #4655: Telenor Denmark
### Brand name

Telenor

### Wikidata ID

Q1796954

### Store finder url(s)

Most useful data is in HTML strings..

https://www.telenor.dk/da/custom/FindNearestShopBlock/GetShops/2bd5f376-3f79-475b-aa1e-b45174b9a2f3/?blockId=1590

### PR DESCRIPTION
**Pull request by Dimitar5555**
Closes #4655

### CODE REVIEW

**Comment by Cj-Malone** [comment]
OK, I didn't realise you hadn't got a local environment to work in and test in. The [README](https://github.com/alltheplaces/alltheplaces#getting-started) has recently been updated, I recommend you try and get scrapy working locally.

I propose: I take over this PR, and if you get everything working locally, you work on #4654. For that one you want to do a `FormRequest` like `mcdonalds_hk`, then in `parse` you want to loop `response.json()["data"]["stores"]`

**Comment by Dimitar5555** [comment]
@Cj-Malone Feel free to take this one over.

**Comment by Cj-Malone** [comment]
This ended up being more complex that I expected, especially the opening hours. Oh well, it's written now. Thank you @Dimitar5555

```python
{'atp/category/shop/mobile_phone': 78,
 'atp/field/country/from_spider_name': 78,
 'atp/field/email/missing': 38,
 'atp/field/image/missing': 78,
 'atp/field/state/missing': 78,
 'atp/field/twitter/missing': 78,
 'atp/field/website/missing': 40,
 'atp/nsi/cc_match': 78,
 'downloader/request_bytes': 384,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 114880,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 1.608906,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 1, 17, 20, 29, 21, 424264),
 'httpcache/hit': 1,
 'item_scraped_count': 78,
 'log_count/DEBUG': 89,
 'log_count/INFO': 8,
 'memusage/max': 118882304,
 'memusage/startup': 118882304,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2023, 1, 17, 20, 29, 19, 815358)}
```

**Comment by iandees** [comment]
That's a tougher one. Thanks for getting it started @Dimitar5555!

**Pull request merged**
