### PR TITLE
Hemköp SE (Supermarket chain Sweden) adding spider (199 items)

### PR DESCRIPTION
**Pull request by matthiasfeist**
Adding spider for Hemköp (a Swedish supermarket chain).

```bash
{'atp/brand/Hemköp': 199,
 'atp/brand_wikidata/Q10521746': 199,
 'atp/category/shop/supermarket': 199,
 'atp/field/country/from_spider_name': 199,
 'atp/field/email/missing': 199,
 'atp/field/image/missing': 199,
 'atp/field/name/missing': 199,
 'atp/field/opening_hours/missing': 1,
 'atp/field/operator/missing': 199,
 'atp/field/operator_wikidata/missing': 199,
 'atp/field/state/missing': 199,
 'atp/field/twitter/missing': 199,
 'atp/nsi/perfect_match': 199,
 'downloader/request_bytes': 648,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 18691,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 3.213838,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 12, 31, 12, 9, 37, 848140, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 143484,
 'httpcompression/response_count': 2,
 'item_scraped_count': 199,
 'log_count/DEBUG': 213,
 'log_count/INFO': 9,
 'memusage/max': 130584576,
 'memusage/startup': 130584576,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2023, 12, 31, 12, 9, 34, 634302, tzinfo=datetime.timezone.utc)}
```

### CODE REVIEW

**Review by Cj-Malone — APPROVED** [review]
https://alltheplaces-data.openaddresses.io/map.html?show=https://alltheplaces-data.openaddresses.io/ci/7370341216/hemkop_se/output.geojson

LGTM thank you. 199 is a little suspicious though, it may be an api limit.

**Comment by iandees** [comment]
The pagination info in the API response says max results is 400, so this is likely the correct number.

**Comment by matthiasfeist** [comment]
thanks for merging :) 

@Cj-Malone I agree 199 seems odd but that's exactly the amount of stores they have in Sweden according to their website

**Comment by Cj-Malone** [comment]
Thanks, I'm on my phone so didn't look at the response.

Thank you and welcome @matthiasfeist :)

**Pull request merged**
