### PR TITLE
Old Chicago

### LINKED ISSUE #70: Old Chicago
https://oldchicago.com/our-locations

### PR DESCRIPTION
**Pull request by swingley**
Fixes #70

### CODE REVIEW

**Comment by swingley** [comment]
Anyone have any ideas why Travis is failing on this? All I see in there is [couldn't save logfile to s3](https://travis-ci.org/alltheplaces/alltheplaces/builds/329555340#L520). Maybe @iandees or @DerekMcDaniel ?

**Comment by iandees** [comment]
Hi @swingley, the CI isn't running because Travis doesn't share secrets (like the AWS credentials used to upload to S3) with forked repository builds. I haven't been able to find a good workaround for this yet. I'll try running your spider locally and check its output.

**Comment by swingley** [comment]
Thanks for the reply and the merge. Am I able to contribute directly to this repo? Seems like a fun project.

**Comment by iandees** [comment]
@swingley I added you. Make sure you update your origin remote so that you push branches to this repo and not your fork.

**Pull request merged**
