### PR TITLE
feat: Jardiland

### PR DESCRIPTION
**Pull request by Romeo-PHILLIPS**

### CODE REVIEW

**Comment by Cj-Malone** [comment]
It looks like the website could be captured with `item["website"] = f'https://www.jardiland.com/storelocator/store/view/name/{feature["properties"]["contact"]["website"]}/'`

**Comment by Cj-Malone** [comment]
I assume this was closed by mistake?

**Comment by Romeo-PHILLIPS** [comment]
> I assume this was closed by mistake?

No sorry I actually already implemented this spider yesterday (https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/jardiland.py). I am tired haha

**Comment by Romeo-PHILLIPS** [comment]
> I assume this was closed by mistake?

Yes sorry a bit tired

**Comment by Cj-Malone** [comment]
No worries, this looks good to me. Thank you.

**Review by Cj-Malone — APPROVED** [review]

**Pull request merged**
