### PR TITLE
hannaford

### LINKED ISSUE #30: Hannaford
https://www.hannaford.com/custserv/locate_store.cmd

### PR DESCRIPTION
**Pull request by DerekMcDaniel**
Fixes #30

### CODE REVIEW

**Comment by DerekMcDaniel** [comment]
I was only able to reproduce the original scraperbot error once. The website was redirecting to an error page but that seems to have stopped. I did find and fix another error while I was debugging that one however.

**Comment by DerekMcDaniel** [comment]
Please check the extra hours for pharmacy and summer hours. I was following the example of: 08:00-16:00 open, 16:00-03:00 open "public room" from the osm opening_hours guide. 

   Also, the stores have a pretty long list of holiday hours, and pharmacy holiday hours. Any idea on how to handle that?

**Comment by iandees** [comment]
Let's stick with just the normal store hours. I'm not interested in the holiday or pharmacy hours at this point.

**Comment by DerekMcDaniel** [comment]
Hold off on this pull please, I found that I was able to pull lat and lon from a script tag. Will update

**Pull request merged**
