### PR TITLE
OK Furniture (287 locations), House & Home (43 locations), Studio 88 (397 locations) (Southern Africa)

### PR DESCRIPTION
**Pull request by arrival-spring**
All three are under Shoprite holdings and have almost identical store pages.

```
 'atp/brand/OK Furniture': 287,
 'atp/brand_wikidata/Q116474866': 287,
 'atp/category/shop/furniture': 287,
 'atp/field/city/missing': 287,
 'atp/field/country/from_website_url': 287,
 'atp/field/email/missing': 287,
 'atp/field/image/missing': 287,
 'atp/field/opening_hours/missing': 287,
 'atp/field/operator/missing': 287,
 'atp/field/operator_wikidata/missing': 287,
 'atp/field/phone/invalid': 25,
 'atp/field/phone/missing': 7,
 'atp/field/postcode/missing': 287,
 'atp/field/state/missing': 287,
 'atp/field/street_address/missing': 287,
 'atp/field/twitter/missing': 287,
 'atp/item_scraped_host_count/www.okfurniture.co.za': 287,
 'atp/nsi/perfect_match': 287,
```

```
 'atp/brand/House & Home': 43,
 'atp/brand_wikidata/Q116520162': 43,
 'atp/category/shop/furniture': 43,
 'atp/field/city/missing': 43,
 'atp/field/country/from_website_url': 43,
 'atp/field/email/missing': 43,
 'atp/field/image/missing': 43,
 'atp/field/opening_hours/missing': 43,
 'atp/field/operator/missing': 43,
 'atp/field/operator_wikidata/missing': 43,
 'atp/field/phone/invalid': 1,
 'atp/field/phone/missing': 1,
 'atp/field/postcode/missing': 43,
 'atp/field/state/missing': 43,
 'atp/field/street_address/missing': 43,
 'atp/field/twitter/missing': 43,
 'atp/item_scraped_host_count/www.houseandhome.co.za': 43,
 'atp/nsi/perfect_match': 43,
```

```
 'atp/brand/Studio 88': 397,
 'atp/brand_wikidata/Q116498145': 397,
 'atp/category/shop/clothes': 397,
 'atp/cdn/cloudflare/response_count': 2,
 'atp/cdn/cloudflare/response_status_count/200': 2,
 'atp/field/city/missing': 397,
 'atp/field/country/from_website_url': 397,
 'atp/field/email/missing': 397,
 'atp/field/image/missing': 397,
 'atp/field/opening_hours/missing': 397,
 'atp/field/operator/missing': 397,
 'atp/field/operator_wikidata/missing': 397,
 'atp/field/phone/invalid': 41,
 'atp/field/phone/missing': 4,
 'atp/field/postcode/missing': 397,
 'atp/field/state/missing': 397,
 'atp/field/street_address/missing': 397,
 'atp/field/twitter/missing': 397,
 'atp/item_scraped_host_count/www.studio-88.co.za': 397,
 'atp/nsi/perfect_match': 397,
```

### CODE REVIEW

**Comment by arrival-spring** [comment]
Todo:
* Fix country for non ZA locations 
* Investigate 403 from Studio 88

**Comment by arrival-spring** [comment]
> Investigate 403 from Studio 88

I guess this is related to Cloudfare (`atp/cdn/cloudflare/response_count`) but I have only had it fail once locally, it has worked fine the rest of the times.

**Comment by iandees** [comment]
If it makes a low number of requests you could try `requires_proxy = True` on that spider.

**Comment by arrival-spring** [comment]
> If it makes a low number of requests

Only one page fetch, so yes

> "title":"Bad Request","status":400,"detail":"Format of field geolocation is invalid"

Is this because we're not telling it where to proxy from? How can I do that? There are locations in multiple countries in Southern Africa (majority in ZA)

**Pull request merged**
