### PR TITLE
circle_k: fix spider and make international

### PR DESCRIPTION
**Pull request by davidhicks**
Use a new Circle API which returns global results. The last page which can be requested is
https://www.circlek.com/stores_master.php?lat=0&lng=0&page=959 and with 10 locations returned per page, and page 0 being the first, that equals a count of 9597 locations returned by this API.

Previously before this spider broke, approximately 6600 results were returned from the USA only.

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Looks like this can't match against NSI. Do you know these are all `amenity=fuel` if so, we could categorise them.

**Comment by davidhicks** [comment]
> 

Actually that's why this is still a draft--I haven't had a chance yet to execute the 960 requests to return and then combine all the JSON blobs into one JSON blob to then allow quick checking of brand parameters, etc. I've already seen the fields returned per location in each JSON blob can differ so wanted to make sure I know how many times each type of field is used, and how many times each value is set for each field.

**Comment by Cj-Malone** [comment]
Ahh, I assumed you'd been left in draft mode after #5184. I often forget to switch back to real mode on my next PR.

For testing, I sometimes set `download_delay = 0`, sometimes they block you, sometimes they allow it. I also use `-s HTTPCACHE_ENABLED=True -s HTTPCACHE_EXPIRATION_SECS=604800` as arguments so I can re run something after a change without having to redownload all the pages again. Just an FYI.

**Comment by davidhicks** [comment]
There are the services I found in the results:

   6181 "atm"
   1360 "car_wash"
     23 "car_wash_cleanfreak"
   6779 "coffee"
   5001 "diesel"
   4945 "easypay"
    306 "EU_ADBLUE_SERVICE"
    161 "EU_ATM"
     67 "EU_BABY_CHANGING"
     99 "EU_CAR_RENTAL"
    818 "EU_CARWASH"
    218 "EU_CARWASH_JETWASH"
    276 "EU_GAS"
     93 "EU_GROCERY_BAKERY"
    141 "EU_HIGH_SPEED_CHARGER"
    298 "EU_HIGH_SPEED_PUMP"
    190 "EU_LOTTO"
    371 "EU_LOUNGE"
    417 "EU_MADE_TO_GO_FAST_FOOD"
    464 "EU_MOBILE_PAYMENTS_CARWASH"
    650 "EU_MOBILE_PAYMENTS_FUEL"
     48 "EU_POSTAL_SERVICE"
    104 "EU_ROAD_TAXES"
    897 "EU_ROUTEX_ATLAS"
     99 "EU_SHOWER"
    760 "EU_SIMPLY_GREAT_COFFEE"
     83 "EU_SMOOTHIE_JUICE"
     95 "EU_TOILETS_BOTH"
     12 "EU_TRACKERS_CLUB"
    493 "EU_TRAILER_RENTAL"
    783 "EU_TRUCKDIESEL_NETWORK"
    191 "EU_TRUCK_PARKING"
     40 "EU_VACUUM_CLEANER"
    536 "EU_WIFI"
    135 "EU_WINDSHIELD_LIQUID_ON_PUMP"
     68 "ev_charger"
   3714 "fresh_food_fast"
   7197 "froster"
   3789 "fuel_day"
    996 "fuel_day_canada"
   5987 "gas"
   7325 "hotdog"
     12 "insta_cart"
   1650 "pastries"
    357 "polar_pop_fuel_event"
   6524 "public_restrooms"
     38 "rainstorm_car_wash"
   7251 "roller_grill"
    111 "shell_fuel"
   7197 "sloche"

**Comment by davidhicks** [comment]
Display brand values are (with the first column being counts):

```
      1 "BEST"
     23 "Car Wash Cleanfreak"
   7271 "Circle K"
   1055 "CIRCLEK"
     77 "CKAUTOMAT"
     11 "Corner Store"
    616 "Couche-Tard"
     43 "INGO"
     90 "Kangaroo Express"
     17 "Mac's"
     22 "ONE_TWO_THREE"
     76 "On the Run"
     38 "Rainstorm Car Wash"
      4 "STATOIL"
     31 "TRUCK"
      2 "UNKNOWN"
```

Does anyone recognise any of these as separate brands from Circle K? In other words, a fuel station is branded as "Couche-Tard" instead of "Circle K"?

**Comment by Cj-Malone** [comment]
Apparently Macs has become Circle K, but I have no knowledge of this brand at all.

https://github.com/osmlab/name-suggestion-index/pull/8143#issue-1709003603

**Pull request merged**
