### PR TITLE
Fixed spider for Aldi UK

### LINKED ISSUE #1814: Spider aldiuk is broken
During the global build at 2021-05-21-20-39-25, spider **aldiuk** failed with **0 features** and **0 errors**.

Here's [the log](https://data.alltheplaces.xyz/runs/2021-05-21-20-39-25/logs/aldiuk.log) and [the output](https://data.alltheplaces.xyz/runs/2021-05-21-20-39-25/output/aldiuk.geojson) ([on a map](https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/runs/2021-05-21-20-39-25/output/aldiuk.geojson))

### LINKED ISSUE #1824: Spider aldiuk is broken
During the global build at 2021-05-26-14-42-23, spider **aldiuk** failed with **0 features** and **0 errors**.

Here's [the log](https://data.alltheplaces.xyz/runs/2021-05-26-14-42-23/logs/aldiuk.log) and [the output](https://data.alltheplaces.xyz/runs/2021-05-26-14-42-23/output/aldiuk.geojson) ([on a map](https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/runs/2021-05-26-14-42-23/output/aldiuk.geojson))

### LINKED ISSUE #1886: Spider aldiuk is broken
During the global build at 2021-06-02-14-42-40, spider **aldiuk** failed with **0 features** and **0 errors**.

Here's [the log](https://data.alltheplaces.xyz/runs/2021-06-02-14-42-40/logs/aldiuk.txt) and [the output](https://data.alltheplaces.xyz/runs/2021-06-02-14-42-40/output/aldiuk.geojson) ([on a map](https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/runs/2021-06-02-14-42-40/output/aldiuk.geojson))

### LINKED ISSUE #1940: Spider aldiuk is broken
During the global build at 2021-06-09-14-42-21, spider **aldiuk** failed with **0 features** and **0 errors**.

Here's [the log](https://data.alltheplaces.xyz/runs/2021-06-09-14-42-21/logs/aldiuk.txt) and [the output](https://data.alltheplaces.xyz/runs/2021-06-09-14-42-21/output/aldiuk.geojson) ([on a map](https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/runs/2021-06-09-14-42-21/output/aldiuk.geojson))

### PR DESCRIPTION
**Pull request by thekuiperbelt**
Fixes #1814
Fixes #1824 
Fixes #1886 
Fixes #1940

### CODE REVIEW

**Comment by iandees** [comment]
Looks like this is only grabbing the southwest part of England? Does it run OK for you locally?

**Comment by thekuiperbelt** [comment]
Ahhh interesting I see that now. I will take a look and see if I can fix that.

**Comment by thekuiperbelt** [comment]
Updated the spider, it is now capturing all locations.

**Comment by iandees** [comment]
Thanks!

**Pull request merged**
