### PR TITLE
McDonalds

### LINKED ISSUE #1: McDonald's
JSON endpoint: http://rl.mcdonalds.com/googleapps/GoogleSearchUSAction.do?method=searchLocation&searchTxtLatlng=(43.1272254%2C-87.9432837)&actionType=searchRestaurant&language=en&country=us

Search by lat/lon only? Looks like they geocode using Google Maps API and then call this endpoint with a lat/lon.

### PR DESCRIPTION
**Pull request by SelfnessAid**
For #1

### CODE REVIEW

**Comment by iandees** [comment]
This doesn't look to be getting any more data than it did before. That one search page doesn't seem to serve all the countries, so you'll probably have to query individual McDonald's domains for their stores.

**Comment by SelfnessAid** [comment]
you mean for each country?

**Comment by iandees** [comment]
Yep. For example, mcdonalds.nl has Netherlands McDonalds and you can get them with a query like:

```
curl 'https://mcdonalds.nl/restaurant' \
  -H 'accept-encoding: gzip, deflate, br' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'accept: application/json' \
  -H 'referer: https://mcdonalds.nl/restaurant' \
  -H 'authority: mcdonalds.nl' \
  -H 'x-requested-with: XMLHttpRequest' \
  --data 'lat=52.3702&lon=4.8951&distance=5000&action=getLocations&storelocator_v2=true'
```

**Comment by SelfnessAid** [comment]
okay, got you.

**Comment by SelfnessAid** [comment]
@nvkelso 
could you possibly look at my comments on #1 ?
thanks.

**Comment by nvkelso** [comment]
Answered there, thanks for the nudge.

**Comment by iandees** [comment]
Closing this because other McDonald's spiders are filling in.

**Pull request closed without merging**
