### PR TITLE
fix #8740 - keep shared phone out of phone tag

### LINKED ISSUE #8740: natwest_gb lists general phone number for (probably) every single branch
`phone = +44 345 788 8444` is listed for nearly all or all POIs

https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md promises

> The telephone number for the venue. Note that this is usually pulled from a website assuming local visitors, so it probably doesn't include the country code.

### PR DESCRIPTION
**Pull request by matkoniecz**
"The telephone number for the venue" in https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md promises venue-specific one

Note: `callcenter_phone` is something that I invented on the spot

### CODE REVIEW

**Comment by Cj-Malone** [comment]
brand:phone is probably a more OSM tag

**Comment by davidhicks** [comment]
Agreed with @Cj-Malone to throw away the number. It's better obtained from the Wikidata item of the brand, along with other phone numbers, e-mail addresses, social media accounts, websites, mailing addresses, etc.

**Comment by matkoniecz** [comment]
I would prefer to keep it in ATP - ATP has higher reliability and cleaner licensing status than Wikidata.

But admittedly I was not planning to use it right now anyway for anything.

**Comment by matkoniecz** [comment]
Any idea when run is starting and which code was used in it? https://www.alltheplaces.xyz/map/#19.93/51.3878157/1.3811661 still shows that bad phone and I wonder whether this PR was send too late to be included or has something went wrong...

**Comment by Cj-Malone** [comment]
Weekly starts about 1330 on Saturday, so yeah this missed it by a day.

**Comment by iandees** [comment]
Sorry I normally try to get stuff merged on Friday to make it into the run on Saturday but I was traveling.

**Comment by matkoniecz** [comment]
Oh no problem with it! (I just got confused as I was not expecting this AND my side also had a data processing bug in code that should do it locally)

**Pull request merged**
