### PR TITLE
Brow Art 23 (US) (shop/beauty) (AgileStoreLocator)

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix https://github.com/alltheplaces/alltheplaces/issues/7126

For some reason by browser can happily load:
https://browart23.com/wp-admin/admin-ajax.php?action=asl_load_stores&load_all=1
But executing the scraper locally is a timeout

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
image
Utterly confused.
From my local machine, happy.
From github codespaces, timeout.

**Comment by davidhicks** [comment]
I think they might be using TLS fingerprinting to block TLS clients that don't look like web browsers?

You could try `is_playwright_spider = True` or if that doesn't work, `requires_proxy = True`, to see if one of those approaches gets around the blocking.

**Comment by CloCkWeRX** [comment]
Tried playwright to no avail, and requires_proxy = True also which is what confuses me further.
It seems odd they would block all of the GitHub ranges

**Comment by CloCkWeRX** [comment]
Going to close for now, as playwright didn't solve this.

**Comment by iandees** [comment]
The `requires_proxy=True` setting won't work unless you set a Zyte API token. The CI running from this repo has it set using donated funds. Github won't share that with PRs running in forks though.

Does the spider make a bunch of requests? If not, we can merge it as is and let it run on the weekly.

**Comment by davidhicks** [comment]
I think you can merge @iandees 

https://alltheplaces-data.openaddresses.io/map.html?show=https://alltheplaces-data.openaddresses.io/ci/7883076133/brow_art_23_us/output.geojson shows that `requires_proxy=True` works. Very few Zyte requests needed

**Review by davidhicks — APPROVED** [review]

**Comment by CloCkWeRX** [comment]
Oh, thanks for checking this

**Pull request merged**
