### PR TITLE
vinmonopolet_no - tweak name data

### PR DESCRIPTION
**Pull request by matkoniecz**

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Doesn't look like `name=Vinmonopolet Beitostølen`, don't you just want to throw it away.

https://www.google.com/maps/place/Vinmonopolet/@61.2466558,8.9110949,3a,17.9y,248.35h,92.99t/data=!3m6!1e1!3m4!1sP8_3mcGGUKhLWto1q8JfFA!2e0!7i16384!8i8192!4m14!1m7!3m6!1s0x461545180ae7f4d9:0x6ea60ac8b18eb8ee!2sVinmonopolet!8m2!3d61.2464696!4d8.9107248!16s%2Fg%2F12mkqyy5q!3m5!1s0x461545180ae7f4d9:0x6ea60ac8b18eb8ee!8m2!3d61.2464696!4d8.9107248!16s%2Fg%2F12mkqyy5q?coh=205409&entry=ttu&g_ep=EgoyMDI0MTAwNS4yIKXMDSoASAFQAw%3D%3D

**Comment by matkoniecz** [comment]
I lack local knowledge here and looked at https://www.openstreetmap.org/search?query=vinmonopolet#map=19/59.949113/10.766375

Not really sure what is better here.

screen02

**Comment by matkoniecz** [comment]
though https://www.openstreetmap.org/node/5690558046 (Vinmonopolet Beitostølen) is also with branch name, so it looks like some overenthusiastic editing in OSM.

It looks like it should be actually dropped?

**Comment by Cj-Malone** [comment]
Thanks

**Pull request merged**
