### PR TITLE
Fix Intermarche Spider

### PR DESCRIPTION
**Pull request by Cj-Malone**
@Romeo-PHILLIPS perhaps you could provide some insight on this one? Particularly around `modelLabel` at line 54+, and maybe [NSI](https://nsi.guide/index.html?t=brands&tt=Intermarch%C3%A9) isn't perfect?

### CODE REVIEW

**Comment by Romeo-PHILLIPS** [comment]
The NSI seems correct as this super-market chain offers gas stations (not all of them, those that have `"entityType": "GAS_STATION"`). 

For the brand names they should all be `Intermarché` CONTACT/DRIVE/SUPER/HYPER are just `store_types` to reflect on size of the store and what they do.

`Retrait La Poste` is weird because in some cases it just looks like a post office but nothing to do with Intermarché.

And `Réservé Soignants` are just drive through stores reserved for medical workers.

**Comment by Cj-Malone** [comment]
NSI fixed: https://github.com/osmlab/name-suggestion-index/pull/7305

**Comment by Romeo-PHILLIPS** [comment]
I think you might want to convert `SUPER ALIMENTAIRE` to -> `Intermarché Super`

**Comment by Cj-Malone** [comment]
Yeah, I'm currently pushing `SUPER ALIMENTAIRE` and `SUPER GENERALISTE` [through](https://github.com/alltheplaces/alltheplaces/pull/4169/files#diff-1d96f33816271a731982a2a2b1872787c5a42060e4b01129de9fff44f2f0ea3aR70), because I didn't know the difference. Happy to remove it if the difference is little, or correct the output if need be.

**Comment by Romeo-PHILLIPS** [comment]
> Yeah, I'm currently pushing `SUPER ALIMENTAIRE` and `SUPER GENERALISTE` [through](https://github.com/alltheplaces/alltheplaces/pull/4169/files#diff-1d96f33816271a731982a2a2b1872787c5a42060e4b01129de9fff44f2f0ea3aR70), because I didn't know the difference. Happy to remove it if the difference is little, or correct the output if need be.

Yeah they both fall into `Intermarché Super` brand

**Comment by Cj-Malone** [comment]
Are they both "supermarkets" or is one closer to a hardware store, or "houseware"?

https://wiki.openstreetmap.org/wiki/Key:shop

**Comment by Romeo-PHILLIPS** [comment]
> Are they both "supermarkets" or is one closer to a hardware store, or "houseware"?
> 
> https://wiki.openstreetmap.org/wiki/Key:shop

Both supermarkets

**Pull request merged**
