### PR TITLE
Fix walmart spider

### PR DESCRIPTION
**Pull request by jancallewaert**
Fixing spider by getting back as a SitemapSpider. I know it has been a sitemap spider in the past and was converted in a crawler. However, it seems a crawler doesn't work correctly while a sitemaps spider for me does work...

### CODE REVIEW

**Comment by JanCallewaert-TomTom** [comment]
Is it possible the Github Action is getting blocked? Locally, it runs just fine.

**Comment by jancallewaert** [comment]
Is the Github Action blocked by the website? Locally, it works fine :-(.

**Comment by Cj-Malone** [comment]
IIRC when this was changed the issue wasn't the finding the store links, but getting blocked. The first x pages worked.

Maybe we should try [AUTOTHROTTLE_ENABLED](https://docs.scrapy.org/en/latest/topics/autothrottle.html#autothrottle-enabled), but I think this one will always cause issues in the current environment.

**Comment by jancallewaert** [comment]
> IIRC when this was changed the issue wasn't the finding the store links, but getting blocked. The first x pages worked.
> 
> Maybe we should try [AUTOTHROTTLE_ENABLED](https://docs.scrapy.org/en/latest/topics/autothrottle.html#autothrottle-enabled), but I think this one will always cause issues in the current environment.

Okay, maybe we should then close this PR and think about a more general solution. I reckon there are more spiders that suffer from this.

Is there any way to see the output of the weekly runs per spider? I don't have time to write new ones but fixing spiders I can do. If I see the output of a spider, it might be easier for me to decide whether it's worth the effort to look at the spider.

**Comment by Cj-Malone** [comment]
> think about a more general solution. I reckon there are more spiders that suffer from this.

I think we've pretty much decided the solution is to set up a proxy/residential ips. It's just not been implemented yet. We are flagging the spiders that need it as `requires_proxy = True` though.

> Is there any way to see the output of the weekly runs per spider? I don't have time to write new ones but fixing spiders I can do. If I see the output of a spider, it might be easier for me to decide whether it's worth the effort to look at the spider.

In theory the [log](https://data.alltheplaces.xyz/runs/2023-01-07-13-32-28/logs/walmart.txt) but in this case it's blank. I think the issue there is related to that log only showing "errors", and scrapy/atp not classing this as an error.

**Review by Cj-Malone — APPROVED** [review]
We at least got some [POIs](https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/4026224846/walmart/output.geojson) with this combination. We'll have to wait and see for the weekly.

**Comment by Cj-Malone** [comment]
Finally got Walmart POIs! Thank you.

**Pull request merged**
