### PR TITLE
Remove all explicitly stated (generic) websites

### LINKED ISSUE #11100: website tag repeated 100 times and more - so likely not POI-specific
* [ ] website = https://www.woolworths.co.za/ repeated 464 times in woolworths_za
* [ ] website = http://www.ramrajcotton.in repeated 232 times in ramraj_cotton_in
* [ ] website = https://markt-baeckerei.de repeated 189 times in edeka_de
* [ ] website = https://www.diska.de/ repeated 101 times in edeka_de
* [ ] website = http://www.jednotaostroh.cz repeated 117 times in coop_cz
* [ ] website = http://www.jednotamk.cz repeated 104 times in coop_cz
* [ ] website = http://www.jednota-hodonin.cz repeated 127 times in coop_cz
* [ ] website = http://www.coopvelmez.cz repeated 108 times in coop_cz
* [ ] website = http://www.coophb.cz repeated 224 times in coop_cz
* [ ] website = http://www.konzumuo.cz repeated 110 times in coop_cz
* [ ] website = http://www.zkdsusice.cz repeated 123 times in coop_cz
* [ ] website = https://www.mcdonalds.com.hk/ repeated 256 times in mcdonalds_hk
* [ ] website = https://sports.coral.co.uk/ repeated 1112 times in coral_gb
* [ ] website = https://www.itesco.cz/prodejny/ repeated 185 times in tesco_eu
* [ ] website = https://www.tesco.sk/obchody/ repeated 177 times in tesco_eu
* [ ] website = https://www.tesco.hu/aruhazak/ repeated 197 times in tesco_eu
* [ ] website = https://www.arbys.com.tr/restoranlar repeated 128 times in arbys_tr
* [ ] website = https://www.cheddars.com/web-api/restaurants repeated 185 times in cheddars_scratch_kitchen
* [x] website = https://www.century21global.com/ repeated 10000 times in century_21
* [ ] website = https://www.starbucks.com.sg/stores/ repeated 131 times in starbucks_sg
* [ ] website = https://sports.ladbrokes.com/ repeated 1577 times in ladbrokes_gb
* [ ] website = https://tiendas3b.com/ repeated 2239 times in tiendas_3b_mx
* [ ] website = https://www.kingpie.co.za/ repeated 269 times in king_pie_za
* [ ] website = https://www.starbucks.com.ar/stores repeated 129 times in starbucks_ar_cl
* [ ] website = https://www.starbucks.cl/stores repeated 151 times in starbucks_ar_cl
* [ ] website = https://www.boostmobile.com/ repeated 329 times in boost_mobile_us
* [ ] website = https://pizzahut.vn/ repeated 129 times in pizza_hut_vn
* [ ] website = http://www.papajohns.co.uk repeated 403 times in papa_johns_gb
* [ ] website = https://www.cricketwireless.com/stores repeated 354 times in cricket_wireless
* [ ] website = https://www.hofer.at/ repeated 529 times in hofer_at
* [ ] website = https://www.pizzahut.co.nz/ repeated 135 times in pizza_hut_nz
* [ ] website = https://www.nissan-europe.com/ repeated 366 times in nissan_eu
* [ ] website = https://www.fountaintire.com/ repeated 165 times in fountain_tire_ca
* [ ] website = https://www.salmoiraghievigano.it/ repeated 254 times in sunglass_hut
* [ ] website = https://stores.pandora.net/ repeated 6537 times in pandora
* [ ] website = https://www.hyundai.at/partner-finden repeated 138 times in hyundai_at
* [ ] website = https://www.bncollege.com/campus-stores/ repeated 277 times in barnes_and_noble_college
* [ ] website = https://www.burgerking.com.br repeated 917 times in burger_king_br
* [ ] website = www.ford.net.my repeated 108 times in ford
* [ ] website = https://uae.pizzahut.me/ repeated 156 times in pizza_hut_ae_sa
* [ ] website = https://starbucks.com.br/lojas repeated 142 times in starbucks_br
* [ ] website = https://www.mapcorewards.com repeated 190 times in mapco_us
* [ ] website = http://www.skechers.com repeated 5942 times in skechers
* [ ] website = https://www.avia-france.fr/ repeated 783 times in avia_fr
* [ ] website = www.boscoffee.com repeated 103 times in bos_coffee_ph
* [ ] website = https://dealerlocator.volkswagen.be/fr repeated 552 times in volkswagen_be
* [ ] website = https://www.calvinklein.us/en repeated 123 times in calvin_klein_ca_us
* [ ] website = https://www.pizzahut.com.hk/ repeated 106 times in pizza_hut_hk
* [ ] website = https://www.foetex.dk/kundeservice/find-din-foetex/ repeated 111 times in salling_group_dk
* [ ] website = https://www.pizzahut.co.th/ repeated 190 times in pizza_hut_th
* [x] website = https://kfcku.com/ repeated 705 times in kfc_id
* [ ] website = https://www.pizzahut.co.kr/ repeated 255 times in pizza_hut_kr
* [ ] website = https://www.mcdonalds.com.my repeated 368 times in mcdonalds_my
* [ ] website = https://www.circlek.com.vn/vi/store-locator/ repeated 476 times in circle_k_vn
* [ ] website = https://loc.costa-coffee.cz/locator/ repeated 120 times in costa_coffee_cz
* [ ] website = https://www.medexpress.com repeated 132 times in medexpress_us
* [ ] website = https://www.stadt-zuerich.ch/wertstoffsammelstelle repeated 176 times in stadt_zuerich_ch
* [ ] website = https://www.frankfurter-volksbank.de repeated 166 times in vr_bank_de
* [ ] website = https://www.volksbanking.de repeated 155 times in vr_bank_de
* [ ] website = https://www.volksbank-pur.de repeated 128 times in vr_bank_de
* [ ] website = https://www.vb-rb.de repeated 124 times in vr_bank_de
* [ ] website = https://www.volksbank-stuttgart.de repeated 101 times in vr_bank_de
* [ ] website = https://www.pizzahut.com.my/ repeated 472 times in pizza_hut_my

### PR DESCRIPTION
**Pull request by arrival-spring**
We state that the website provided is a store-specific website:

> The website for the venue. We try to make this a URL specific to the venue and not a generic URL for the brand that is operating the venue.

So removing all that are explicitly stated, and clearly generic.

Closes #11100 (does not fix all of them, but marking closed as advised)

### CODE REVIEW

**Comment by arrival-spring** [comment]
AWS doesn't want to run this many spiders

n.b. I haven't rerun these locally, do I need to or not?

**Comment by matkoniecz** [comment]
looking at changes, this edit feels quite save

but I am not a maintainer

**Review by matkoniecz — APPROVED** [review]
note: I looked at code, have not run it

**Comment by matkoniecz** [comment]
> Ref https://github.com/alltheplaces/alltheplaces/issues/11100 (does not fix all of them though)

I would add "closes #11100" here and on similar, I will just regenerate it in a week (less effort than adding checkmarks at correct location)

**Comment by arrival-spring** [comment]
Noted

My thinking had been that generic websites can easily enough be fetched from Wikidata if desired

**Pull request merged**
