### PR TITLE
Add Castorama PL Spider

### LINKED ISSUE #5893: Castorama - Poland
### Brand name

Castorama

### Wikidata ID

Q966971

### Store finder url(s)

https://www.castorama.pl/informacje/sklepy

### PR DESCRIPTION
**Pull request by Cj-Malone**
Fixes #5893

### CODE REVIEW

**Comment by matkoniecz** [comment]
Some seem missing, compare http://overpass-turbo.eu/s/1AL0

**Comment by Cj-Malone** [comment]
PR only runs for ~1 minuet. I think I had 98 when I ran locally.

**Comment by matkoniecz** [comment]
Oh, so "Resulted in a timeout ([Log](https://data.alltheplaces.xyz/ci/6249969943/castorama_pl/log.txt))" indicates that you look at sample only.

**Comment by Cj-Malone** [comment]
The 98 that I got locally: https://gist.github.com/Cj-Malone/47bed500b5ea465b940b9680b5b8c15d

**Comment by matkoniecz** [comment]
this makes sense! I was just unaware that it is only sample being shown

BTW `image=https://s7g10.scene7.com/is/image/KingfisherDigital/66aefe0e1b764a023696e9977d43a2e0978b009d` seems repeated and is again a logo

**Comment by iandees** [comment]
I used "timeout" because I couldn't think of another single word to use there that meant the same thing but was positive. I want to keep the table short/concise.

The important thing is if the build passes or fails.

**Pull request merged**
