### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by iandees**
This makes the readme's install instructions more specific (for Ubuntu and macOS) and adds information about using pyenv.

### CODE REVIEW

**Comment by iandees** [comment]
Relates to https://github.com/alltheplaces/alltheplaces/issues/7312

**Comment by matkoniecz** [comment]
+1 - though I guess that it introduces expectation of updating this readme for each LTS version

And not sure is it reasonable to add also this, but hint about devcontainer may be a good idea (I have not figured out what Pipenv is changing on my system so I like version with container keeping such changes inside)

**Comment by iandees** [comment]
> it introduces expectation of updating this readme for each LTS version

I think it's a good idea to revisit the install instructions periodically to make sure they still work, so I'm OK with this.

> hint about devcontainer may be a good idea

I'm not sure how that system works. Maybe @CloCkWeRX can suggest a change to the readme that mentions how to use it?

> I have not figured out what Pipenv is changing on my system so I like version with container keeping such changes inside

Python has the concept of [virtual environments](https://docs.python.org/3/tutorial/venv.html), with the goal of keeping your Python dependencies out of the system's python altogether. Pipenv and Pyenv work together to manage virtual environments and the dependencies in them. If you follow the instructions in the readme as-is, your global system should not be affected at all.

**Comment by CloCkWeRX** [comment]
>I'm not sure how that system works. Maybe @CloCkWeRX can suggest a change to the readme that mentions how to use it?

So, codespaces _should_ be a part of the github UI for pretty much everyone.

It's simply a checkout option:
image


Which then launches a web based version of VS Code (you can also have VS Code installed locally and connect to the cloud hosted container)

image

It also executes the content of the Dockerfile; and adds any extras in the devcontainer.json - for example, bash completion is a handy quality of life improvement.

This gives you a cloud development environment which turns itself off after a while of inactivity, so it can be really handy for casual contribution or executing big runs of scraper testing from the cloud; rather than your local machine.

Biggest downsides are accidentally closing your tab when you use ctrl+w in the terminal emulator and after ~3 weeks it forgets your auth tokens

**Comment by matkoniecz** [comment]
Oh  that is this one. (Though I have not used this and do not plan to use it as part of avoiding features specific to proprietary products)

**Pull request merged**
