### PR TITLE
Fix broken postbank_bg spider

### PR DESCRIPTION
**Pull request by Dimitar5555**

### CODE REVIEW

**Comment by Dimitar5555** [comment]
It works on my machine. I'm not sure why it's giving 403 error here.

**Comment by iandees** [comment]
Likely getting blocked because of the IP range we request from.

**Comment by iandees** [comment]
I think the proxy we normally use also doesn't know what to do with this domain. We'll leave it for now and hopefully they resolve it.

**Comment by Dimitar5555** [comment]
> Likely getting blocked because of the IP range we request from.

Their site might be restricted for users outside of Bulgaria... It's not the first local bank that does it.

**Pull request merged**
