### PR TITLE
TractorSupply

### LINKED ISSUE #153: Tractor Supply
http://www.tractorsupply.com/tsc/store-locator

### PR DESCRIPTION
**Pull request by whoissteven**
Fixes #153.

Having issues sending properties to GeojsonPointItem.
"KeyError: 'GeojsonPointItem does not support field: fieldname"

Any ideas why I run into this..? Thanks!

Also, my spider runs so fast that eventually their servers block my IP.
Should I use a simple sleep to avoid any issues?

### CODE REVIEW

**Comment by whoissteven** [comment]
Added a 2 second sleep after the properties dict is built, but it seems it didn't benefit anything. 9 less results that run.

Open to suggestions on this one. Thanks.

**Comment by iandees** [comment]
Scrapy "items" only allow you to set certain properties  (see the list of properties on the [GeojsonPointItem](https://github.com/alltheplaces/alltheplaces/blob/master/locations/items.py) class). Read [the Scrapy documentation about items](https://docs.scrapy.org/en/latest/topics/items.html), too.

To slow the spider down, use the `download_delay` property on your spider. See [this other spider](https://github.com/alltheplaces/alltheplaces/blob/0f6fa8463b38493f031c252fee43d5553cc781a1/locations/spiders/sephora.py#L11) as an example. Also, there is [documentation on `download_delay` here](https://doc.scrapy.org/en/latest/topics/settings.html?highlight=download_delay#download-delay).

**Comment by whoissteven** [comment]
What is the max download we should be setting to avoid the script timing out?

**Comment by iandees** [comment]
There shouldn't be a max download set: the timeout is for testing only and won't be set when we run to get all the data.

**Pull request merged**
