### PR TITLE
Add Lewiatan PL Spider

### LINKED ISSUE #5894: Lewiatan
### Brand name

Lewiatan

### Wikidata ID

Q11755396

### Store finder url(s)

https://www.lewiatan.pl/znajdz-sklep

### PR DESCRIPTION
**Pull request by Cj-Malone**
Fixes #5894

@matkoniecz NSI has this as convenience stores and supermarkets, can you see a way for us to tell from the data?

https://www.lewiatan.pl/api/stores

### CODE REVIEW

**Comment by matkoniecz** [comment]
No, and pages like https://www.lewiatan.pl/znajdz-sklep/lewiatan-krakow-ul-na-blonie-11b have no real hint either

BTW, `  "addr:city": "Kraków (Kraków-Krowodrza)",` contains not only city name but also suburb name

`  "name": "PRZEDSIĘBIORSTWO HANDLOWO USŁUGOWE ZACHĘTA SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWA",` would rather fit `operator`

Oh, and pages like https://www.lewiatan.pl/znajdz-sklep/lewiatan-krakow-ul-na-blonie-11b seem to have opening hours

**Comment by Cj-Malone** [comment]
Are all the names operators?

This isn't parsing the web pages, but the [api](https://www.lewiatan.pl/api/stores). There is `field_open_hours_1_value` to `field_open_hours_4_value`. If you can work out what they mean, I'll happily parse them.

My guess would be 1 = Mo-Th, 2 = Fr, 3 = Sa, 4 = Su. But I didn't spend any time checking.

**Comment by matkoniecz** [comment]
> Are all the names operators?

Yes. All of several I checked are legal names of companies, and all Lewiatan stores I have seen use uniform brand name with no branch variations.

> My guess would be 1 = Mo-Th, 2 = Fr, 3 = Sa, 4 = Su. But I didn't spend any time checking.

1 Mo-Fr
2 Sa
3 Su with allowed trade (there is no good tagging for that: I guess it can be Su with "niedziela handlowa" comment)
4 All sundays - see https://www.lewiatan.pl/znajdz-sklep/lewiatan-biadoliny-szlacheckie-biadoliny-szlacheckie-206

**Comment by Cj-Malone** [comment]
> 3 Su with allowed trade (there is no good tagging for that: I guess it can be Su with "niedziela handlowa" comment)
> 4 All sundays - see https://www.lewiatan.pl/znajdz-sklep/lewiatan-biadoliny-szlacheckie-biadoliny-szlacheckie-206

There are 141 x field_open_hours_3_value but only 24 x field_open_hours_4_value. Is that expected. Which is the usual Sunday?

We don't currently output comments or public holidays.

**Comment by matkoniecz** [comment]
> Is that expected.

Yes. In short, law allows petrol stations/pharmacies etc and self-owned shops to be open on all Sundays (this includes franchises). Most Lewiatans are closed on Sundays.

BTW, this law was also causing #5890 weirdness

**Pull request merged**
