### PR TITLE
Charles Vögele

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes https://github.com/alltheplaces/alltheplaces/issues/7367

2024-02-27 08:54:22 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Charles Vögele': 46,
 'atp/brand_wikidata/Q1066326': 46,
 'atp/category/shop/clothes': 46,
 'atp/field/country/from_reverse_geocoding': 46,
 'atp/field/email/missing': 46,
 'atp/field/image/missing': 46,
 'atp/field/operator/missing': 46,
 'atp/field/operator_wikidata/missing': 46,
 'atp/field/phone/invalid': 22,
 'atp/field/twitter/missing': 46,
 'atp/field/website/missing': 46,
 'atp/nsi/perfect_match': 46,
 'downloader/request_bytes': 682,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 30082,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/404': 1,
 'elapsed_time_seconds': 3.606032,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 2, 27, 8, 54, 22, 957161, tzinfo=datetime.timezone.utc),
 'item_scraped_count': 46,
 'log_count/DEBUG': 59,
 'log_count/INFO': 9,
 'memusage/max': 150466560,
 'memusage/startup': 150466560,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/404': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 2, 27, 8, 54, 19, 351129, tzinfo=datetime.timezone.utc)}
2024-02-27 08:54:22 [scrapy.core.engine] INFO: Spider closed (finished)

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Not 100% sure if they are AT or DE, or both, or more

**Comment by CloCkWeRX** [comment]
Needs more research as to exactly what is physically on the ground and where.

**Comment by Cj-Malone** [comment]
https://alltheplaces-data.openaddresses.io/map.html?show=https://alltheplaces-data.openaddresses.io/ci/8062078078/charles_voegele/output.geojson has AT, HU, SI

**Comment by CloCkWeRX** [comment]
Thanks re spider. I still feel like this needs checking by someone local to those areas or something, as the wikipedia articles as suggest a lot of closures happened. I don't want to accidentally index stores that don't exist just because someone keeps paying a WordPress hosting bill for a holding company

**Comment by Cj-Malone** [comment]
You can spot check these against Google imagery/data to validate these are real POIs. I don't know how much effort you want to put in for 46 POIs though.

**Comment by CloCkWeRX** [comment]
Ah hah:
http://www.sempionefashion.com/en-CH/company-en

> Charles Vögele Holding AG merged with Charles Vögele Mode AG in autumn 2017. The merged company was renamed Sempione Fashion AG and sells the Italian fashion brand OVS in its stores as a sales organisation in Switzerland.

The conversion to OVS will take place in Austria in the second half of 2018. The Charles Vögele brand will remain in Hungary until further notice. The German sales organisation was sold to a Dutch fashion retailer in spring 2018.

**Comment by CloCkWeRX** [comment]
@iandees I consider this ready

**Comment by CloCkWeRX** [comment]
Maybe blocked by https://github.com/alltheplaces/alltheplaces/pull/7912

**Comment by CloCkWeRX** [comment]
Back to green :)

**Pull request merged**
