### PR TITLE
OpeningHours: introduce add_ranges_from_string

### PR DESCRIPTION
**Pull request by davidhicks**
add_ranges_from_string is added as a parser function designed to help translate from opening hours provided as human readable text in a fuzzy format.

This function is intended to add opening hours ranges based on the following type of ranges that may be found in source data:

1. Monday-Wednesday: 5pm - 7pm
2. Monday-Wednesday 08:00-14:00
3. Monday to Tuesday: 15:00:01 to 16:35
4. Thurs 2PM-6:30PM
5.  Fri    9am  -  11am
6. Weekends: 8:00 AM to 6:00 PM
7. Monday to Thursday 7am to 7pm, Friday 7am to 10pm, Weekends CLOSED

This function works with a source that may mix and match from the type of examples listed above. For example, if a source uses both 12h and 24h times to describe opening hours.

This function does not currently support extraction of multiple opening hours on the same day of a week. Only the first opening time of each day is extracted. This function should therefore not be used if the source data has the potential to list multiple opening hours for the same day.

This function does not currently support named times of each day such as 'Midday' and "Midnight". It is possible to replace these prior to the input string being provided to this function.

This function allows specification of days and day ranges in langauges other than the default English.

### CODE REVIEW

**Comment by iandees** [comment]
I'd be interested in seeing more examples of where this would be useful. I worry that this block of code is relatively dense and hard to improve to support other styles of hours.

**Comment by iandees** [comment]
That being said, thank you for writing this. It would be very useful to have!

**Comment by davidhicks** [comment]
> I'd be interested in seeing more examples of where this would be useful.

I've got a few examples ready to submit, but so far they're all English. I'll send them through referencing this pull request. I'd like to try and find some non-English examples too but will likely have to rely on others to help with that.

**Comment by Cj-Malone** [comment]
Would it be more manageable if the time code was split into a different function?

Also [Tous](https://www.tous.com/gb-en/stores) looks to have some good examples in a bunch of languages, eg:
`$ curl "https://brand.tous.com/gb-en/stores/listByCountry.html?idBusinessCountry=MX" | jq ".shops[].schedule" -r | sort | uniq`
```
Lunes a Domingo de 10:00 a 17:00
Lunes a Domingo de 11:00 a 19:00
Lunes a Domingo de 11:00 a 20:00
Lunes a Domingo de 11:00 a 21:00
Lunes a Domingo de 11:00 a 21:00
Lunes a Domingo de 12:00 a 18:00
Lunes a Domingo de 12:00 a 19:00
Lunes a Domingo de 12:00 a 19:00
Lunes a Domingo: 10:00 a 19:00
Lunes a Domingo: 10:00 a 21:00
Lunes a Domingo: 10:30 a 20:00
Lunes a Domingo: 11:00 a 17:00
Lunes a Domingo: 11:00 a 17:00
Lunes a Domingo: 11:00 a 18:00
Lunes a Domingo: 11:00 a 19:00
Lunes a Domingo: 11:00 a 19:00
Lunes a Domingo: 11:00 a 20:00
Lunes a Domingo: 11:00 a 20:00
Lunes a Domingo: 11:00 a 20:30
Lunes a Domingo: 11:00 a 20:30 / Viernes y Sábado: 11:00 a 21:00
Lunes a Domingo: 11:00 a 21:00
Lunes a Domingo: 11:00 a 21:00
Lunes a Domingo: 12:00 a 18:00
Lunes a Jueves: 11:00 a 20:30 / Viernes a Sábado: 11:00 a 21:00
Lunes a Sábado de 11:00 a 21:00 / Domingo de 11:00 a 20:00
Lunes a Sábado: 10:00 a 18:00
Lunes a Sábado: 11:00 a 20:00 / Domingo: 12:00 a 18:00
Lunes a Sábado: 11:00 a 21:00
Lunes a Viernes: 12:00 a 18:00
Lunes a Viernes: 12:00 a 19:00
```

**Comment by davidhicks** [comment]
Thanks @Cj-Malone 

I've added Spanish tests based on the Tous opening hours. To make this work, I also allowed the add_ranges_from_string function to be passed a language-specific set of delimiters specified for words that exist between e.g. "Monday to Wednesday" or "Friday and Saturday" or "09:00 to 10:00", "Monday from 09:00 to 10:00", etc.

For splitting time code, do you mean move all the DAYS_xx / NAMED_DAYS_xx / DELIMITERS_xx lists into e.g. separate JSON files per language to avoid having 200 different lists defined in locations/hours.py? This seems like a good clean up exercise and longer term goal. Perhaps this data could be populated automatically or synced semi-automatically from sources such as:

https://query.wikidata.org/#SELECT%20%3FdayLabel%20%3Fisocode%20%3FlanguageLabel%20%3Flemma%20WHERE%20%7B%0A%20%20%3Fl%20a%20ontolex%3ALexicalEntry%3B%0A%20%20%20%20%20%20%20ontolex%3Asense%20%3Fsense%3B%0A%20%20%20%20%20%20%20dct%3Alanguage%20%3Flanguage%3B%0A%20%20%20%20%20%20%20wikibase%3Alemma%20%3Flemma.%0A%20%20%3Fsense%20wdt%3AP5137%20%3Fday.%0A%20%20%3Fday%20wdt%3AP31%20wd%3AQ41825.%0A%20%20%3Flanguage%20wdt%3AP218%20%3Fisocode.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20%3FdayLabel%20%3Fisocode%20%3Flemma

**Comment by davidhicks** [comment]
Also I was wondering whether the "day_hours" defaultdict as part of the OpeningHours class could be changed to have mutable ranges instead of tuples for hour ranges, allowing the add_range function to de-duplicate overlapping ranges. This was on my mind before looking at the Tous opening hours, but now Tous has shown a real world case where a source provides overlapping hour ranges e.g.: Lunes a Domingo: 11:00 a 20:30 / Viernes y Sábado: 11:00 a 21:00

Which is: ```Monday-Sunday: 11:00-20:30, Friday-Saturday: 11:00-21:00```, where the add_ranges function should ideally just amend 11:00-20:30 to be 11:00-21:00 when it sees the second Friday-Saturday range be added.

**Comment by Cj-Malone** [comment]
> For splitting time code, do you mean move all the DAYS_xx / NAMED_DAYS_xx / DELIMITERS_xx lists into e.g. separate JSON files per language to avoid having 200 different lists defined in locations/hours.py? This seems like a good clean up exercise and longer term goal.

I meant more the parsing of start & end time. It might make it more readable, and it might be possible to use it with `from_linked_data` as that currently needs the defined time format.

**Comment by iandees** [comment]
Thanks for adding the comments!

**Comment by iandees** [comment]
I am worried that this is pretty brittle and that it's not great to put a bunch of specific parsing logic in a general spot (i.e. we try to fix a bug for one spider but end up breaking 3 others), but let's see how it goes.

**Pull request merged**
