### PR TITLE
&pizza

### LINKED ISSUE #138: &pizza
You have to click the Locations link on the right, no direct link that I can find http://www.andpizza.com

### PR DESCRIPTION
**Pull request by Eagle19243**
Fixes #138.

### CODE REVIEW

**Comment by Eagle19243** [comment]
Thanks for your fix, @iandees. I will reference it in the future.

**Comment by Eagle19243** [comment]
@iandees, Could you please merge this pull request to master branch?

**Comment by iandees** [comment]
It's not quite ready yet. I haven't had a chance for a full review, but the opening hours are in the incorrect format and there's no latitude or longitude extracted. It looks like they don't have lat/lon on the website.

**Comment by Eagle19243** [comment]
Yes, they don't have lat/lon on the website. And I will try to fix the opening hours in correct format.

**Comment by iandees** [comment]
I'm ok with leaving out lat/lon for now. We can add a step to introduce that later. Let me know when the hours format is ready.

**Comment by Eagle19243** [comment]
@iandees, opening_hours format is ready. Could you please check the above commit ?

**Comment by iandees** [comment]
Great work!

**Comment by Eagle19243** [comment]
Thanks

**Pull request merged**
