### PR TITLE
[worldcat] Add spider - advice requested

### LINKED ISSUE #38: The Library
https://www.worldcat.org/libraries

### PR DESCRIPTION
**Pull request by arrival-spring**
Fixes #38

The question is which "institution type" do we want, or what extra tags to apply. From a look at a sample, most with a type of "OTHER" are not really libraries or are at least private. Do we take them anyway and add another tag, or skip them? I think everything else is fine though.

If anyone wants to look here https://search.worldcat.org/libraries and search for a location you're familiar with and see what types show up and add a comment that would be helpful.

```
 'atp/worldcat/type/ACADEMIC': 29894,
 'atp/worldcat/type/CORPORATE_SPECIAL_LIBRARY': 3115,
 'atp/worldcat/type/HEALTH': 1630,
 'atp/worldcat/type/LAW': 244,
 'atp/worldcat/type/LIBRARY_NETWORK_GROUP': 2976,
 'atp/worldcat/type/MUSEUM_OR_ARCHIVES': 1292,
 'atp/worldcat/type/MUSIC': 43,
 'atp/worldcat/type/OTHER': 61972,
 'atp/worldcat/type/PUBLIC': 35009,
 'atp/worldcat/type/REGIONAL_OR_NATIONAL': 6355,
```

```
 'atp/category/amenity/library': 142530,
 'atp/cdn/cloudflare/response_count': 2852,
 'atp/cdn/cloudflare/response_status_count/200': 2852,
 'atp/closed_check': 8,
 'atp/field/branch/missing': 142530,
 'atp/field/brand/missing': 142530,
 'atp/field/brand_wikidata/missing': 142530,
 'atp/field/city/missing': 3371,
 'atp/field/country/from_reverse_geocoding': 7,
 'atp/field/country/from_website_url': 142,
 'atp/field/country/missing': 2676,
 'atp/field/email/invalid': 1472,
 'atp/field/email/missing': 113043,
 'atp/field/image/missing': 142530,
 'atp/field/lat/invalid': 3,
 'atp/field/lat/missing': 8394,
 'atp/field/lon/invalid': 3,
 'atp/field/lon/missing': 8394,
 'atp/field/opening_hours/missing': 142530,
 'atp/field/operator/missing': 142530,
 'atp/field/operator_wikidata/missing': 142530,
 'atp/field/phone/invalid': 1596,
 'atp/field/phone/missing': 90632,
 'atp/field/postcode/missing': 8737,
 'atp/field/state/from_reverse_geocoding': 85588,
 'atp/field/state/missing': 51828,
 'atp/field/street_address/missing': 3767,
 'atp/field/twitter/missing': 142530,
 'atp/field/website/invalid': 81,
 'atp/field/website/missing': 82129,
 'atp/geometry/null_island': 1,
 'atp/item_scraped_host_count/search.worldcat.org': 142530,
```

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
https://wiki.openstreetmap.org/wiki/Tag:amenity=library is a bit of a muddle.

Perhaps we want to be conservative for now and only output clearly public libraries, or make sure we pass through the worldcat detail in extras

The other category for me locally had examples of school or technical college libraries, generally not available to the public.

**Comment by davidhicks** [comment]
For those in the PUBLIC category:
```
amenity=library
```

All others are probably:
```
amenity=library
access=private
```

(in reality, `permissive` may be more accurate but I don't think we'd have any data to know whether this is true or not, hence `private` I'd argue is better`)

**Comment by panasonic-mafia** [comment]
Worldcat spider existed before in alltheplaces and it was removed as it's an aggregator: https://github.com/alltheplaces/alltheplaces/pull/9927#issuecomment-2315409721

**Comment by matkoniecz** [comment]
What is the license of this data? It is now first-party data so it is trickier than typical case.

**Comment by davidhicks** [comment]
> What is the license of this data? It is now first-party data so it is trickier than typical case.

No different to any other spider from what I can tell. It's just showing up as name, street address, coordinates, phone number and e-mail address. Therefore no copyrightable content as it's raw data and not the result of a creative process.

**Comment by davidhicks** [comment]
> Worldcat spider existed before in alltheplaces and it was removed as it's an aggregator: [#9927 (comment)](https://github.com/alltheplaces/alltheplaces/pull/9927#issuecomment-2315409721)

Seemingly a proxy is no longer needed, so your new spider could be added without having the previous problem of needing an (expensive) proxy service to be used for the ~2850 requests sent. Looks good to be added again?

**Comment by arrival-spring** [comment]
Well, I hadn't realised it had existed before.

With the comment about it being an aggregator, is it duplicating data from other spiders? (I'm not aware of any)

**Comment by matkoniecz** [comment]
> Therefore no copyrightable content as it's raw data and not the result of a creative process.

depending on data source it may be running into database rights issues if using this in area where such thing exists

**Comment by davidhicks** [comment]
> Well, I hadn't realised it had existed before.
> 
> With the comment about it being an aggregator, is it duplicating data from other spiders? (I'm not aware of any)

I think this aggregator is OK because most of of the libraries it knows about are not within other chains of libraries, and the data is seemingly contributed directly by member libraries and more likely to be accurate. Even if there are other aggregators existing (such as https://www.nla.gov.au/apps/libraries/ for Australia) I would be fine with capturing duplicate POIs which can then be merged together automatically post-crawl by ATP consumers.

**Comment by matkoniecz** [comment]
I found some issue: unexpectedly present link in `addr:street_address` ( http://www.ajol.info ) reported as #11198

**Pull request merged**
