### PR TITLE
[allegro_one_box_pl] filter for only PL points, try to extract more data

### LINKED ISSUE #8900: allegro_one_box_pl - allegro parcel machines have extractable addresses
see say https://allegro.pl/kampania/one/znajdz-nas?pointId=1195850

"Kozia 14 30-733 Kraków"

(to be strict, it is not exactly address of machine, just nearest address but it is still useful to check locations by geocoding)

### PR DESCRIPTION
**Pull request by ireun**
Not sure if it will be fast enough..

Fixes #8900

### CODE REVIEW

**Comment by iandees** [comment]
What assistance do you need?

**Comment by ireun** [comment]
Why is it timing out? Can it be made somehow faster, concurrent or sth?

**Comment by iandees** [comment]
A timeout on the CI is ok. It only gets 60 seconds to run before reporting back to Github. It will get 8+ hours to run in the weekly system.

**Comment by ireun** [comment]
Fine, so I guess we can merge this one :)

**Comment by ireun** [comment]
Also - this fixes https://github.com/alltheplaces/alltheplaces/issues/8900

**Pull request merged**
