### PR TITLE
move `name` into `branch` for `tesco_eu`

### PR DESCRIPTION
**Pull request by vfosnar**
## Before
name:
```
Hypermarket Komárno
EXTRA Bratislava Zlaté piesky
Supermarket Poltár
Supermarket Sečovce
TESCO Szeged Szupermarket
TESCO expressz Sopron - Lackner K. utca
TESCO Expressz Bp. - Ady Endre utca
TESCO Gyöngyös Hipermarket
Hypermarket Uherské Hradiště
Expres Praha Mendelova
Supermarket Odolena Voda
Expres Nový Bor
```

## After
name:
```
Tesco
Tesco Extra
Tesco
Tesco
Tesco
Tesco Express
Tesco Express
Tesco
Tesco
Tesco Express
Tesco
Tesco Express
```

branch:
```
Hypermarket Komárno
EXTRA Bratislava Zlaté piesky
Supermarket Poltár
Supermarket Sečovce
Szeged Szupermarket
expressz Sopron - Lackner K. utca
Expressz Bp. - Ady Endre utca
Gyöngyös Hipermarket
Hypermarket Uherské Hradiště
Expres Praha Mendelova
Supermarket Odolena Voda
Expres Nový Bor
```

### CODE REVIEW

**Comment by Cj-Malone** [comment]
I don't love these branches, IMO the format (eg "Hypermarket", "Expressz") shouldn't be in them. Right now, it looks like it'd be a mess to clean them, I'd be OK with removing the names completely so we get NSI names.

**Comment by vfosnar** [comment]
The `name`s are being applied from the NSI. Tesco has a different NSI/wikidata entry for each of these 3 cases. In case of `branch`es I think it should include Supermarket etc. as that's part of their branding.

**Comment by Cj-Malone** [comment]
It's already part of the `name` and `brand`.

**Comment by vfosnar** [comment]
That makes sense, fixed it. Now it only leaves `Supermarket` and `Hypermarket` in `branch`. These are not included in `name` and shouldn't be, but they are good to know.

**Review by Cj-Malone — APPROVED** [review]
I still don't think store formats belong in `branch`. However it's not worth the argument, this is an improvement. Thank you.

**Comment by vfosnar** [comment]
I'd personally prefer a tag to describe hypermarket, but [it's abondoned](https://wiki.openstreetmap.org/wiki/Proposal:Hypermarket). I find this information useful and I'm not sure where else to store it so it's user visible.

**Pull request merged**
