### PR TITLE
Mcdonalds

### LINKED ISSUE #1: McDonald's
JSON endpoint: http://rl.mcdonalds.com/googleapps/GoogleSearchUSAction.do?method=searchLocation&searchTxtLatlng=(43.1272254%2C-87.9432837)&actionType=searchRestaurant&language=en&country=us

Search by lat/lon only? Looks like they geocode using Google Maps API and then call this endpoint with a lat/lon.

### PR DESCRIPTION
**Pull request by SelfnessAid**
Fixes #1

### CODE REVIEW

**Comment by SelfnessAid** [comment]
ah~, I made same mistake.

**Comment by nvkelso** [comment]
I suspect locations/spiders/tops.py
<https://github.com/alltheplaces/alltheplaces/blob/33b06eb86fc467a8366024274df24967372e33cb/locations/spiders/tops.py>
should
be removed from this PR?
<https://github.com/alltheplaces/alltheplaces/blob/33b06eb86fc467a8366024274df24967372e33cb/locations/spiders/tops.py>

**Comment by SelfnessAid** [comment]
yes, I removed it.
not sure why it's here yet.
it seems I created branch from "tops" branch, not master.
sorry for it.
I'll fix it soon. @nvkelso

**Comment by SelfnessAid** [comment]
@nvkelso could you possibly remove 1-mcdonalds branch now?
thanks.

**Pull request closed without merging**
