### PR TITLE
Add Bulgarian Posts (BG) (3007 locations)

### LINKED ISSUE #5809: Bulgarian Posts
### Brand name

Български пощи

### Wikidata ID

Q2880826

### Store finder url(s)

https://new.bgpost.bg/api/offices?search_by_city_name_or_address=

The URL above returns all of their offices. Hopefully they won't patch it.

If the working hours for a particular day are `null` it means that they don't work on that day.

### PR DESCRIPTION
**Pull request by davidhicks**
Fixes #5809

### CODE REVIEW

**Comment by iandees** [comment]
These don't have any category info. Are they post offices?

**Comment by davidhicks** [comment]
@Dimitar5555 can you check the map (https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/6097780372/bulgarian_posts_bg/output.geojson) and advise what points are present (e.g. branch, ATM, ..)?  The locations look too close for branches and there is no "type" field in the raw data.

**Comment by Dimitar5555** [comment]
> These don't have any category info. Are they post offices?

Yes, they are post offices.


> @Dimitar5555 can you check the map (https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/6097780372/bulgarian_posts_bg/output.geojson) and advise what points are present (e.g. post office, postbox, ..)? The locations look too close for post offices and there is no "type" field in the raw data.

Thank you for making a PR!

Everything is looking good. This is just how our posts operate - there are multiple offices in each city (one office per postcode). In Sofia there are also smaller offices in more popular places (metro stations and large supermarkets). Every other village has a post office. Offices in very small villages are operated by a team which runs a dozen offices in that area on a predefined schedule. Most of the smaller offices are used by elderly people since they don't have any other means to receive their pension.

**Comment by iandees** [comment]
Thanks for the context, @Dimitar5555

**Comment by davidhicks** [comment]
Thank you @Dimitar5555 :)

**Pull request merged**
