### PR TITLE
[Shoe Zone GB] Add address and opening hours

### PR DESCRIPTION
**Pull request by TheUKHighStreet**
I'm sure that there must be an easier way to get the structured data spider to get the opening hours from scraping the page.

### CODE REVIEW

**Comment by Cj-Malone** [comment]
> I'm sure that there must be an easier way to get the structured data spider to get the opening hours from scraping the page.

The structured data is broken, we might be able to fix it in pre process, but it's not worth the effort.

**Comment by Cj-Malone** [comment]
Thanks

**Comment by TheUKHighStreet** [comment]
Thanks for basically rewriting it :) I am gradually getting the hang of it but this is very useful. Thanks. I had tried setting the time format to  "%H.%M" but somewhere had gone wrong and couldn't get it to work.

**Comment by Cj-Malone** [comment]
You're doing great, keep it up.

**Pull request merged**
