### PR TITLE
chemist_warehouse_au: fix spider

### PR DESCRIPTION
**Pull request by davidhicks**

### CODE REVIEW

**Comment by iandees** [comment]
Looks like it's blocking the robots.txt request.

**Comment by davidhicks** [comment]
Yes, a proxy is needed for this one.

Here's the stats:
```
2024-01-04 14:58:01 [scrapy.core.engine] INFO: Closing spider (finished)
2024-01-04 14:58:01 [locations.pipelines.duplicates] INFO: Dropped 0 duplicate items
2024-01-04 14:58:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Chemist Warehouse': 515,
 'atp/brand_wikidata/Q48782120': 515,
 'atp/category/amenity/pharmacy': 515,
 'atp/category/multiple': 515,
 'atp/cdn/cloudflare/response_count': 2,
 'atp/cdn/cloudflare/response_status_count/200': 2,
 'atp/field/country/from_spider_name': 515,
 'atp/field/email/invalid': 1,
 'atp/field/image/missing': 515,
 'atp/field/lat/missing': 515,
 'atp/field/lon/missing': 515,
 'atp/field/opening_hours/missing': 1,
 'atp/field/operator/missing': 515,
 'atp/field/operator_wikidata/missing': 515,
 'atp/field/twitter/missing': 515,
 'atp/field/website/missing': 515,
 'atp/nsi/perfect_match': 515,
 'downloader/request_bytes': 904,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 44333,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 3.023093,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 1, 4, 3, 58, 1, 774587),
 'httpcompression/response_bytes': 300342,
 'httpcompression/response_count': 2,
 'item_scraped_count': 515,
 'log_count/DEBUG': 528,
 'log_count/INFO': 9,
 'memusage/max': 147668992,
 'memusage/startup': 147668992,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 1, 4, 3, 57, 58, 751494)}
2024-01-04 14:58:01 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by davidhicks** [comment]
Scratch that, I found another API on their website that returns coordinates. I'll rewrite it.

**Comment by davidhicks** [comment]
Stats for revised spider (using alternative API endpoint):

```
2024-01-04 15:33:10 [scrapy.core.engine] INFO: Closing spider (finished)
2024-01-04 15:33:10 [locations.pipelines.duplicates] INFO: Dropped 0 duplicate items
2024-01-04 15:33:10 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Chemist Warehouse': 518,
 'atp/brand_wikidata/Q48782120': 518,
 'atp/category/amenity/pharmacy': 518,
 'atp/category/multiple': 518,
 'atp/cdn/cloudflare/response_count': 2,
 'atp/cdn/cloudflare/response_status_count/200': 2,
 'atp/field/country/from_spider_name': 518,
 'atp/field/email/invalid': 1,
 'atp/field/image/missing': 518,
 'atp/field/lat/missing': 1,
 'atp/field/lon/missing': 1,
 'atp/field/opening_hours/missing': 3,
 'atp/field/operator/missing': 518,
 'atp/field/operator_wikidata/missing': 518,
 'atp/field/phone/missing': 2,
 'atp/field/twitter/missing': 518,
 'atp/field/website/missing': 518,
 'atp/geometry/null_island': 1,
 'atp/nsi/perfect_match': 518,
 'downloader/request_bytes': 983,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 51210,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 3.328407,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 1, 4, 4, 33, 10, 736074),
 'httpcompression/response_bytes': 656393,
 'httpcompression/response_count': 2,
 'item_scraped_count': 518,
 'log_count/DEBUG': 531,
 'log_count/INFO': 9,
 'memusage/max': 147668992,
 'memusage/startup': 147668992,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 1, 4, 4, 33, 7, 407667)}
2024-01-04 15:33:10 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by iandees** [comment]
Nice find on the new API.

**Pull request merged**
