### PR TITLE
[hilton] revamp and fix the spider (8k locations)

### PR DESCRIPTION
**Pull request by panasonic-mafia**
- I use requests directly (I know it's not a scrapy way of doing things) as anything else doesn't work. It's only ~100 of lightweight requests, so it should be fine.

Stats:

```json
{
 "atp/brand/AutoCamp": 8,
 "atp/brand/Canopy": 45,
 "atp/brand/Conrad": 51,
 "atp/brand/Curio Collection": 186,
 "atp/brand/DoubleTree": 722,
 "atp/brand/Embassy Suites": 273,
 "atp/brand/Graduate": 34,
 "atp/brand/Hampton": 3110,
 "atp/brand/Hilton": 634,
 "atp/brand/Hilton Garden Inn": 1084,
 "atp/brand/Hilton Grand Vacations": 84,
 "atp/brand/Home2 Suites": 782,
 "atp/brand/Homewood Suites": 554,
 "atp/brand/LXR Hotels & Resorts": 14,
 "atp/brand/Motto": 8,
 "atp/brand/NoMad": 1,
 "atp/brand/Signia": 4,
 "atp/brand/Small Luxury Hotels of the World": 293,
 "atp/brand/Spark by Hilton": 104,
 "atp/brand/Tapestry Collection": 168,
 "atp/brand/Tempo": 4,
 "atp/brand/Tru": 293,
 "atp/brand/Waldorf Astoria": 38,
 "atp/brand_wikidata/Q109275422": 168,
 "atp/brand_wikidata/Q112144335": 4,
 "atp/brand_wikidata/Q112144350": 8,
 "atp/brand_wikidata/Q112144357": 4,
 "atp/brand_wikidata/Q1162859": 1084,
 "atp/brand_wikidata/Q13636126": 84,
 "atp/brand_wikidata/Q19903229": 186,
 "atp/brand_wikidata/Q24907770": 293,
 "atp/brand_wikidata/Q2504643": 722,
 "atp/brand_wikidata/Q30632909": 45,
 "atp/brand_wikidata/Q3239392": 38,
 "atp/brand_wikidata/Q5369524": 273,
 "atp/brand_wikidata/Q5646230": 3110,
 "atp/brand_wikidata/Q5887912": 782,
 "atp/brand_wikidata/Q5890701": 554,
 "atp/brand_wikidata/Q598884": 634,
 "atp/brand_wikidata/Q64605184": 14,
 "atp/brand_wikidata/Q855525": 51,
 "atp/brand_wikidata/Q85846030": 34,
 "atp/category/tourism/hotel": 8494,
 "atp/field/branch/missing": 8494,
 "atp/field/brand_wikidata/missing": 406,
 "atp/field/email/missing": 8494,
 "atp/field/image/missing": 8494,
 "atp/field/opening_hours/missing": 8494,
 "atp/field/operator/missing": 8494,
 "atp/field/operator_wikidata/missing": 8494,
 "atp/field/phone/invalid": 101,
 "atp/field/phone/missing": 37,
 "atp/field/postcode/missing": 8494,
 "atp/field/state/missing": 1996,
 "atp/field/twitter/missing": 8494,
 "atp/field/website/missing": 2,
 "atp/hilton/unknown_service/adjoiningRooms": 6137,
 "atp/hilton/unknown_service/adventureStays": 8,
 "atp/hilton/unknown_service/airportShuttle": 647,
 "atp/hilton/unknown_service/allInclusive": 16,
 "atp/hilton/unknown_service/beach": 258,
 "atp/hilton/unknown_service/boutique": 405,
 "atp/hilton/unknown_service/businessCenter": 6245,
 "atp/hilton/unknown_service/casino": 25,
 "atp/hilton/unknown_service/concierge": 1629,
 "atp/hilton/unknown_service/digitalKey": 6477,
 "atp/hilton/unknown_service/dining": 3647,
 "atp/hilton/unknown_service/evCharging": 2043,
 "atp/hilton/unknown_service/eveningReception": 255,
 "atp/hilton/unknown_service/executiveLounge": 398,
 "atp/hilton/unknown_service/fitnessCenter": 8206,
 "atp/hilton/unknown_service/freeBreakfast": 5113,
 "atp/hilton/unknown_service/freeParking": 5939,
 "atp/hilton/unknown_service/golf": 54,
 "atp/hilton/unknown_service/hotelResidence": 147,
 "atp/hilton/unknown_service/inRoomKitchen": 1334,
 "atp/hilton/unknown_service/luxury": 400,
 "atp/hilton/unknown_service/meetingRooms": 6100,
 "atp/hilton/unknown_service/newHotel": 324,
 "atp/hilton/unknown_service/outdoorPool": 3113,
 "atp/hilton/unknown_service/petsAllowed": 6495,
 "atp/hilton/unknown_service/petsNotAllowed": 1999,
 "atp/hilton/unknown_service/resort": 325,
 "atp/hilton/unknown_service/roomService": 2692,
 "atp/hilton/unknown_service/ski": 72,
 "atp/hilton/unknown_service/spa": 593,
 "atp/hilton/unknown_service/streamingTv": 1946,
 "atp/hilton/unknown_service/tennisCourt": 191,
 "atp/item_scraped_host_count/www.hilton.com": 8494,
 "atp/nsi/cc_match": 3110,
 "atp/nsi/perfect_match": 4978,
 "downloader/request_bytes": 3875,
 "downloader/request_count": 2,
 "downloader/request_method_count/POST": 2,
 "downloader/response_bytes": 6029,
 "downloader/response_count": 2,
 "downloader/response_status_count/200": 2,
 "elapsed_time_seconds": 55.262204,
 "feedexport/success_count/FileFeedStorage": 1,
 "finish_reason": "finished",
 "finish_time": "2024-09-15T18:52:56.566322+00:00",
 "httpcache/firsthand": 2,
 "httpcache/miss": 2,
 "httpcache/store": 2,
 "httpcompression/response_bytes": 8259,
 "httpcompression/response_count": 1,
 "item_scraped_count": 8494,
 "log_count/INFO": 10,
 "memusage/max": 223756288,
 "memusage/startup": 223756288,
 "request_depth_max": 1,
 "response_received_count": 2,
 "scheduler/dequeued": 2,
 "scheduler/dequeued/memory": 2,
 "scheduler/enqueued": 2,
 "scheduler/enqueued/memory": 2,
 "start_time": "2024-09-15T18:52:01.304118+00:00"
}
```

### CODE REVIEW

**Comment by panasonic-mafia** [comment]
Most probably it doesn't work on CI because cache or cookies from previous run should be cleaned.

**Comment by iandees** [comment]
Cookies and cache aren't saved between CI runs.

**Comment by panasonic-mafia** [comment]
Looks like it's a CND blocking thing, spider worked on my locals yesterday, but today it's not 😔

**Comment by panasonic-mafia** [comment]
Looks like spider worked with "US" proxy:

> 2024-09-24 09:57:40 [scrapy.core.engine] INFO: Closing spider (closespider_timeout)
2024-09-24 09:57:40 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 3 pages/min), scraped 2424 items (at 2424 items/min)

**Pull request merged**
