### PR TITLE
Add parsing of hasMap to LinkedDataParser

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix https://github.com/alltheplaces/alltheplaces/issues/10399

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
image

**Comment by Cj-Malone** [comment]
This will break coords on spiders like `ford_dealers_us`.

**Comment by Cj-Malone** [comment]
It needs parsing with chompjs because it's broken json. But the website also looks broken, for humans.
```json
{
  "@context": "http://schema.org",
  "@type": "AutoDealer",
  "address": {
    "@type": "PostalAddress",
    "addressLocality": "Canon City",
    "addressRegion": "CO",
    "postalCode": "81212",
    "streetAddress": "2501 Fremont Dr."
  },
  "name": "The Faricy Boys Ford",
  "openingHours": [
    "Mo 08:30-18:00",
    "Tu 08:30-18:00",
    "We 08:30-18:00",
    "Th 08:30-18:00",
    "Fr 08:30-18:00",
    "Sa 09:00-18:00"
  ],
  "telephone": "(719) 315-9895",
  "url": "https://www.ford.com/dealerships/dealer-details/co/canon-city/the-faricy-boys-ford/",
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": "38.448281",
    "longitude": "-105.210325"
  },
  "hasmap": "https://www.fordmapping.com/hybrid?encprms=Gqcc8Y7Fvdb3FWYk7D3XUwYa3LZ8leueXkMbUtHZ5sIZowcwQ4eUg4X8x05eaS6m"
}
```

**Comment by Cj-Malone** [comment]
stonegate_gb is another

**Comment by Cj-Malone** [comment]
I'm gonna make the executive decision to revert this before the weekly. Sorry to be the grumpy old man, I know you meant well, but this has broken more spiders that it's helped and that's only the ones we know about.

**Pull request merged**
