### PR TITLE
Dollar Tree

### LINKED ISSUE #204: Dollar Tree

### PR DESCRIPTION
**Pull request by whoissteven**
Fixes #204

### CODE REVIEW

**Comment by iandees** [comment]
The spider needs to be placed in the `locations/spiders/` directory for this to work.

**Comment by whoissteven** [comment]
Placed in locations/spiders/

**Comment by sledjama** [comment]
I believe you may need to pull changes, [see here](https://github.com/alltheplaces/alltheplaces/pull/225#issuecomment-348793352)

**Comment by whoissteven** [comment]
@sledjama thank you, I'll be giving that a try once I have steady internet soon. I've been experiencing a comcast outage all day.

**Comment by whoissteven** [comment]
Hmm.. From my own machine.
 'finish_reason': 'finished',
 'item_scraped_count': 6399,
I'm confused by the timeout.

**Comment by iandees** [comment]
The time out is okay. It's just a defense against long running spiders making the CI take forever.

**Pull request merged**
