### PR TITLE
Use proxy for CapitecBankZA

### LINKED ISSUE #9747: Capitec Bank 403
### Spider name

capitec_bank_za

### Log output

https://alltheplaces-data.openaddresses.io/ci/alltheplaces-fetch:fc22844d-a3d2-4898-a3e5-c303ff9c2bcd/capitec_bank_za/log.txt

### Backtrace (if applicable)

_No response_

### Example bad data or results

403 error on all requests, although it worked fine locally.

### Expected behaviour or results

_No response_

### Possible causes?

#9723 got merged despite the spider currently failing in the run, with 403 errors.

Does this need a proxy, or a different user agent? It worked fine for me locally, in ZA.

### PR DESCRIPTION
**Pull request by arrival-spring**
Attempt to fix #9747

### CODE REVIEW

**Comment by arrival-spring** [comment]
That appears to have worked

**Comment by iandees** [comment]
I'm reluctant to add proxy to a lat/lon scanner. Each requests costs some amount of money and it can get expensive quickly. Do you know how many requests it needs to do to get the full dataset?

**Comment by arrival-spring** [comment]
That's fair enough. With different number of requests we get different number of objects, per https://github.com/alltheplaces/alltheplaces/pull/9723 :

- 315km radius, 13 requests, 987 objects (199 branches)
- 158km radius, 36 requests, 1975 objects (359 branches)
- 94km radius, 78 requests, 2884 objects (520 branches)
- 79km radius, 98 requests, 3123 objects (567 branches)
- 48 km radius, 262 requests, 3483 objects (635 branches)
- 24km radius, 964 requests, not attempted

The spider is currently set to 48km radius, so 262 requests

**Comment by iandees** [comment]
Eh, low hundreds isn't too bad.

**Pull request merged**
