### PR TITLE
Improve the "global build" process

### PR DESCRIPTION
**Pull request by iandees**
This branch is trying to find a better way to run all of the spiders in the project with a queue and execution pool of some sort.

Ideas I've tried:
- [x] `multiprocessing.Pool` where each process runs a [`CrawlerProcess`](https://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerProcess). This failed because the `CrawlerProcess` starts up a Twisted reactor that can't be reused
- [x] `multiprocessing.dummy.Pool` where each thread runs a `subprocess.run()` with `scrapy crawl`
- [ ] `multiprocessing.Pool` where each process runs a `CrawlerProcess` and reuses it until all the spiders are done processing.
- [ ] (still looking for ideas)

### CODE REVIEW

**Comment by nvkelso** [comment]
A victim of our own success ;)

**Comment by iandees** [comment]
The second option doesn't work either. The `scrapy crawl` that gets run by `subprocess.run()` fails with this:

```
Traceback (most recent call last):
  File "/Users/iandees/.local/share/virtualenvs/alltheplaces--UjjKvf9/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Users/iandees/.local/share/virtualenvs/alltheplaces--UjjKvf9/lib/python3.6/site-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/Users/iandees/.local/share/virtualenvs/alltheplaces--UjjKvf9/lib/python3.6/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/Users/iandees/.local/share/virtualenvs/alltheplaces--UjjKvf9/lib/python3.6/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
    module = import_module(module)
  File "/Users/iandees/.local/share/virtualenvs/alltheplaces--UjjKvf9/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'locations'
```

Even though it should have the same PYTHONPATH and whatnot as the process that's running it. The same shell runs `scrapy crawl` just fine.

**Comment by iandees** [comment]
Asked a StackOverflow question here: https://stackoverflow.com/questions/48088582/running-dozens-of-scrapy-spiders-in-a-controlled-manner

**Comment by iandees** [comment]
I ended up going with `xargs` and dealing with it in shell. We'll see how this works.

**Pull request merged**
