### PR TITLE
[Grandvision] Add Spider covering Pearle, GrandOptical and other brands for EU countries (2748 locations)

### PR DESCRIPTION
**Pull request by ehsan-firdaus**
Helpful Reference: https://en.wikipedia.org/wiki/Pearle_Vision
image

```
{'atp/brand/Apollo-Optik': 877,
 'atp/brand/GrandOptical': 317,
 'atp/brand/Optica2000': 101,
 'atp/brand/Pearle': 665,
 'atp/brand/Synoptik': 244,
 'atp/brand/Vision Express': 544,
 'atp/brand_wikidata/Q10687541': 244,
 'atp/brand_wikidata/Q15812731': 101,
 'atp/brand_wikidata/Q2231148': 665,
 'atp/brand_wikidata/Q3113677': 317,
 'atp/brand_wikidata/Q618940': 877,
 'atp/brand_wikidata/Q7936150': 544,
 'atp/category/shop/optician': 2748,
 'atp/cdn/cloudflare/response_count': 3185,
 'atp/cdn/cloudflare/response_status_count/200': 3152,
 'atp/cdn/cloudflare/response_status_count/404': 33,
 'atp/field/email/missing': 2,
 'atp/field/image/dropped': 188,
 'atp/field/image/missing': 356,
 'atp/field/opening_hours/missing': 13,
 'atp/field/operator/missing': 2748,
 'atp/field/operator_wikidata/missing': 2748,
 'atp/field/phone/invalid': 2,
 'atp/field/state/missing': 2735,
 'atp/field/twitter/missing': 2748,
 'atp/item_scraped_host_count/www.apollo.de': 877,
 'atp/item_scraped_host_count/www.grandoptical.com': 209,
 'atp/item_scraped_host_count/www.grandoptical.nl': 86,
 'atp/item_scraped_host_count/www.grandoptical.pt': 9,
 'atp/item_scraped_host_count/www.grandoptical.sk': 13,
 'atp/item_scraped_host_count/www.optica2000.com': 101,
 'atp/item_scraped_host_count/www.pearle.at': 128,
 'atp/item_scraped_host_count/www.pearle.be': 177,
 'atp/item_scraped_host_count/www.pearle.nl': 360,
 'atp/item_scraped_host_count/www.synoptik.dk': 101,
 'atp/item_scraped_host_count/www.synoptik.se': 143,
 'atp/item_scraped_host_count/www.visionexpress.com': 533,
 'atp/item_scraped_host_count/www.visionexpress.ie': 11,
 'atp/nsi/brand_missing': 101,
 'atp/nsi/cc_match': 665,
 'atp/nsi/perfect_match': 1982,
 'downloader/request_bytes': 1233014,
 'downloader/request_count': 3209,
 'downloader/request_method_count/GET': 3209,
 'downloader/response_bytes': 239656332,
 'downloader/response_count': 3209,
 'downloader/response_status_count/200': 3167,
 'downloader/response_status_count/301': 9,
 'downloader/response_status_count/404': 33,
 'dupefilter/filtered': 598,
 'elapsed_time_seconds': 122.798029,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 8, 7, 20, 39, 35, 521107, tzinfo=datetime.timezone.utc),
 'httpcache/hit': 3209,
 'httpcompression/response_bytes': 1308051453,
 'httpcompression/response_count': 3200,
 'item_scraped_count': 2748,
 'log_count/DEBUG': 5970,
 'log_count/INFO': 12,
 'log_count/WARNING': 1,
 'request_depth_max': 2,
 'response_received_count': 3200,
 'robotstxt/request_count': 13,
 'robotstxt/response_count': 13,
 'robotstxt/response_status_count/200': 13,
 'scheduler/dequeued': 3196,
 'scheduler/dequeued/memory': 3196,
 'scheduler/enqueued': 3196,
 'scheduler/enqueued/memory': 3196,
 'start_time': datetime.datetime(2024, 8, 7, 20, 37, 32, 723078, tzinfo=datetime.timezone.utc)}
```

### CODE REVIEW

**Comment by ehsan-firdaus** [comment]
[Pearle Studio in NL is now GrandOptical](https://fonkmagazine.nl/artikelen/marketing/pearle-studio-winkels-gaan-verder-als-grand-optical-65596.html#sluiten) 
image

Hence, [Pearle Studio NL](https://github.com/alltheplaces/alltheplaces/blob/501abc283686ea3b4b748616eb07f8d1b8667de9/locations/spiders/pearle_studio_nl.py) Spider is deleted, locations covered as `GrandOptical` by this `Grandvision` Spider.

**Comment by CloCkWeRX** [comment]
Apollo-Optik

German optician and eyewear retail chain

### Wikidata ID

Q618940
https://www.wikidata.org/wiki/Q618940
https://www.wikidata.org/wiki/Special:EntityData/Q618940.json

### Store finder url(s)

Official Url(s): https://www.apollo.de/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q618940 https://www.apollo.de/`
```
```

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/discussions/7468 suggests there are one or two other grandvision sub brands

**Comment by ehsan-firdaus** [comment]
> Apollo-Optik
> 
> German optician and eyewear retail chain
> 
> ### Wikidata ID
> Q618940 https://www.wikidata.org/wiki/Q618940 https://www.wikidata.org/wiki/Special:EntityData/Q618940.json
> 
> ### Store finder url(s)
> Official Url(s): https://www.apollo.de/
> 
> * [x]  I have run the below and if anything in generated, added it.
> * [x]  I have manually checked for a storefinder
> * [x]  This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
>   `pipenv run scrapy sf --brand-wikidata=Q618940 https://www.apollo.de/`

@CloCkWeRX Already added this brand, this beside other brands is part of GrandVision.
Ref: https://www.bloomreach.com/en/case-studies/grandvision-case-study
image

**Comment by ehsan-firdaus** [comment]
One brand is [Eye Wish](https://www.eyewish.com/nl-nl/over-ons) whose owner changes from `GrandVision` to `MPG Eyewear`. Hence, not adding thinking to add here.
image

**Comment by ehsan-firdaus** [comment]
Fresh stats:
```
{'atp/brand/Apollo-Optik': 877,
 'atp/brand/GrandOptical': 317,
 'atp/brand/Optica2000': 101,
 'atp/brand/Pearle': 665,
 'atp/brand/Synoptik': 244,
 'atp/brand/Vision Express': 544,
 'atp/brand_wikidata/Q10687541': 244,
 'atp/brand_wikidata/Q15812731': 101,
 'atp/brand_wikidata/Q2231148': 665,
 'atp/brand_wikidata/Q3113677': 317,
 'atp/brand_wikidata/Q618940': 877,
 'atp/brand_wikidata/Q7936150': 544,
 'atp/category/shop/optician': 2748,
 'atp/cdn/cloudflare/response_count': 3185,
 'atp/cdn/cloudflare/response_status_count/200': 3152,
 'atp/cdn/cloudflare/response_status_count/404': 33,
 'atp/field/email/missing': 2,
 'atp/field/image/dropped': 188,
 'atp/field/image/missing': 356,
 'atp/field/opening_hours/missing': 13,
 'atp/field/operator/missing': 2748,
 'atp/field/operator_wikidata/missing': 2748,
 'atp/field/phone/invalid': 2,
 'atp/field/state/missing': 2735,
 'atp/field/twitter/missing': 2748,
 'atp/item_scraped_host_count/www.apollo.de': 877,
 'atp/item_scraped_host_count/www.grandoptical.com': 209,
 'atp/item_scraped_host_count/www.grandoptical.nl': 86,
 'atp/item_scraped_host_count/www.grandoptical.pt': 9,
 'atp/item_scraped_host_count/www.grandoptical.sk': 13,
 'atp/item_scraped_host_count/www.optica2000.com': 101,
 'atp/item_scraped_host_count/www.pearle.at': 128,
 'atp/item_scraped_host_count/www.pearle.be': 177,
 'atp/item_scraped_host_count/www.pearle.nl': 360,
 'atp/item_scraped_host_count/www.synoptik.dk': 101,
 'atp/item_scraped_host_count/www.synoptik.se': 143,
 'atp/item_scraped_host_count/www.visionexpress.com': 533,
 'atp/item_scraped_host_count/www.visionexpress.ie': 11,
 'atp/nsi/brand_missing': 101,
 'atp/nsi/cc_match': 665,
 'atp/nsi/perfect_match': 1982,
 'downloader/request_bytes': 1233014,
 'downloader/request_count': 3209,
 'downloader/request_method_count/GET': 3209,
 'downloader/response_bytes': 239656332,
 'downloader/response_count': 3209,
 'downloader/response_status_count/200': 3167,
 'downloader/response_status_count/301': 9,
 'downloader/response_status_count/404': 33,
 'dupefilter/filtered': 598,
 'elapsed_time_seconds': 122.798029,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 8, 7, 20, 39, 35, 521107, tzinfo=datetime.timezone.utc),
 'httpcache/hit': 3209,
 'httpcompression/response_bytes': 1308051453,
 'httpcompression/response_count': 3200,
 'item_scraped_count': 2748,
 'log_count/DEBUG': 5970,
 'log_count/INFO': 12,
 'log_count/WARNING': 1,
 'request_depth_max': 2,
 'response_received_count': 3200,
 'robotstxt/request_count': 13,
 'robotstxt/response_count': 13,
 'robotstxt/response_status_count/200': 13,
 'scheduler/dequeued': 3196,
 'scheduler/dequeued/memory': 3196,
 'scheduler/enqueued': 3196,
 'scheduler/enqueued/memory': 3196,
 'start_time': datetime.datetime(2024, 8, 7, 20, 37, 32, 723078, tzinfo=datetime.timezone.utc)}
```

**Pull request merged**
