### PR TITLE
western_union: fix spider to use correct geographic search

### PR DESCRIPTION
**Pull request by davidhicks**
The Western Union GraphQL endpoint does use a 350km radius from each supplied search coordinate to find locations to return (over multiple pages of results). The previous attempt to fix this spider incorrectly assumed a 'country' parameter to the GraphQL search function was used instead of a radius being applied.

To achieve this search across the entire surface of the Earth, a new searchable points file is provided, along with documentation for how this searchable points file was created, and how similar could be created in the future for different search radiuses.

### CODE REVIEW

**Comment by davidhicks** [comment]
There's a small number of erroneous coordinates that will need filtering from the sample results stated above. For example, two coordinates near the North pole and one in the middle of an ocean. Can I come back to address this after this spider completes a weekly run so we have all the data needed to see whether any of these erroneous coordinates can be quickly and efficiently filtered out (e.g. ignore all coordinates near the North pole if they're all wrong).

**Comment by davidhicks** [comment]
@iandees Is this waiting for some further resolution of issue #5495 for how searchable points are generated?

**Comment by iandees** [comment]
I was still trying to understand the tools you used to generate the CSV and it sounded like you needed to filter some coordinates out of the file? Maybe you meant coordinates in the Western Union data.

In the future, it would be helpful to make separate PRs for different chunks of work.

**Comment by davidhicks** [comment]
There are a few bad coordinates I've seen in the Western Union data, somewhat like the problem I fixed recently for moneygram per pull request #5515. These bad coordinates likely existed in the previous CrawlSpider version of western_union too. I just haven't had a chance to do a full run of the western_union spider to then figure out how many coordinates might be bad, and how best to remove those coordinates (if it's practical to do so).

The reason for putting the new searchable points generation method within this pull request was so that it was committed along with the first consumer of the method (western_union), allowing the effectiveness to be verified. I was planning to wait for issue #5495 discussion to conclude before extending this new searchable points generation method to be used country-by-country. And then, my thought was if we commit new searchable points, that a few spiders be switched over to the new method at the same time so that the effectiveness can be verified (new location count = old location count). Or is it best to keep separate PRs for the change to searchable points, and a separate PR for each spider switched to the new method?

**Comment by iandees** [comment]
Thanks for the explanation. Generally I would prefer that new features (like the new searchable points) get added as a separate PR so that they're easier to find and to encapsulate discussion about them.

**Comment by davidhicks** [comment]
Thanks I'll make sure I do that for planned searchable points generation per-country as proposed in #5495

**Pull request merged**
