### PR TITLE
avoid conflict with OSM relation type tag

### PR DESCRIPTION
**Pull request by matkoniecz**

### CODE REVIEW

**Comment by matkoniecz** [comment]
note: I see no object_type in @scraperbot output. Maybe something went wrong?

**Comment by CloCkWeRX** [comment]
I wonder if going a bit wider than this one, it's worth adding a validation in to indicate that's reserved so we find any similar bugs easily going forward

**Comment by matkoniecz** [comment]
I definitely like such idea.

**Comment by iandees** [comment]
Yea, it might be a good idea to flag in CI...

**Pull request merged**
