### PR TITLE
Beer Mapping Project

### LINKED ISSUE #274: The Beer Mapping Project
https://beermapping.com/

### PR DESCRIPTION
**Pull request by SelfnessAid**
Fix #274

### CODE REVIEW

**Comment by SelfnessAid** [comment]
I am not sure why this is crawling 0 items.
I got 15096 items on my side.
screen shot 2017-12-08 at 12 40 10 pm
@iandees could you possibly look at this?
I can see urls are blocked in [Log](https://s3.amazonaws.com/placescraper-results/results/beermapping/2017-12-08-17-37-08/log.txt)

**Comment by iandees** [comment]
You're probably breaking their server with too many requests. Slow things down with a `download_delay` or come up with a more efficient way of making requests.

**Comment by SelfnessAid** [comment]
okay, got you.

**Comment by nvkelso** [comment]
Wow!

**Pull request merged**
