### PR TITLE
Add Słoneczko (PL)

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix https://github.com/alltheplaces/alltheplaces/issues/7493
{'atp/brand/Słoneczko': 50,
 'atp/brand_wikidata/Q113230439': 50,
 'atp/category/shop/convenience': 50,
 'atp/field/country/from_spider_name': 50,
 'atp/field/email/missing': 50,
 'atp/field/image/missing': 50,
 'atp/field/opening_hours/missing': 50,
 'atp/field/operator/missing': 50,
 'atp/field/operator_wikidata/missing': 50,
 'atp/field/phone/missing': 50,
 'atp/field/twitter/missing': 50,
 'atp/field/website/missing': 50,
 'atp/nsi/perfect_match': 50,
 'downloader/request_bytes': 677,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 3315,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 5.772457,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 2, 26, 11, 4, 23, 471798, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 24543,
 'httpcompression/response_count': 2,
 'item_scraped_count': 50,
 'log_count/DEBUG': 63,
 'log_count/INFO': 9,
 'memusage/max': 150335488,
 'memusage/startup': 150335488,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 2, 26, 11, 4, 17, 699341, tzinfo=datetime.timezone.utc)}
2024-02-26 11:04:23 [scrapy.core.engine] INFO: Spider closed (finished)

### CODE REVIEW

**Review by davidhicks — CHANGES_REQUESTED** [review]
A catch with `WPStoreLocatorSpider` is that there is often a hardcoded (not remotely configurable) limit to how many locations are returned at once. In this case, a hardcoded limit of 50 exists, as confirmed by 64 stores being listed in one region of Poland alone.

This spider will thus need to use a searchable points file for Poland to get all locations across the country. Hopefully there aren't more than 50 stores in close proximity so that a large radius could be used.

I can help by generating a suitable pl_centroids_iseadgg_xxxkm_radius.csv/.meta pair of files that hopefully allows capturing of all store locations. Would this help rather than having to follow the instructions in searchable_points/earth_centroids_iseadgg.md yourself?

**Comment by sterojos** [comment]
@davidhicks, what do you think about moving the Markdown files from `searchable_points` to the `docs` section? At first, I didn't notice them in the folder with the CSVs.

**Comment by CloCkWeRX** [comment]
> I can help by generating a suitable pl_centroids_iseadgg_xxxkm_radius.csv/.meta pair of files that hopefully allows capturing of all store locations. 

I'll take the help if our local environment is setup for this.
Would it be worth generating these points for every country at some reasonable density?

**Comment by matkoniecz** [comment]
@davidhicks Are this serach points generated for Poland by now? (I can try figuring out how to do this, but maybe this is done now...)

> This spider will thus need to use a searchable points file for Poland to get all locations across the country. Hopefully there aren't more than 50 stores in close proximity so that a large radius could be used.

will spider throw an error if it will report 50 shops in one search?

**Comment by CloCkWeRX** [comment]
Feel free to take over this PR, I'm struggling to get the time at the moment

**Comment by davidhicks** [comment]
I've got it working with a geographic radius search (25km radius is what I've tried as 50km is too large and results in some locations being lost). However I am amidst a big improvement to `OpeningHours.add_ranges_from_string` that is needed to parse the opening hours of this particular WPStoreLocator spider. I'll have this spider fixed and submitted again once that opening hours improvement is in place.

**Comment by CloCkWeRX** [comment]
Hmm. 34 locations is... less than 50. Let's hope thats a timeout.

**Comment by CloCkWeRX** [comment]
@iandees this one is potentially good to go. I haven't run it for longer than CI though.

**Pull request merged**
