### PR TITLE
Add Centra spiders

### PR DESCRIPTION
**Pull request by Cj-Malone**
centra_ie
```python
{'atp/brand/Centra': 473,
 'atp/brand_wikidata/Q747678': 473,
 'atp/category/shop/convenience': 473,
 'atp/field/city/missing': 473,
 'atp/field/country/from_spider_name': 473,
 'atp/field/email/missing': 473,
 'atp/field/image/missing': 473,
 'atp/field/opening_hours/missing': 473,
 'atp/field/phone/invalid': 4,
 'atp/field/phone/missing': 3,
 'atp/field/postcode/missing': 3,
 'atp/field/state/missing': 473,
 'atp/field/street_address/missing': 473,
 'atp/field/twitter/missing': 473,
 'atp/field/website/missing': 473,
 'atp/nsi/category_match': 473,
 'downloader/request_bytes': 327,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 60471,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 1.757478,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 2, 2, 19, 22, 30, 510082),
 'httpcache/hit': 1,
 'httpcompression/response_bytes': 911207,
 'httpcompression/response_count': 1,
 'item_scraped_count': 473,
 'log_count/DEBUG': 484,
 'log_count/INFO': 9,
 'memusage/max': 111665152,
 'memusage/startup': 111665152,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2023, 2, 2, 19, 22, 28, 752604)}
```

centra_gb
```python
{'atp/brand/Centra': 80,
 'atp/brand_wikidata/Q747678': 80,
 'atp/category/shop/convenience': 80,
 'atp/field/country/from_spider_name': 80,
 'atp/field/email/missing': 75,
 'atp/field/image/missing': 80,
 'atp/field/lat/missing': 2,
 'atp/field/lon/missing': 2,
 'atp/field/opening_hours/missing': 80,
 'atp/field/phone/invalid': 1,
 'atp/field/phone/missing': 10,
 'atp/field/postcode/missing': 6,
 'atp/field/state/missing': 12,
 'atp/field/twitter/missing': 80,
 'atp/field/website/invalid': 3,
 'atp/nsi/category_match': 80,
 'downloader/request_bytes': 656,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 6205,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 0.950685,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 2, 2, 19, 22, 7, 247516),
 'httpcache/hit': 2,
 'httpcompression/response_bytes': 32145,
 'httpcompression/response_count': 1,
 'item_scraped_count': 80,
 'log_count/DEBUG': 88,
 'log_count/INFO': 9,
 'memusage/max': 111775744,
 'memusage/startup': 111775744,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2023, 2, 2, 19, 22, 6, 296831)}
```

https://github.com/osmlab/name-suggestion-index/pull/7745

### CODE REVIEW

**Comment by iandees** [comment]
I wonder what would be useful from the stats output to include automatically in the github-actions report. Maybe missing "important" fields?

**Comment by Cj-Malone** [comment]
I guess the "error" ones are the important ones to have, the actual error count but also if there was a ton of duplicates, or the invalid fields.

But the ultimate answer, is which ever ones you look at. I can stop posting them if you don't find them useful.

**Comment by iandees** [comment]
Only keep posting them if it's easy for you to do. I'll think about a better way to show more detail from the GH action.

**Comment by Cj-Malone** [comment]
These quick api spiders, it's no problem, for the longer crawling spiders I'll stop.

**Pull request merged**
