### PR TITLE
Add a Dutch Bros spider.

### PR DESCRIPTION
**Pull request by youngpm**
Delicious coffee stand addition.

### CODE REVIEW

**Comment by iandees** [comment]
Looks good! https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/2953382540/dutchbros/output.geojson

**Comment by iandees** [comment]
I'll merge this and CI will auto-fix the Black lint error.

**Comment by youngpm** [comment]
These are fun to do!

**Comment by iandees** [comment]
Yes! Wait til you find one that supports Linked Data + sitemap. Then it can be pretty boiler-plate: https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/99centsonly.py

**Pull request merged**
