### PR TITLE
potbelly sandwich

### LINKED ISSUE #124: Potbelly Sandwich Shop
http://www.potbelly.com/Shops/ShopLocator.aspx

### PR DESCRIPTION
**Pull request by sweetdream0729**
Fixes #124.

@iandees , I have taken "pickup_menu_url" for "website" field.
But there is also "facebook_url".
I am not sure if it is correct to pull "pickup_menu_url" for "website".
Thanks.

### CODE REVIEW

**Comment by iandees** [comment]
Let's use the Facebook URL for now instead of the menu URL.

It also looks like the server is rejecting the spider's request for some reason. Does it work for you when you run it locally?

**Comment by sweetdream0729** [comment]
yes, but not now.
let me check more.

**Comment by iandees** [comment]
There are many more stores missing from the output. It looks like the the full list of locations can be found in `https://www.potbelly.com/dist/main.js` if you search for `staticLocations=[`. The trick is to find the end of the array.

**Comment by sweetdream0729** [comment]
ok, let me check more.
Thanks.

**Comment by sweetdream0729** [comment]
wow~, contents of staticLocations=[ is not JSON format. 
Properties and values have not double quotes:(

**Comment by sweetdream0729** [comment]
@iandees, added demjson package in order to convert Javascript object to python dictionary.
Please have a look it and let me know any issues.
Thanks.

**Comment by iandees** [comment]
@sweetdream0729 demjson worked but it was taking a very long time, so I added a couple regex runs to make the JSON correct and parse it with the normal JSON parser.

**Pull request merged**
