### PR TITLE
try better phrasing

### PR DESCRIPTION
**Pull request by matkoniecz**
disclaimer: I am not a native speaker

but it seems much better to me, repeated forward sounded a bit weird

(I hope that it actually improves thing, sorry if it does not)

### CODE REVIEW

**Comment by matkoniecz** [comment]
BTW

> The ATP tooling described here and on related pages can go a long way to giving you confidence in your end spider before writing any code!

in https://github.com/alltheplaces/alltheplaces/blob/master/docs/STRUCTURED_DATA.md also seems weird (why I would have confidence in not-yet-existing spider?) but I am less sure hidden and have no obvious fixes

**Comment by CloCkWeRX** [comment]
You are right, it's a bit weirdly phrased.

Native speakers would probably rewrite it as "... A further step" or something to avoid the double use of forward, if they focused on it.

But then it depends how far you go on the "vernacular Australia English" (bloody hell we've gotten a long way, and quick smart too, but that's job's not over yet! So buckle up and point your looking gear at this...) vs other dialects.

Note: this is why no one lets me near the en_au.yml i18n files at work though.

**Comment by matkoniecz** [comment]
Looking at what I ended writing it may be also (over)reaction to how often "forward" appears in various corporate/bureaucracy babble (as seen from non-English language country).

**Comment by iandees** [comment]
Thanks for calling these out. I did some more extensive copy editing on this file to make it clearer.

**Pull request merged**
