### PR TITLE
Lee's Famous Recipe

### LINKED ISSUE #95: Lee's Famous Recipe
http://www.leesfamousrecipe.com/locations/all

### PR DESCRIPTION
**Pull request by AnthoneyKalasho**
Fixes #95

### CODE REVIEW

**Comment by AnthoneyKalasho** [comment]
Just realized I never added hours, not complete yet.

**Comment by iandees** [comment]
@AnthoneyKalasho can you finish this off please?

**Comment by AnthoneyKalasho** [comment]
@iandees I'll get it done tonight sorry for the delay

**Comment by AnthoneyKalasho** [comment]
@iandees Should be good to go now

**Pull request merged**
