### PR TITLE
Add Zyte to Citgo

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by iandees** [comment]
Looks like citgo changed quite a bit since we last successfully got data.

**Comment by davidhicks** [comment]
Request format for obtaining locations:

`curl 'https://www.citgo.com/api/locations/search' -X POST -H 'Accept: application/json' -H 'Content-Type: application/json; charset=utf-8' --data-raw '{"token":"nTDQeMMivJH8KZciLxMoL7voPDE2YJ2ZbXH6MJ0U","location":"Newark, NJ, USA"}'`

Sometimes an error is returned:

`"No CITGO stations located within 100 miles of this address."`

It doesn't look like a simple job to find cities/towns that are ideally 200 miles (but no greater) apart from each other, whilst also ensuring full coverage of the USA landmass.

**Comment by iandees** [comment]
We're using `requires_proxy` to enable Zyte now.

**Comment by davidhicks** [comment]
I think this may have been closed by accident?

**Pull request closed without merging**
