### PR TITLE
Add GLSC Gazetteer Spider

### LINKED ISSUE #5499: Guyana Gazetteer
### Brand name

Guyana

### Wikidata ID

_No response_

### Store finder url(s)

https://gazetteer.glsc.gov.gy/gazetteer/

### PR DESCRIPTION
**Pull request by Cj-Malone**
Fixes #5499

@justinelliotmeyers we try to be as close to OSM categories as possible, feel free to improve the mapping if you can.

### CODE REVIEW

**Comment by iandees** [comment]
There's a lot of data of questionable quality in there, too...

**Comment by Cj-Malone** [comment]
I was originally annoyed by there being only points, even for features like rivers. But I the lack of data is quite understandable, and so I can't blame them for that. Honestly, I think any nation without an established mapping agency by now should just embrace OSM, but that's not my decision to make.

I have however just found there [category](https://gazetteer.glsc.gov.gy/index.php/explanatory-notes/#103) definitions, and I would definitely blame them for having both `Fall` and `Falls` in the data when only the first is in the spec.

**Comment by iandees** [comment]
I'm not happy with the quality of the data in here, so I'm going to close this out.

I think the GeoJSON produced by the CI here would be useful for someone who might want to add this to OSM, though.

**Comment by justinelliotmeyers** [comment]
Agree and thank you all for looking into it 
 Appreciate your help

**Comment by iandees** [comment]
Thanks for finding the data, Justin. Keep it up!

**Pull request closed without merging**
