### PR TITLE
Long John Silver's

### PR DESCRIPTION
**Pull request by MagnetonIO**
For #49

### CODE REVIEW

**Comment by iandees** [comment]
There are more than 29 Long John Silvers. Keeping this open until we find an efficient way to do searches across large areas.

**Comment by iandees** [comment]
@MagnetonIO are you able to get this spider out any farther than 30 locations?

**Comment by MagnetonIO** [comment]
I will check again.

**Comment by MagnetonIO** [comment]
Checking now. I will update.

**Comment by MagnetonIO** [comment]
@iandees The spider module is searching with zipcode 7601.
How do you know the result is more than 29?

**Comment by iandees** [comment]
If you look at their website it has more places around the country. I'll merge this in and mark the ticket with the "requires zipcode search" so we can figure it out later.

**Comment by MagnetonIO** [comment]
I'm updating module with increased radius.

**Pull request merged**
