### PR TITLE
[WesternUnion] Remove top level tag

### LINKED ISSUE #5889: @spider=western_union in Poland list `amenity=money_transfer` POIs not actually existing as separate objects
very similar to #5881

It would be better to drop main tag over showing it like this. And in this case it seems dubious to me is it mappable as all on https://www.openstreetmap.org/node/5873034793 bank note.

https://www.alltheplaces.xyz/map/#16.47/50.076332/20.032325

https://location.westernunion.com/pl/malopolskie/krakow/e6d7165e8f86df94dacd8de6f1bfc780

I can visit that place and check in which form Western Union appears there.

### PR DESCRIPTION
**Pull request by Cj-Malone**
Fixes #5889

### CODE REVIEW

**Comment by Cj-Malone** [comment]
@matkoniecz CI (or me) don't have permission to edit the fork, please could you remove the Categories import on line 7.

**Comment by matkoniecz** [comment]
> don't have permission to edit the fork 

how can I give it?

**Comment by matkoniecz** [comment]
> please could you remove the Categories import on line 7.

done

**Comment by matkoniecz** [comment]
is there some way to see why linter is unhappy? Or maybe this PR can be closed and I will open a new one?

**Pull request closed without merging**
