### PR TITLE
add spider for dish

### PR DESCRIPTION
**Pull request by LadyLatitude**
closes issue #1741

### CODE REVIEW

**Comment by iandees** [comment]
Looks like there's one page that's erroring with a stack trace like this:

```
2021-04-13 18:35:25 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dish.com/find-retailer/getretailershandler.ashx?Zip=96910&Miles=1000> (referer: https://www.dish.com/find-retailer/)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/home/runner/work/alltheplaces/alltheplaces/locations/spiders/dish.py", line 34, in parse_store
    store_data = json.loads(response.body_as_unicode())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

[log](https://placescraper-results.s3.amazonaws.com/ci/745747994/dish/log.txt)

**Comment by LadyLatitude** [comment]
Okay, I'll fix.

**Comment by LadyLatitude** [comment]
Fixed spider, should be good to merge now.

**Comment by iandees** [comment]
Great, thanks!

**Pull request merged**
