### PR TITLE
Initial commit of Marshally Spider, hours need to be parsed to OSM.

### LINKED ISSUE #207: Marshall's

### PR DESCRIPTION
**Pull request by kristinepetrosyan**
Closes #207

### CODE REVIEW

**Comment by mendoncaangelo** [comment]
@iandees https://s3.amazonaws.com/placescraper-results/runs/1512015627.html why does it say 0 results? I see the log showing more than 1 value.

**Comment by iandees** [comment]
I'm not sure why the count is off, but you're only getting one result because the `ref` property is the same for every result. It dedupes on the value of the `ref` property.

**Comment by kristinepetrosyan** [comment]
@iandees I have added OSM hours format for Marshalls. Please review the code and let me know.

**Comment by iandees** [comment]
Ack, I didn't mean to merge this one.

@kristinepetrosyan, can you please take a look at the other spiders to see what the output looks like? The output on this spider doesn't match the desired output.

**Comment by kristinepetrosyan** [comment]
@iandees this spider has this output 
image

Applebees has this format. Do you want me to remove some of the additional fields? I thought I would leave them in there so that we have more data.

**Comment by iandees** [comment]
Yes, please standardize the attributes and remove the extras. Things like Region, RegionID, Facilities, Directions, Comment, Departments, NewStore, etc. aren't really useful to us.

**Comment by kristinepetrosyan** [comment]
@iandees will do. Will keep this in mind for the other spiders. Thanks once again for reviewing. I will push to the same branch.

**Comment by iandees** [comment]
Thanks for pointing it out – I am making a change in #222 so that the expected properties are more obvious.

**Pull request merged**
