### PR TITLE
Qdoba

### PR DESCRIPTION
**Pull request by wessport**
Repairs Qdoba spider which was only returning results for NY. Now scrapes all 732 US and CA locations.

### CODE REVIEW

**Comment by iandees** [comment]
Do you think you could rebase this branch from master so that there's not a ton of other commits on it?

**Comment by wessport** [comment]
Yeah sure thing. Let me see what I can do.

**Comment by wessport** [comment]
@iandees I think I finally figured it out. Heck of a way to kick off a Friday night 😄! Let me know what you think!

**Comment by iandees** [comment]
Woo git party! Looks good, thanks.

**Pull request merged**
