### PR TITLE
Add Reece brands (AU/NZ) (561 stores)

### PR DESCRIPTION
**Pull request by davidhicks**

### CODE REVIEW

**Comment by iandees** [comment]
Can you apply a category? Maybe `doityourself`?

**Comment by davidhicks** [comment]
I have to catch up on recent additions needing to be pushed to NSI.

Is it OK for me to add to https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/shop/trade.json rather than assign a category within ATP?

**Comment by iandees** [comment]
Yep, that's a good way of doing it (so OSM folks would get the brand too). @Cj-Malone has made changes like this before, too, so it might be worth looking at some of his pull requests there.

**Comment by Cj-Malone** [comment]
I'd always prefer us to put categories in NSI, obviously OSM also benefits immediately, but we also benefit in the long term if it's decided to change the category. Just like DIY vs Trade above.

I'm a maintainer of NSI now so I'll review and merge it when it's ready. NSI has lots of docs, but essentially you're just adding a name, locations and the tags [eg](https://github.com/osmlab/name-suggestion-index/commit/08b70de1bc29314046f5bf824241d43e572ecd07).

**Comment by davidhicks** [comment]
I've added some changes to manually add categories for different Reece branded stores.

**Pull request merged**
