### PR TITLE
[DominosPizza GB] Improve regex

### PR DESCRIPTION
**Pull request by TheUKHighStreet**

### CODE REVIEW

**Comment by TheUKHighStreet** [comment]
I don't really understand yet how this is creating the stores without a yield. 
However, there is a problem with the original regex as it is missing some stores which have this structure with an extra /:
 <loc>https://www.dominos.co.uk/pizza-near-me/welling/9/9b-upper-wickham-lane</loc>

**Comment by arrival-spring** [comment]
There is no yield because it is using StructuredDataSpider and the default methods for that do not need overriding here, assuming all data is being returned as expected.

**Comment by TheUKHighStreet** [comment]
Thanks - I guessed it was something like that. 
I'm not sure why it is timing out but I assume it doesn't have anything to do with the regex. There seem to be 28 stores which were being missed with the original file.

**Comment by arrival-spring** [comment]
I had the same query about timeout when I started contributing, maybe we should put it in the docs somewhere. Basically though the spiders are only given a minute to run in the PR tests, so timeout is fine for a status here if it runs ok locally.

**Comment by TheUKHighStreet** [comment]
Thanks very much, good to know.

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/blob/5dfc5bee0ab432e46f9b4a67b86bd95a53904d57/locations/structured_data_spider.py#L301 if you are curious about where it's working from - sitemap > parse_sd > yield from post process item.

**Comment by TheUKHighStreet** [comment]
Thanks very much.

**Pull request merged**
