### PR TITLE
[Gucci] Fix spider

### PR DESCRIPTION
**Pull request by ckpiper**
Anybody have any ideas on what the issue may be with my code? The get request works in postman, but does not want to work in scrapy. I was hoping if this works then I could fix the regular gucci spider by grabbing bboxs of countries and using this.

### CODE REVIEW

**Comment by Cj-Malone** [comment]
It worked locally...
```python
{'atp/brand/Gucci': 675,
 'atp/brand_wikidata/Q178516': 675,
 'atp/category/shop/clothes': 675,
 'atp/field/email/missing': 675,
 'atp/field/image/missing': 675,
 'atp/field/opening_hours/missing': 675,
 'atp/field/operator/missing': 675,
 'atp/field/operator_wikidata/missing': 675,
 'atp/field/phone/invalid': 31,
 'atp/field/phone/missing': 35,
 'atp/field/postcode/missing': 675,
 'atp/field/state/from_reverse_geocoding': 128,
 'atp/field/state/missing': 549,
 'atp/field/street_address/missing': 1,
 'atp/field/twitter/missing': 675,
 'atp/field/website/invalid': 6,
 'atp/nsi/perfect_match': 675,
 'downloader/request_bytes': 429,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 124646,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 1.390583,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 7, 22, 13, 17, 37, 104001, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 1910476,
 'httpcompression/response_count': 1,
 'item_dropped_count': 13,
 'item_dropped_reasons_count/DropItem': 13,
 'item_scraped_count': 675,
 'log_count/INFO': 9,
 'memusage/max': 173187072,
 'memusage/startup': 173187072,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 7, 22, 13, 17, 35, 713418, tzinfo=datetime.timezone.utc),
 'z/type/flagship': 45,
 'z/type/store': 642,
 'z/type/storeTnf': 1}
```

Timeout may be an AWS thing, or you may need to bump `DOWNLOAD_TIMEOUT`.

**Comment by ckpiper** [comment]
It does work for me now as well.

**Comment by ckpiper** [comment]
Put it ready to review. Not sure why it is not working in the PR Workflow.

**Comment by iandees** [comment]
It's failing because the site is blocking connections, probably based on IP address.

**Comment by CloCkWeRX** [comment]
Fixes https://github.com/alltheplaces/alltheplaces/issues/2033 ?

**Pull request merged**
