### PR TITLE
[KFC] Modernise code

### PR DESCRIPTION
**Pull request by Cj-Malone**
Potential fix for #8626

Remove old and broken GB parsing

Remove bad name

Set closed on items without opening hours

### CODE REVIEW

**Comment by Cj-Malone** [comment]
https://gist.github.com/Cj-Malone/42e8517ca310f0a1fc9ace86800184fe

```python
{'atp/brand/KFC': 4266,
 'atp/brand_wikidata/Q524757': 4266,
 'atp/category/amenity/fast_food': 4266,
 'atp/cdn/cloudflare/response_count': 4268,
 'atp/cdn/cloudflare/response_status_count/200': 4268,
 'atp/closed_poi': 372,
 'atp/field/email/missing': 4266,
 'atp/field/image/missing': 4266,
 'atp/field/lat/missing': 1,
 'atp/field/lon/missing': 1,
 'atp/field/opening_hours/missing': 372,
 'atp/field/operator/missing': 4266,
 'atp/field/operator_wikidata/missing': 4266,
 'atp/field/website/invalid': 3,
 'atp/nsi/cc_match': 4266,
 'downloader/request_bytes': 1615022,
 'downloader/request_count': 4268,
 'downloader/request_method_count/GET': 4268,
 'downloader/response_bytes': 216605393,
 'downloader/response_count': 4268,
 'downloader/response_status_count/200': 4268,
 'elapsed_time_seconds': 59.529145,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 6, 16, 19, 22, 37, 399150, tzinfo=datetime.timezone.utc),
 'httpcache/hit': 4268,
 'httpcompression/response_bytes': 1397556780,
 'httpcompression/response_count': 4268,
 'item_scraped_count': 4266,
 'log_count/INFO': 10,
 'memusage/max': 166359040,
 'memusage/startup': 166359040,
 'request_depth_max': 1,
 'response_received_count': 4268,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 4267,
 'scheduler/dequeued/memory': 4267,
 'scheduler/enqueued': 4267,
 'scheduler/enqueued/memory': 4267,
 'start_time': datetime.datetime(2024, 6, 16, 19, 21, 37, 870005, tzinfo=datetime.timezone.utc),
 'x/Catering': 2063,
 'x/Delivery': 2485,
 'x/Drive Thru': 3609,
 'x/Gift Cards': 4197,
 'x/WiFi': 2754}
```

**Comment by davidhicks** [comment]
Can we use this opportunity to rename the spider to `kfc_gb` from `kfc`?

**Comment by iandees** [comment]
> Can we use this opportunity to rename the spider to `kfc_gb` from `kfc`?

This doesn't look to be GB-only after @Cj-Malone's changes.

**Comment by Cj-Malone** [comment]
`kfc_gb` is GB and IE, however they get the right `addr:country` so I'm not gonna cry about it. `kfc` is now only US, and has been for a while since it's GB bit stopped working. I'll rename it to `kfc_us`.

**Pull request merged**
