### PR TITLE
[Fonehouse GB] Add spider

### PR DESCRIPTION
**Pull request by TheUKHighStreet**
Can anyone give me a hint as to what I've done wrong here?

### CODE REVIEW

**Comment by TheUKHighStreet** [comment]
It does crawl the pages but doesn't scrape any data.
Each page has a ```
<script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "LocalBusiness",
            "address": {
                "@type": "PostalAddress",
                "streetAddress": "569/571 High Road",
                "addressLocality": "Tottenham",
                "addressRegion": "London",
                "postalCode": "N17 6SB",
                "addressCountry": ""
            }, ...
```
Shouldn't the parser be able to scrape this?

**Comment by TheUKHighStreet** [comment]
Still need the opening hours.

**Comment by Cj-Malone** [comment]
> It does crawl the pages but doesn't scrape any data. Each page has a
> 
> ```
> <script type="application/ld+json">
>         {
>             "@context": "http://schema.org",
>             "@type": "LocalBusiness",
>             "address": {
>                 "@type": "PostalAddress",
>                 "streetAddress": "569/571 High Road",
>                 "addressLocality": "Tottenham",
>                 "addressRegion": "London",
>                 "postalCode": "N17 6SB",
>                 "addressCountry": ""
>             }, ...
> ```
> 
> Shouldn't the parser be able to scrape this?

Probably broken in some way, `json_parser = "chompjs"` may help. The website 404s for me.

**Comment by TheUKHighStreet** [comment]
Thanks - tried with the json_parser but it still didn't work. The page seems to randomly give 404 errors but a few minutes later works fine.

**Pull request merged**
