### PR TITLE
[vernyi_ru] add spider (1223 locations)

### PR DESCRIPTION
**Pull request by panasonic-mafia**
Stats:

```json
{
  "atp/brand/Верный": 1223,
  "atp/brand_wikidata/Q110037370": 1223,
  "atp/category/shop/supermarket": 1223,
  "atp/field/brand/missing": 1223,
  "atp/field/city/missing": 1223,
  "atp/field/country/from_spider_name": 1223,
  "atp/field/email/missing": 1223,
  "atp/field/image/missing": 1223,
  "atp/field/name/missing": 1223,
  "atp/field/opening_hours/missing": 27,
  "atp/field/operator/missing": 1223,
  "atp/field/operator_wikidata/missing": 1223,
  "atp/field/phone/missing": 1223,
  "atp/field/postcode/missing": 1223,
  "atp/field/state/missing": 1223,
  "atp/field/street_address/missing": 1223,
  "atp/field/twitter/missing": 1223,
  "atp/field/website/missing": 1223,
  "atp/nsi/perfect_match": 1223,
  "downloader/request_bytes": 611,
  "downloader/request_count": 2,
  "downloader/request_method_count/GET": 2,
  "downloader/response_bytes": 121048,
  "downloader/response_count": 2,
  "downloader/response_status_count/200": 2,
  "elapsed_time_seconds": 5.186928,
  "feedexport/success_count/FileFeedStorage": 1,
  "finish_reason": "finished",
  "finish_time": "2023-12-30T20:29:21.525253+00:00",
  "httpcompression/response_bytes": 777821,
  "httpcompression/response_count": 1,
  "item_scraped_count": 1223,
  "log_count/INFO": 10,
  "log_count/WARNING": 27,
  "memusage/max": 142245888,
  "memusage/startup": 142245888,
  "response_received_count": 2,
  "robotstxt/request_count": 1,
  "robotstxt/response_count": 1,
  "robotstxt/response_status_count/200": 1,
  "scheduler/dequeued": 1,
  "scheduler/dequeued/memory": 1,
  "scheduler/enqueued": 1,
  "scheduler/enqueued/memory": 1,
  "start_time": "2023-12-30T20:29:16.338325+00:00"
}
```

### CODE REVIEW

**Comment by panasonic-mafia** [comment]
> "atp/field/brand/missing": 1223,

Brand was successfully assigned by `ApplyNSICategoriesPipeline`. 
Should we move `CheckItemPropertiesPipeline` below `ApplyNSICategoriesPipeline`?

@Cj-Malone @davidhicks @iandees

**Comment by Cj-Malone** [comment]
I can't remember why it was done in this order... I don't think anything will break so :+1: from me

**Comment by iandees** [comment]
I'd prefer that change in a different PR, so I'm going to merge this.

**Comment by panasonic-mafia** [comment]
Thanks for feedback!

**Pull request merged**
