### PR TITLE
[usave_za] add more detailed outlet profiling

### PR DESCRIPTION
**Pull request by mjoe999**
@arrival-spring : this represents the last that I had in the cupboard concerning ZA suppliers for now!

### CODE REVIEW

**Comment by arrival-spring** [comment]
Thanks, although this will now overlap with the shoprite and medirite spiders.

I've been working on a spider to replace them, this and also the checkers_za spiders as it turns out we can ping this JSON file on the shoprite holdings website and get results for all the brands in all the countries, with the appropriate parameters.

I'm just stuck on the file encoding being returned for a couple of the countries at the moment, as special characters are not working. Maybe I'll post what I have as a draft later.

**Comment by mjoe999** [comment]
@arrival-spring : sounds like you're on top of the game in South Africa and so are best placed to decide how the various brands in the group should be presented. All good!

**Comment by arrival-spring** [comment]
Well I've just been starting to get into this and adding missing chains that I'm aware of. I've made fairly decent coverage of the main ones in NSI, so that's a good source to start looking for missing brands here in ATP.

**Comment by arrival-spring** [comment]
I have now got it working in #9752, I'm sorry for your effort wasted here, but that gets all brands across many countries in Africa.

**Pull request closed without merging**
