### PR TITLE
Initial commit of CVS store, hours yet to be processed

### PR DESCRIPTION
**Pull request by kristinepetrosyan**

### CODE REVIEW

**Comment by kristinepetrosyan** [comment]
@iandees can you let me know why my build is failing in travis ci? I am able to generate an output.geojson file. 

```{"type":"FeatureCollection","features":[{"type": "Feature", "properties": {"addr:full": "2800 South 4th Avenue", "phone": "928-344-2341", "addr:city": "Yuma", "addr:state": "AZ", "addr:postcode": "85364", "ref": "https://www.cvs.com/store-locator/cvs-pharmacy-address/2800+South+4th+Avenue-Yuma-AZ-85364/storeid=9334", "website:": "https://www.cvs.com/store-locator/cvs-pharmacy-address/2800+South+4th+Avenue-Yuma-AZ-85364/storeid=9334", "hours": {"Store & Photo Hours": {"M-F": "8:00 AM - 9:00 PM", "Sat": "10:00 AM - 6:00 PM", "Sun": "10:00 AM - 6:00 PM"}, "Pharmacy Hours": {"M-F": "8:00 AM - 9:00 PM", "Sat": "10:00 AM - 6:00 PM", "Sun": "10:00 AM - 6:00 PM"}}}, "geometry": {"type": "Point", "coordinates": [32.6762, -114.626]}},
{"type": "Feature", "properties": {"addr:full": "1801 E Parks Hwy", "phone": "907-631-7201", "addr:city": "Wasilla", "addr:state": "AK", "addr:postcode": "99654", "ref": "https://www.cvs.com/store-locator/cvs-pharmacy-address/1801+E+Parks+Hwy-Wasilla-AK-99654/storeid=17404", "website:": "https://www.cvs.com/store-locator/cvs-pharmacy-address/1801+E+Parks+Hwy-Wasilla-AK-99654/storeid=17404", "hours": {"Store & Photo Hours": {"M-F": "9:00 AM - 9:00 PM", "Sat": "9:00 AM - 6:00 PM", "Sun": "9:00 AM - 6:00 PM"}, "Pharmacy Hours": {"M-F": "9:00 AM - 9:00 PM", "Sat": "9:00 AM - 6:00 PM", "Sun": "9:00 AM - 6:00 PM"}}}, "geometry": {"type": "Point", "coordinates": [61.5762, -149.406]}}```

**Comment by kristinepetrosyan** [comment]
@iandees ok let me do that

**Comment by kristinepetrosyan** [comment]
@iandees merged the upstream branch after syncing with upstream.

**Comment by kristinepetrosyan** [comment]
@iandees the build continue to fail even after doing that merge:

'locations/spiders/cvs.py couldn't save logfile to s3'

**Comment by nvkelso** [comment]
You should have access to the main repo, can you try filing the PR there
instead of from your fork to see if that makes the CI happy?

On Tue, Nov 28, 2017 at 1:01 PM, kristinepetrosyan <notifications@github.com

**Comment by kristinepetrosyan** [comment]
@nvkelso let me do that.

**Comment by kristinepetrosyan** [comment]
Closing this PR of my personal fork. I have opened #213 for the same work from the upstream repo.

**Comment by iandees** [comment]
I think Travis was refusing to propagate secure settings (like my AWS credentials) to builds that run from forks.

**Pull request closed without merging**
