### PR TITLE
Add City of Darwin Free Wi-Fi (42 hotspots)

### PR DESCRIPTION
**Pull request by davidhicks**
The Shapely library is imported to find the centroid of circles (51 vertice polygons) that are provided in the source data as the estimated range of each access point.

### CODE REVIEW

**Comment by davidhicks** [comment]
@iandees I've pulled in Shapely with this spider for more advanced geometry processing. I realise this is a fairly heavy dependency, but it is also suggested for import within #4295 and would additionally be useful for automatically raising errors about features in the middle of oceans, features not corresponding to country codes provided, etc.

**Comment by iandees** [comment]
Hmmm. I'm not excited about this for two reasons:

* The centroid of the areas here are not where the antennas are. Using centroids is similar to generating a name for a record where the source data doesn't specify its own name. Is there not a data source for this that shows the points?
* Adding shapely makes installation of the All the Places code significantly more difficult for people trying to do development. If you're lucky there's a pre-compiled wheel that includes gdal, but if you have to install from source then the install with gdal becomes more complicated.

**Comment by davidhicks** [comment]
> Hmmm. I'm not excited about this for two reasons:
> 
>     * The centroid of the areas here are not where the antennas are. Using centroids is similar to generating a name for a record where the source data doesn't specify its own name. Is there not a data source for this that shows the points?
> 
>     * Adding shapely makes installation of the All the Places code significantly more difficult for people trying to do development. If you're lucky there's a pre-compiled wheel that includes gdal, but if you have to install from source then the install with gdal becomes more complicated.

Unfortunately their source data is just a 51 sided polygon approximating a circle around each Wi-Fi access point. All their Polygons have the same radius, and therefore look like a simple and fairly useless buffer of 300-and-a-bit-metres around each coordinate in their source data for where the access points are located. There are other layers with point data for Wi-Fi access points, but they all look woefully out of date.

Shapely depends on GEOS which is a C/C++ library (homepage: https://libgeos.org/) and per https://libgeos.org/usage/download/#build-requirements is stated to have no dependencies beyond CMake and GCC/Clang/VisualC++ for building the library. As far as I'm aware, Shapely doesn't depend upon GDAL, even though GDAL itself depends on GEOS too. Shapely is in official package repositories on Debian, Ubuntu, Fedora, Arch, Gentoo and more per https://repology.org/project/python:shapely/versions   Does this help the situation?

**Comment by davidhicks** [comment]
I could hack together a custom algorithm for this spider to take the 51 vertices and attempt to find a centroid, avoiding the need for `Shapely` as a dependency. But if #4295 is suggesting `Shapely` (I'd be happy to implement this feature request by the way), and there are other benefits to be had with `Shapely` for warning on invalid locations in oceans, and invalid country codes, etc, I'd rather not hack a centroid algorithm if `Shapely` (or similar library) may be imported in the future.

**Pull request merged**
