### PR TITLE
Fixed Rite Aid spider

### PR DESCRIPTION
**Pull request by thekuiperbelt**
Fixed the scraper to capture all locations & capture brand information for Rite Aid, RediClinic, and Walgreens.

### CODE REVIEW

**Comment by thekuiperbelt** [comment]
Scraper now captures 3072/3072 locations.

**Comment by iandees** [comment]
#345

**Comment by thekuiperbelt** [comment]
I wonder why this was originally named **RiteaidPizzaSpider** :pizza: :upside_down_face:

**Comment by iandees** [comment]
🤔

**Pull request merged**
