### PR TITLE
not all abs shops are abc branded or having abc name

### PR DESCRIPTION
**Pull request by matkoniecz**
see say  https://www.openstreetmap.org/?mlat=50.042003&mlon=20.060863#map=19/50.04192/20.06127

IMG_20240702_173635
screen01

### CODE REVIEW

**Comment by matkoniecz** [comment]
from data I see no way to recover it

there is occasional `"format": "Supermarket"` in data but I do not see evidence of it being right

**Comment by matkoniecz** [comment]
>  raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
> KeyError: 'Feature does not support field: shop'

**Comment by Cj-Malone** [comment]
> raise KeyError(f"{self.**class**.**name**} does not support field: {key}")
> KeyError: 'Feature does not support field: shop'

Same as chorten_pl

**Comment by matkoniecz** [comment]
> Same as chorten_pl

ops. See #8765 for unbreak attempt

**Pull request merged**
