### PR TITLE
[lidl_lt][lidl_cy][lidl_ee][lidl_lv] Added new lidl country spiders

### PR DESCRIPTION
**Pull request by ckpiper**
Added some more lidl country spiders.

### CODE REVIEW

**Comment by panasonic-mafia** [comment]
Since these spiders look exactly the same it makes sense to reuse class of one of the spiders in others.

**Comment by iandees** [comment]
I agree on merging the spiders but merged too quickly. Please add a PR for that.

**Comment by ckpiper** [comment]
@iandees, When you say merge, does that mean merge most countries into one spider? Or as @panasonic-mafia said should I just use one spider as a parent spider and the rest as child spiders. This would be in a separate PR.

**Comment by panasonic-mafia** [comment]
For this case I prefer to have 4 spiders with common class, if one of the spiders errored it's higher probability that we notice that and fix it.

**Pull request merged**
