### PR TITLE
Add spider for Chemist Warehouse (AU) (491 stores)

### PR DESCRIPTION
**Pull request by davidhicks**
Closes issue #4530

### CODE REVIEW

**Comment by davidhicks** [comment]
CI is getting a 403 error so I guess the URL is geoblocked to Australian IP addresses?

**Comment by Cj-Malone** [comment]
It works from GB, so maybe a GitHub or US thing.

```python
{'atp/category/amenity/pharmacy': 491,
 'atp/category/multiple': 491,
 'atp/field/email/invalid': 2,
 'atp/field/image/missing': 491,
 'atp/field/twitter/missing': 491,
 'atp/field/website/missing': 491,
 'atp/nsi/perfect_match': 491,
 'downloader/request_bytes': 902,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 45787,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/403': 1,
 'elapsed_time_seconds': 6.993919,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 1, 4, 20, 1, 45, 637595),
 'httpcache/firsthand': 2,
 'httpcache/miss': 2,
 'httpcache/store': 2,
 'httpcompression/response_bytes': 293736,
 'httpcompression/response_count': 2,
 'item_scraped_count': 491,
 'log_count/DEBUG': 530,
 'log_count/INFO': 8,
 'log_count/WARNING': 1,
 'memusage/max': 119177216,
 'memusage/startup': 119177216,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/403': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2023, 1, 4, 20, 1, 38, 643676)}
```

**Review by Cj-Malone — APPROVED** [review]
@davidhicks Hope you don't mind, but I changed the opening hours a little. Otherwise looks good, thank you.

**Comment by davidhicks** [comment]
@Cj-Malone Thanks for the improvements to opening hours extraction :)

**Pull request merged**
