### PR TITLE
[HM] Add hardcoded country list to avoid blocking

### PR DESCRIPTION
**Pull request by sterojos**

### CODE REVIEW

**Comment by sterojos** [comment]
This spider seems to get 403'd in weekly runs, but I just ran it locally without problems. There's also another spider (`hm_nl`) which uses the same API and seems to have no issues.

Alternatively, the countries could be hardcoded into the spider.

**Comment by iandees** [comment]
Let's try it with the hardcoded country list?

**Comment by sterojos** [comment]
This works, but there are so many countries that it might be difficult to spot mistakes in the list in the future...

I'm thinking about iterating over all countries from `GeonamesCache` instead. This would waste some requests, but also ensure that no country is left out. 

The API returns an empty `stores` array if an invalid country is requested.

**Comment by iandees** [comment]
If it's just one query per country then I think I'm ok with iterating the whole list.

**Pull request merged**
