### PR TITLE
update remax_fr

### PR DESCRIPTION
**Pull request by abbensid2**

### CODE REVIEW

**Comment by iandees** [comment]
This doesn't seem to be getting any useful attributes. It might be because `DictParser` only looks for English keys? Can you try pulling fields out individually? At least address and maybe phone number?

**Comment by abbensid2** [comment]
> This doesn't seem to be getting any useful attributes. It might be because `DictParser` only looks for English keys? Can you try pulling fields out individually? At least address and maybe phone number?

There is no phone or address

```
  {
      "entity": "Region2",
      "regionName": "Charente - 16",
      "regionName2": null,
      "previousRegionName": "Nouvelle-Aquitaine",
      "name": null,
      "officeName": null,
      "id": null,
      "regionID": 2789,
      "previousRegionID": 270,
      "agentID": null,
      "officeNumber": null,
      "userPictureURL": null,
      "userPictureBase64": null,
      "localZone": null,
      "officePictureURL": null,
      "matchName": "Charente - 16",
      "matchID": "2789",
      "coordinates": {
          "latitude": 45.585560543995804,
          "longitude": 0.1490068527854905
      }
  },
```

**Comment by iandees** [comment]
Do the locations have website or something you can spider into for more information?

**Comment by abbensid2** [comment]
> Do the locations have website or something you can spider into for more information?

In the [website](https://www.remax.fr/agence/remax-avenir/75000) there is nothing to add

**Comment by iandees** [comment]
There's address and phone number information on the right:

image

**Comment by abbensid2** [comment]
PR is closed, new PR: [4406](https://github.com/alltheplaces/alltheplaces/pull/4406)

**Pull request closed without merging**
