### PR TITLE
Add Metizsoft store finder and sample brands

### PR DESCRIPTION
**Pull request by davidhicks**
Metizsoft is a store locator plugin for Shopify that appears to be widely used amongst smaller brands to allow look-up of stockists at independent or other retail chain stores. However, Metizsoft store locator is also used by some small brands for locating their brick and mortar stores.

### CODE REVIEW

**Comment by davidhicks** [comment]
NSI pull request for these two sample brands: https://github.com/osmlab/name-suggestion-index/pull/8019

**Comment by davidhicks** [comment]
Failing test_pipeline_state_cleanup.py is due to https://github.com/alltheplaces/alltheplaces/pull/5195 and not something that changes in this pull request.

**Comment by iandees** [comment]
Tests are passing after merging that PR + updating your branch. Let me know when you're ready to review.

**Comment by davidhicks** [comment]
Ready for merge @iandees

**Pull request merged**
