### PR TITLE
[yves_rocher] bump download timeout

### PR DESCRIPTION
**Pull request by panasonic-mafia**
```json
{
 "atp/brand/Yves Rocher": 1933,
 "atp/brand_wikidata/Q28496595": 1933,
 "atp/category/shop/beauty": 1933,
 "atp/field/country/from_website_url": 272,
 "atp/field/email/missing": 1933,
 "atp/field/image/missing": 1933,
 "atp/field/lat/missing": 7,
 "atp/field/lon/missing": 7,
 "atp/field/opening_hours/missing": 25,
 "atp/field/operator/missing": 1933,
 "atp/field/operator_wikidata/missing": 1933,
 "atp/field/phone/invalid": 16,
 "atp/field/phone/missing": 21,
 "atp/field/street_address/missing": 1,
 "atp/field/twitter/missing": 1933,
 "atp/nsi/cc_match": 1933,
 "downloader/request_bytes": 13487,
 "downloader/request_count": 33,
 "downloader/request_method_count/GET": 33,
 "downloader/response_bytes": 1507223,
 "downloader/response_count": 33,
 "downloader/response_status_count/200": 24,
 "downloader/response_status_count/301": 6,
 "downloader/response_status_count/500": 3,
 "elapsed_time_seconds": 5.696317,
 "feedexport/success_count/FileFeedStorage": 1,
 "finish_reason": "finished",
 "finish_time": "2024-07-30T12:30:51.131012+00:00",
 "httpcompression/response_bytes": 9061802,
 "httpcompression/response_count": 27,
 "item_scraped_count": 1933,
 "log_count/ERROR": 1,
 "log_count/INFO": 10,
 "memusage/max": 215646208,
 "memusage/startup": 215646208,
 "request_depth_max": 1,
 "response_received_count": 31,
 "retry/count": 2,
 "retry/max_reached": 1,
 "retry/reason_count/500 Internal Server Error": 2,
 "robotstxt/request_count": 13,
 "robotstxt/response_count": 13,
 "robotstxt/response_status_count/200": 13,
 "scheduler/dequeued": 20,
 "scheduler/dequeued/memory": 20,
 "scheduler/enqueued": 20,
 "scheduler/enqueued/memory": 20,
 "start_time": "2024-07-30T12:30:45.434695+00:00"
}
```

### CODE REVIEW

**Comment by panasonic-mafia** [comment]
Not sure why it's still failing: CI wait for 60s, that should be enough. The spider worked on my locals...

**Comment by matkoniecz** [comment]
Maybe they block scrapers? And proxy is needed.

And it worked for you as you connected from residential IP?

(?)

**Comment by iandees** [comment]
Try using Playwright. It might be that they're using SSL fingerprinting.

**Comment by panasonic-mafia** [comment]
Thanks for finishing up this PR @iandees!

**Pull request merged**
