### PR TITLE
Fix Perkins

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix  https://github.com/alltheplaces/alltheplaces/issues/2678
2024-03-23 02:12:15 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Perkins': 286,
 'atp/brand_wikidata/Q7169056': 286,
 'atp/category/amenity/restaurant': 286,
 'atp/cdn/cloudflare/response_count': 289,
 'atp/cdn/cloudflare/response_status_count/200': 289,
 'atp/field/email/missing': 286,
 'atp/field/image/missing': 278,
 'atp/field/lat/missing': 1,
 'atp/field/lon/missing': 1,
 'atp/field/opening_hours/missing': 284,
 'atp/field/operator/missing': 286,
 'atp/field/operator_wikidata/missing': 286,
 'atp/field/twitter/missing': 286,
 'atp/nsi/perfect_match': 286,
 'downloader/request_bytes': 118067,
 'downloader/request_count': 289,
 'downloader/request_method_count/GET': 289,
 'downloader/response_bytes': 15440768,
 'downloader/response_count': 289,
 'downloader/response_status_count/200': 289,
 'elapsed_time_seconds': 354.433489,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 3, 23, 2, 12, 15, 851865, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 72276181,
 'httpcompression/response_count': 289,
 'item_scraped_count': 286,
 'log_count/DEBUG': 586,
 'log_count/INFO': 14,
 'memusage/max': 285253632,
 'memusage/startup': 159707136,
 'request_depth_max': 1,
 'response_received_count': 289,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 288,
 'scheduler/dequeued/memory': 288,
 'scheduler/enqueued': 288,
 'scheduler/enqueued/memory': 288,
 'start_time': datetime.datetime(2024, 3, 23, 2, 6, 21, 418376, tzinfo=datetime.timezone.utc)}
2024-03-23 02:12:15 [scrapy.core.engine] INFO: Spider closed (finished)
ubuntu@codespaces-83b177:/workspaces/alltheplaces$

### CODE REVIEW

**Comment by iandees** [comment]
The latitude and longitude are available elsewhere on the page in a single big JSON blob. It's probably worth digging those out.

**Comment by CloCkWeRX** [comment]
Ah:
```
{content:{name:fA,id:"3540",menu_id:124353,address:"954 Gap Newport Pike",city:fA,state:g,country:a,latitude:39.8366245,longitude:-75.7966917,restaurantType:b,review_url:"https:\u002F\u002Fsearch.google.com\u002Flocal\u002Fwritereview?placeid=ChIJ79oK3QJUxokR0PJXpqjBZqM\n"},path:"locations\u002Fus\u002Fpa\u002Favondale\u002F954-gap-newport-pike"},
{content:{name:fB,id:"3813",menu_id:74941,address:"12 East Olive Avenue",city:fB,state:en,country:a,latitude:47.6609842,longitude:-117.4105787,restaurantType:c,review_url:c},path:"locations\u002Fus\u002Fwa\u002Fspokane\u002F12-east-olive-avenue"},
```

**Comment by CloCkWeRX** [comment]
To find just the store in question... look for where the function is invoked and find arguments aK and aM
```
:{}}}("US","Franchise","","Corporate",null,"MN","PA","link","multilink","FL",void 0,"IA","story","OH","WI",false,"SD",true,"url","TN","default","service","Sioux Falls","NE","Des Moines","6:00","22:00","f540c244-2252-409e-9dbe-63d7be77ce78","MO","menu",34637503,"Hudson","KS","ON","CA","Rapid City","NY","Winona","NJ","IN","ND","WY","https:\u002F\u002Fperkinsfranchising.com","\u002F","Willmar","Savannah","Moundsville","Milford","Little Falls","Independence","Germantown","Gardner","Collierville","Cloquet","Blytheville","Avon","IL","Noblesville","Hastings","Bloomington","Appleton","Green Bay","Memphis","Altoona","Erie","Sioux City","Bismarck","Allentown","Bethlehem","Madison","Kissimmee","Billings","Warren","Cedar Rapids","Naples","Ft Myers","Duluth","Holiday Meals","Holiday Bake Shop","956 1\u002F2 Mankato Avenue","3845","WV","CO","MT","ID",63332,"Butcher Block",34207,{},74919,44.0301454,"Bakery",-91.6210467,"https:\u002F\u002Fsearch.google.com\u002Flocal\u002Fwritereview?placeid=ChIJ59LjS0Fs-YcR8HfLRsLZQq4\n","asset","locations\u002Fus\u002Fmn\u002Fwinona\u002F956-1-2-mankoto-avenue","a30e6828-02df-49cf-afea-0323d7d40b48","pages\u002Four-story","Our Story","\u002Ffacebook","\u002Ftwitter","\u002Finstagram","3cfebbd5-f599-4143-ba2b-819d853d8bf9","pages\u002Fgift-cards","e4188564-34e8-4a3e-adf7-701e7e77d56d","pages\u002Fcatering","\u002Fnutrition","\u002Fgluten-free-information","\u002Fcareers","Work With Us","83a00452-887a-4257-ae2a-9083f93ee12c","be8acc23-95e0-45b2-8cad-cd86e8583f81","2021-01-21T17:36:39.000Z","https:\u002F\u002Fperkins-careers.careerplug.com\u002Fjobs","4331","2645 South 1st Street","2663","5835 East Arrowhead Parkway","2446","3-A Gateway Blvd. S.","GA","2579","105 N. Lafayette Avenue","2613","2400 N Avenue","2410","201 16th St. NE","2641","3939 S. Bolger Rd.","2509","130 W. Streetsboro, Unit 1","3829","1340 So Germantown Pkwy","2651","2000 E. Santa Fe","1269","960 W. Poplar Avenue","4322","Big Lake Drive & Hwy. 33","3826","1121 E Main St","AR","2493","1503 Traveler's Pointe","Rochester","Galesburg","Bartow","Colonia","Orlando","Edinboro","Lincoln","Omaha","Salina","Yankton","Pickering","Waterloo","Sudbury","Toronto","St Catharines","Niagara Falls","Salt Lake City","South Bend","Elkhart","Hazlet","Miamisburg","Ottawa","Colorado Springs","Loveland","Minnetonka","Lakeville","Chaska","Apple Valley","Bradenton","Venice","Sarasota","North Port","Port Charlotte","Englewood","Sidney","Bullhead City","Manitowoc","Oshkosh","Menominee","Dandridge","Newburgh","Wappingers Falls","Summerville","Lees Summit","Gladstone","Saint Joseph","Du Bois","Meadville","Johnstown","State College","Clarion","Lawrence","Topeka","Port St. Lucie","Anderson","Blaine","Buffalo","Fridley","Plymouth","https:\u002F\u002Fsearch.google.com\u002Flocal\u002Fwritereview?placeid=ChIJc67JFzBKs1IR95CdG4m3OqY\n","Golden Valley","Crystal","Brooklyn Park","Elk River","Maple Grove","Monticello","Marion","East Brunswick","Jackson","Clearwater","Indiana","Staten Island","Lemoyne","Hanover","Harrisburg","Gettysburg","Chambersburg","Olean","Eau Claire","Shawano","Wisconsin Rapids","Superior","Marshfield","Stevens Point","Menomonie","Minot","Grand Forks","Fargo","Sedalia","Maplewood","Roseville","New Brighton","Forest Lake","Eagan","Stillwater","Vadnais Heights","Red Wing","Newton","Marshalltown","Mason City","Clear Lake","Great Bend","Columbus","Drexel Hill","East Windsor","Forked River","Onalaska","Tomah","Mitchell","Watertown","Brookings","Spearfish","Ft. Pierre","Ponca City","Jefferson City","Tunkhannock","Scranton","Mt. Pocono","Wilkes-Barre","Bloomsburg","Selinsgrove","Mansfield","Lewisburg","Matamoras","Hazleton","Stroudsburg","Williamsport","Danville","East Stroudsburg","Dubuque","Plattsburgh","Ankeny","Fort Dodge","Ames","West Des Moines","Fairfield","Cincinnati","Mason","Ellensburg","WA","Northfield","Owatonna","Austin","Mankato","Albert Lea","Worthington","New Ulm","Faribault","Fairmont","Painesville","Middleburg Heights","Kingsport","Sandusky","2635","Ashland","Altamonte Spgs","Winter Park","Winter Springs","Apopka","Butte","Norfolk","Orange City","DeLand","Lady Lakes","Mt Dora","Spring Hill","Gainesville","Leesburg","Youngstown","Austintown","Viera","Alexandria","Sartell","St. Cloud","Burlington","Coralville","Peoria","Scottsbluff","North Platte","Grand Island","Kearney","Laramie","Gillette","Sheridan","Cheyenne","Casper","Wheeling","Longmont","Newark","McHenry","Bristol","Cape Coral","Estero","Lehigh Acres","Brainerd","Bemidji","Fergus Falls","Decatur","Urbana","Philadelphia","Doylestown","Twin Falls","Burley","Idaho Falls","Cortland","Blk River Falls","Avondale","Spokane","Marshall",75324,"Philly Cheese Phavorites",68587,"Oreo LTO",65511,"Doughnuts",65313,"Strawberry Bakery Treats",64434,"Chocolate Bakery Treats",61406,"Brunch Time Benedicts",62160,"Build Your Own Pie",63160,"Hearty & Homestyle",33236,34818,35326,"Pumpkin Bakery",81930,"Mother's Day Menu","Beverages","Retail Coffee",78273));
```

```
44.0301454,"Bakery",-91.6210467
```

**Comment by CloCkWeRX** [comment]
Every page I crawl, the JS structure is slightly different; and there's ~50 coordinates on the page.
I could cut through a lot of it and target just the big list of locations, then match the current path:
```
locations:[
        {content:{name:N,id:aW,menu_id:74919,address:aX,city:N,state:f,country:a,
        latitude:44.0301454,longitude:-91.6210467,restaurantType:b,review_url:"https:\u002F\u002Fsearch.google.com\u002Flocal\u002Fwritereview?placeid=ChIJ59LjS0Fs-YcR8HfLRsLZQq4\n"},path:"locations\u002Fus\u002Fmn\u002Fwinona\u002F956-1-2-mankoto-avenue"},
        {content:{name:O,id:aY,menu_id:74891,address:aZ,city:O,state:f,country:a,
        latitude:45.0973683,longitude:-95.0425824,restaurantType:b,review_url:"https:\u002F\u002Fsearch.google.com\u002Flocal\u002Fwritereview?placeid=ChIJYRTZ5TxZtVIRzCdX74tiMbk\n"},path:"locations\u002Fus\u002Fmn\u002Fwillmar\u002F2645-south-hwy--71"},
        {content:{name:u,id:a_,menu_id:74915,address:a$,city:u,state:q,country:a,
        latitude:43.5439241,longitude:-96.6542922,restaurantType:b,review_url:"https:\u002F\u002Fsearch.google.com\u002Flocal\u002Fwritereview?placeid=ChIJnR9gEU6zjocRCprNtV02AeA\n"},path:"locations\u002Fus\u002Fsd\u002Fsioux-falls\u002F5835-e--arrowhead-place"},
```

**Comment by CloCkWeRX** [comment]
@iandees ready, finally.

**Comment by iandees** [comment]
Nice, thanks for digging into it.

**Pull request merged**
