### PR TITLE
[amtrak_us] Fix and rename

### PR DESCRIPTION
**Pull request by arrival-spring**
Runs in #10732 failed because network is not a main field, so moving it to extras.

This doesn't work locally as I get an empty response on the start_url, but could be a geo issue.

### CODE REVIEW

**Comment by arrival-spring** [comment]
I'm not sure then. When I open https://www.amtrak.com/plan-your-trip.html the file https://maps.amtrak.com/services/MapDataService/stations/allStations comes up essentially empty as well.

Any thoughts from anyone?

**Comment by Cj-Malone** [comment]
Works in the weekly, and contains some CA locations.

https://www.alltheplaces.xyz/spiders.html?search=amtrak

**Comment by Cj-Malone** [comment]
Clicking "map" on [here](https://www.amtrak.com/routes/adirondack-train.html) is also broken. I assume they broke there backend, hopefully it will be fixed soon.

**Comment by arrival-spring** [comment]
> Works in the weekly, and contains some CA locations.

Ah yes, I didn't see them as they were only just over the border, I'll rename it again now

**Pull request merged**
