### PR TITLE
McDonalds - Norway

### PR DESCRIPTION
**Pull request by SelfnessAid**
For #1 

Added the Norway to McdonaldsSpider.

### CODE REVIEW

**Comment by SelfnessAid** [comment]
I am not sure why here is two Spiders.

**Comment by SelfnessAid** [comment]
@iandees 
we're getting timeout at mcdonalds.py.
we need to create another Spider to avoid timeout?

**Comment by iandees** [comment]
Don't worry about the timeout – it indicates the spider takes longer than a minute to run.

**Comment by SelfnessAid** [comment]
okay, got you.

**Pull request merged**
