### PR TITLE
freddys_us: fix and rename to freddys_frozen_custard_and_steakburgers_us

### PR DESCRIPTION
**Pull request by davidhicks**

### CODE REVIEW

**Comment by davidhicks** [comment]
@iandees @Cj-Malone As you've both worked with Playwright spiders before (and this is my first), do you have any tips for how to fix this spider to work with Playwright?

The site throws up a Javascript challenge to the requester, then redirects to the actual page.

Does custom_settings = {"COOKIES_ENABLED": True} need to be set in the spider, or Playwright keeps browser session history?

**Comment by Cj-Malone** [comment]
I had actually written a storefinder spider for use with Nomnom (and it used Playwright) IIRC it was still getting blocked. Playwright isn't as perfect as I first thought. But then again, neither is my browser, I seem to get "robot" checks quite frequently.

**Comment by Cj-Malone** [comment]
```python
import datetime

import chompjs
from scrapy import Spider
from scrapy.http import JsonRequest

from locations.dict_parser import DictParser
from locations.hours import OpeningHours

# https://nomnom-prod-api.jackinthebox.com/location


class NomnomSpider(Spider):
    dataset_attributes = {"source": "api", "api": "nomnom"}

    api = ""
    brand_filter = None
    custom_settings = {
        "USER_AGENT": None,  # Playwright sets its own
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        "PLAYWRIGHT_BROWSER_TYPE": "firefox",
        "DOWNLOAD_HANDLERS": {"https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler"},
        # "PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT": 60000,
    }

    def start_requests(self):
        today = datetime.date.today()
        next_week = today + datetime.timedelta(days=6)
        yield JsonRequest(
            url=f'{self.api}/restaurants?nomnom=calendars&nomnom_calendars_from={today.strftime("%Y%m%d")}&nomnom_calendars_to={next_week.strftime("%Y%m%d")}',
            meta={"playwright": True},
        )

    def parse(self, response, **kwargs):
        for location in chompjs.parse_js_object(response.text)["restaurants"]:
            if self.brand_filter:
                if location["brand"] != self.brand_filter:
                    continue

            item = DictParser.parse(location)

            if calendars := location.get("calendars", {}).get("calendar", []):
                if calendar := calendars[-1]:
                    oh = OpeningHours()
                    for rule in calendar["ranges"]:
                        oh.add_range(
                            rule.get("weekday"),
                            rule.get("start").split(" ")[-1],
                            rule.get("end").split(" ")[-1],
                            time_format="%H:%M",
                        )
                    item["opening_hours"] = oh.as_opening_hours()

            yield from self.parse_item(item, location)

    def parse_item(self, item, location, **kwargs):
        yield item
```

I don't think there is anything useful in it, it will have been one of my first Store Finder Spiders, and around the time I added Playwright. Don't remember why I used `chompjs.parse_js_object` not `response.json()`. Don't remember why I used 6 days. Don't know why my opening hours were a little different. But in the end I put it to the bottom of the todo list, or gave up, you decide.

**Comment by Cj-Malone** [comment]
I have no strong opinion on deleting broken spiders. As a plus, it's quite exhorting looking at the list of broken ones. As a negative, it's a decent todo list for ones to be fixed, removing them would lead us to forget about most of them.

I would quite like a NomnomSpider that works at some point though, maybe I'll reach out to them, but after a quick Google, it's not clear what it's marketing name is/who runs it.

**Comment by iandees** [comment]
I submitted a request to CloudFlare to be listed as a "friendly bot" ([see also](https://blog.cloudflare.com/friendly-bots/)). Last time I did this I never heard back, so maybe they aren't running this program anymore.

**Comment by Cj-Malone** [comment]
I've also done that in the last month or 2, but we're not on the [list](https://radar.cloudflare.com/traffic/verified-bots).

If you don't hear anything this time, I can try again from my TomTom email, if you're OK with that.

**Comment by Cj-Malone** [comment]
Note: there are currently 174 bots on that list. I wish I had checked at the start, we'd know if they still maintain the list or not.

**Pull request closed without merging**
