### PR TITLE
[The Fish & Chip Co ZA] Add spider

### PR DESCRIPTION
**Pull request by Cj-Malone**
Rel: https://github.com/osmlab/name-suggestion-index/commit/2b4557713f66e236502cfe7998f9c9fdca452529

### CODE REVIEW

**Comment by Cj-Malone** [comment]
> TheFishAndChipCOZASpider' instead of 'TheFishAndChipCoZASpider

The `CO` isn't a country. I'm OK with faking it though, if we need to please the linter.

**Comment by arrival-spring** [comment]
> > TheFishAndChipCOZASpider' instead of 'TheFishAndChipCoZASpider
> 
> The `CO` isn't a country. I'm OK with faking it though, if we need to please the linter.

When that first came up, other such spiders were renamed to _company

See:
https://github.com/alltheplaces/alltheplaces/pull/10631/commits/e4d3a54f24299c8004823309ccb2529072982256

**Comment by Cj-Malone** [comment]
> When that first came up, other such spiders were renamed to _company

Sounds good to me. Thanks

**Comment by arrival-spring** [comment]
Also, n.b. there is GoReviewApiSpider store finder which this could use. Maybe some more comments need putting there to make it more discoverable?

**Pull request merged**
