### PR TITLE
[American golf GB] Add spider

### PR DESCRIPTION
**Pull request by TheUKHighStreet**
Adding a spider for American Golf.

### CODE REVIEW

**Comment by TheUKHighStreet** [comment]
I thought that if I saved to a new branch it would just pull the commits in that branch.  Am I supposed to delete the other branch with previous commits in it?

**Comment by Cj-Malone** [comment]
It's difficult to know exactly what you did. I think you deleted a branch which caused the other PR to close. And I think this branch is based off the other, hence the noise. Don't worry about the noise, after the other PR is merged, one of us will get rid of the noise and when Ian merges this, he'll squash and clean the commit

**Comment by Cj-Malone** [comment]
Yeah, so you've committed to your master. I think one of the most important things with git is to keep your master/main clean and in sync with upstream. I don't know exactly how to do that just using the GitHub website, sorry.

**Comment by Cj-Malone** [comment]
Yeah it's fixable, if you were using git you'd delete your master and create a new branch tracking upstream/master. It'll be possible on the GitHub, but I don't know the buttons, sorry.

**Comment by TheUKHighStreet** [comment]
Thanks very much - I'll investigate.

**Pull request closed without merging**
