### PR TITLE
PDQ

### LINKED ISSUE #596: PDQ
http://eatpdq.com/

### PR DESCRIPTION
**Pull request by whoissteven**
Fixes #596

### CODE REVIEW

**Comment by whoissteven** [comment]
Hmmm... when trying that xpath on that error URL... it works.. will push again.

**Comment by SelfnessAid** [comment]
This spider occur NoneType error of city.
please check the [Log](https://s3.amazonaws.com/placescraper-results/results/pdq/2017-12-20-07-21-04/log.txt)

**Comment by whoissteven** [comment]
@SelfnessAid, I checked the logs of course.

There is an odd issue where this site will randomly produce the following HTML...:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /><title>Sitefinity trial version</title></head><body><div style=\'font-family: Arial; font-size: 14px; color: #666; position: absolute; top: 50%; left: 50%; width: 680px; height: 50px; margin-left: -340px; margin-top: -25px; text-align: center;\'><h1 style=\'font-size: 30px; color: #999; font-weight: normal; margin: 0; padding: 0;\'>You are running a trial version of <a title=\'Sitefnity CMS\' href=\'http://www.sitefinity.com\' style=\'border-bottom: 1px dotted #ccc; color: #999; text-decoration: none;\'>Sitefinity 9.2</a>.</h1><p style=\'margin:0; padding: 0;\'>To proceed with your evaluation, press <a href=\'http://eatpdq.qatserver.com/locations/find-a-location\'>Continue</a> or refresh the page.</p></div></body></html>

STRANGE

**Comment by SelfnessAid** [comment]
you can solve above issue with error-exception processing.

**Comment by whoissteven** [comment]
@SelfnessAid, thank you. Already on it :). Just had to replicate the issue locally and it made it easier.
None-the-less, I appreciate the tip!!!

**Comment by whoissteven** [comment]
NOTE: This place is extremely good.

**Pull request merged**
