### PR TITLE
La Rosa's

### LINKED ISSUE #22: La Rosa's
https://www.larosas.com/find/

### PR DESCRIPTION
**Pull request by SelfnessAid**
Fixes #22

### CODE REVIEW

**Comment by iandees** [comment]
It looks like you're adding several files here. Please limit your pull request to a single new spider.

**Comment by SelfnessAid** [comment]
I pulled source code from master before I commit.
so it has several files.
We don't need to merge from master before commit?

**Comment by iandees** [comment]
You shouldn't need to merge master into your branch because you should only be adding files. You can merge if you'd like, but it shouldn't result in the diff showing them getting added because these files are already in master.

Also, please don't include the `.DS_Store` files.

**Comment by SelfnessAid** [comment]
okay, got you.

**Comment by SelfnessAid** [comment]
@iandees I need to commit again?

**Comment by iandees** [comment]
🤔  I'm not sure how you got so many files into this pull request. I'll clean it up.

**Comment by iandees** [comment]
I think what might have happened is that you made your branch `22-larosas` from one of your other branches that haven't been merged in yet.

Every time you start working on a new spider make sure you create your branch from the `master` branch so that it will merge in cleanly.

**Comment by iandees** [comment]
I'm going to close this one and merge in #270.

**Comment by SelfnessAid** [comment]
thanks, @iandees

**Pull request closed without merging**
