### PR TITLE
Add Masoutis (GR)

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix https://github.com/alltheplaces/alltheplaces/issues/9107

TODO: All of the extras are probably overkill

### CODE REVIEW

**Comment by iandees** [comment]
No coords?

**Comment by iandees** [comment]
I'm surprised `DictParser` didn't get it 🤔

**Comment by CloCkWeRX** [comment]
Langitude!
(Also the mistake I made)

**Comment by iandees** [comment]
Ohh good catch!

**Comment by matkoniecz** [comment]
amenity=bakery? See #10228

**Pull request merged**
