### PR TITLE
Add M-Texx (BG) (362 locations)

### LINKED ISSUE #6038: M-texx clothes and shoes containers
### Brand name

M-texx

### Wikidata ID

Q122947768

### Store finder url(s)

https://m-texx.com/локации

It requires parsing of all `li` html elements. The four digit numbers are postcodes, there is no `ref` system.

### PR DESCRIPTION
**Pull request by Dimitar5555**
Resolves #6038.

### CODE REVIEW

**Comment by Dimitar5555** [comment]
It seems like it's almost done. I'm not sure why it's complaining about the lack of `ref`. Also some coordinates are in `43°29'39.4"N 24°04'44.9"E` format. I'm not sure if they are automatically converted or not.

**Comment by iandees** [comment]
> I'm not sure why it's complaining about the lack of ref

Every item that a spider produces needs to have a `ref` property set that is unique per place. We do this to create unique IDs and to remove duplicate places.

> some coordinates are in 43°29'39.4"N 24°04'44.9"E format. I'm not sure if they are automatically converted or not

They won't be converted, no. Can you please convert them?

**Comment by Dimitar5555** [comment]
> > I'm not sure why it's complaining about the lack of ref
> 
> Every item that a spider produces needs to have a `ref` property set that is unique per place. We do this to create unique IDs and to remove duplicate places.

It seemed like they are generated automagically in other spiders. Am I missing something here? 

> > some coordinates are in 43°29'39.4"N 24°04'44.9"E format. I'm not sure if they are automatically converted or not
> 
> They won't be converted, no. Can you please convert them?

Should be done.

**Comment by Dimitar5555** [comment]
There are 5 locations that are not in the ATP dataset. One of them is "Coming soon", the other 4 have no coordinates. Otherwise it should be good to go.

**Comment by iandees** [comment]
> It seemed like they are generated automagically in other spiders. Am I missing something here?

Yea, true. I forgot that we moved away from requiring ref a while ago. If we can't find a stable identifier for each location we will generate one randomly. This is less ideal, but if there isn't any data there then it's the best we can do.

**Pull request merged**
