### PR TITLE
Add Baskin-Robbins (GB/IE/JE) (130 stores)

### PR DESCRIPTION
**Pull request by davidhicks**
All locations appear to be colocated at Cineworld or Millie's Cookies. Branding appears to be separate and distinct from each other, such that Baskin-Robbins appears as a store-within-a-store.

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Ideally we'd get `located_in` on these.

**Comment by davidhicks** [comment]
Can do!

Are you able to check whether [cineworld ](https://www.cineworld.co.uk/) has a store locator that could be added? It's geoblocked from Australia.

I'll add [Millie's](https://www.milliescookies.com/about-us/our-stores)

**Comment by Cj-Malone** [comment]
I thought I already had written one, but evidently not. Yeah, I'll do it now.

**Comment by davidhicks** [comment]
Thanks.

I've added Millie's in #5686

**Comment by Cj-Malone** [comment]
https://github.com/alltheplaces/alltheplaces/pull/5687

**Review by Cj-Malone — APPROVED** [review]
Thank you

**Pull request merged**
