### PR TITLE
[Sweaty betty] add spider

### PR DESCRIPTION
**Pull request by TheUKHighStreet**

### CODE REVIEW

**Comment by TheUKHighStreet** [comment]
The opening hours are included in the json as escaped html but I'm not quite sure how to parse them.
I hadn't added this spider because there aren't any coordinates - but I've seen that there are other spiders without coordinates - so is that ok?

**Comment by CloCkWeRX** [comment]
#9735

**Comment by CloCkWeRX** [comment]
Yup, missing coordinates is a bit annoying but still okay

**Comment by CloCkWeRX** [comment]
Also, https://github.com/search?q=repo%3Aalltheplaces%2Falltheplaces%20mobify&type=code - is this similar to the existing/a new Storefinder?

**Comment by iandees** [comment]
I'm going to merge this, but we should definitely look to see if Mobify can be extracted as a store locator.

**Pull request merged**
