### PR TITLE
Fix lidl.de website

### PR DESCRIPTION
**Pull request by kalpeshtawde**

### CODE REVIEW

**Comment by kalpeshtawde** [comment]
I do not understand why it is in failure. The error code says it has added a comment but I do not see anything.

**Comment by iandees** [comment]
The logs from the spider have this stack trace:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/home/runner/work/alltheplaces/alltheplaces/locations/spiders/lidl_de.py", line 51, in parse_details
    json_data = json.loads(json_data.groups(1)[0])
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1034 (char 1033)
```

Also, it looks like it's not decoding Unicode properly.

**Comment by kalpeshtawde** [comment]
I don't see these logs anywhere. Could you please point me to the correct link?

**Comment by iandees** [comment]
Click on the red X, click details, expand the "Run spiders that have changed" step that failed, look for the S3 link to the logs.

**Comment by kalpeshtawde** [comment]
As of now I don't see any exception in the logs. However still it is in failure.
Log says `has no output` but I can see data in the logs. Any idea?

**Comment by iandees** [comment]
There's no output because all entries have the same `ref` output and are getting deduplicated.

**Comment by kalpeshtawde** [comment]
> There's no output because all entries have the same `ref` output and are getting deduplicated.

Thanks, that worked. All checks are passed now.

**Comment by iandees** [comment]
Great! Thanks for working through it.

**Pull request merged**
