### PR TITLE
[champs_sports_us] add spider (410 locations)

### PR DESCRIPTION
**Pull request by mjoe999**
A US sports shop brand:

'atp/brand/Champs Sports': 410,
 'atp/brand_wikidata/Q2955924': 410,
 'atp/category/shop/sports': 410,
 'atp/field/country/from_spider_name': 410,
 'atp/field/email/missing': 410,
 'atp/field/image/dropped': 410,
 'atp/field/image/missing': 410,
 'atp/field/lat/missing': 1,
 'atp/field/lon/missing': 1,
 'atp/field/opening_hours/missing': 25,
 'atp/field/operator/missing': 410,
 'atp/field/operator_wikidata/missing': 410,
 'atp/field/twitter/missing': 410,
 'atp/nsi/perfect_match': 410

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
### Brand name

Champs Sports

American sports retail store

### Wikidata ID

Q2955924
https://www.wikidata.org/wiki/Q2955924
https://www.wikidata.org/wiki/Special:EntityData/Q2955924.json

### Store finder url(s)

Official Url(s): https://stores.champssports.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q2955924 https://stores.champssports.com/`
```
```
Official Url(s): https://www.champssports.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q2955924 https://www.champssports.com/`
```
```

**Comment by Cj-Malone** [comment]
This is a perfect example of terrible names, it's not just the name/branch thing I'm trying to clean up with #5899. This is SEO trash + address.

> Champs Sports in 1200 Town Ctr Blvd Provo, Utah | We Know Game

To fix this we'd have to override a StructuredDataSpider function and drop the `name`, then we'd get it from NSI. It's a bit of a faff, I think we could have a `drop_attributes` variable on spiders, and a early pipeline to drop them.

**Comment by iandees** [comment]
Should the name be modified in an override of `process_item()`?

**Comment by Cj-Malone** [comment]
It could be fixed via:
```python
    def pre_process_data(self, ld_data, **kwargs):
        ld_data["name"] = None
```
or:
```python
    def post_process_item(self, item, response, ld_data, **kwargs):
        item["name"] = None
        yield item
```

However I'll do my PR with a pipeline, it may be useful for some other attributes like `image`.

**Pull request merged**
