### PR TITLE
Add spider for crocs_es

### PR DESCRIPTION
**Pull request by abbensid2**

### CODE REVIEW

**Comment by iandees** [comment]
It looks like this is still data for Spain, but there's some errors in the lat/lon. Can you change it back to crocs_es?

**Comment by abbensid2** [comment]
> It looks like this is still data for Spain, but there's some errors in the lat/lon. Can you change it back to crocs_es?

how I can do it?

**Comment by iandees** [comment]
Ah nevermind, I misunderstood one of the commits. Looks good.

**Comment by abbensid2** [comment]
> Ah nevermind, I misunderstood one of the commits. Looks good.

on the previous commit I tried to merge the two spiders crocs_es and crocs_eu but it doesn’t give the same results

**Pull request merged**
