### PR TITLE
feat: united colors of benetton

### PR DESCRIPTION
**Pull request by mickaelabdealy**

### CODE REVIEW

**Comment by Cj-Malone** [comment]
It looks like the website needs some tweaking https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/4551292473/united_colors_of_benetton/output.geojson

**Comment by mickaelabdealy** [comment]
> It looks like the website needs some tweaking https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/4551292473/united_colors_of_benetton/output.geojson

I don't get what you mean sorry

**Comment by Cj-Malone** [comment]
`"website": "/bludenz/werdenbergerstr-19",`

It should be a full URL. I can't see find the domain, so maybe just override `parse_item` and remove `website`

**Comment by mickaelabdealy** [comment]
ok i did not find any working domain for this url so I removed the field.

**Review by Cj-Malone — APPROVED** [review]

**Pull request merged**
