### PR TITLE
[Auchan FR] Add spider

### PR DESCRIPTION
**Pull request by karen-kerr**

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Does this cover... #923 ?

**Comment by iandees** [comment]
I think they're separate things? Can't tell.

**Comment by CloCkWeRX** [comment]
This one does seem to have some sub-branded auchan drive entries when I checked the map.
Whether it warrants a different wikidata ID or not, I'd probably lean towards no

**Comment by CloCkWeRX** [comment]
(https://www.auchandrive.fr redirects to https://www.auchan.fr/)

**Pull request merged**
