### PR TITLE
Address clean up pipeline: Strip small addresses across multiple attributes

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix https://github.com/alltheplaces/alltheplaces/issues/9241 in a very basic way

Later:
* Do we want to assert stripping all \W characters and _ so long as we cooerce the strings into unicode?

### CODE REVIEW

**Comment by matkoniecz** [comment]
If for example just `addr:city` or `addr:street_address` has content `-` it will not be dropped.

why not apply `if value.replace("-", "").replace("–", "").strip() == ""` check? It may look oddly specific but actually putting "----" or "-" as null seems quite common across world.

**Comment by CloCkWeRX** [comment]
> If for example just addr:city or addr:street_address has content - it will not be dropped.

Ah, it should be :) min_length < 2

**Comment by CloCkWeRX** [comment]
> why not apply if value.replace("-", "").replace("–", "").strip() == ""

So, this is a really good check for a common human language pattern; and I do agree you have the real world stats to show it.


For targetting specific characters/character sequences as "these 'never' appear in an address", I thought about it and it seemed like targetting via regex all of the non word characters (\W), plus one to two others (like `_` `--` or any repetition of a punctuation character) in a unicode context would be the best approach.

IE "----" might be surprisingly common, but I bet there's a next level down we'll find after we target that exact pattern.

But that's slightly above my regexp golf to go to that level.

**Comment by matkoniecz** [comment]
What about things like `addr:city=Foovar addr:street=Barfoo addr:housenumber=-` ? In such case, despite assembled address being link I would throw away  `addr:housenumber` field.

And you cannot throw away all single-character long housenumber fields :)

**Comment by iandees** [comment]
It doesn't look like this modifies the `addr:housenumber` field, so we don't need to worry there.

**Pull request merged**
